In [1]:
import numpy as np
import pandas as pd
import psycopg2
import pytz
from tqdm import tqdm
from datetime import timedelta
from dateutil.relativedelta import relativedelta

In [2]:
sales = pd.read_csv('pedidos-1743765883268.csv', sep=';', encoding='latin1')

In [3]:
df = sales[['account_id', 'sales_channel_id']].value_counts()
df = pd.DataFrame(df).reset_index()

In [4]:
# EPOCHS = 1000
# BATCH_SIZE = 32
# VALID_SPLIT = 0.1

In [5]:
SAO_PAULO_TZ = pytz.timezone('America/Sao_Paulo')
LOOKBACK = 1
# SEASONAL_PERIODS = (24, 24*7)
# COVERAGE = 0.33
END_DATE = pd.to_datetime(pd.to_datetime(sales['created_date'].max()).strftime("%Y-%m-%d %H:00:00"))
# START_DATE = END_DATE - timedelta(hours=END_DATE.hour)
START_DATE = END_DATE - timedelta(hours=23)
# TEST_SIZE = int((END_DATE - START_DATE).seconds / 60**2 + 1)

In [6]:
# OOT_DATE = START_DATE + timedelta(hours=23)

In [7]:
# OOT_PERIODS = int((OOT_DATE - END_DATE).seconds / 60**2 + 1)

In [8]:
# oot_dates = pd.DatetimeIndex([END_DATE+timedelta(hours=h) for h in range(1, OOT_PERIODS)], freq='h')
# df_oot = pd.DataFrame(index=oot_dates)

In [9]:
# df.drop('count', axis=1, inplace=True)
# for account_id in df['account_id'].unique():
#     df = pd.concat([df, pd.DataFrame({'account_id': [account_id], 'sales_channel_id': ['ALL']})], ignore_index=True)

In [10]:
# df

In [11]:
id_pairs = list(zip(df['account_id'], df['sales_channel_id']))
# id_pairs = list(zip(df_filtered['account_id'], df_filtered['sales_channel_id']))

In [12]:
weights_chan = {}
for account_id, sales_channel_id in tqdm(id_pairs):
    # if sales_channel_id == 'ALL':
    #     cond = (sales['account_id'] == account_id) & \
    #            (sales['status'].notna())
    # else:
    #     cond = (sales['account_id'] == account_id) & \
    #            (sales['sales_channel_id'] == sales_channel_id) & \
    #            (sales['status'].notna())
    cond = (sales['account_id'] == account_id) & \
           (sales['sales_channel_id'] == sales_channel_id) & \
           (sales['status'].notna())

    df_client = sales[cond].drop(['account_id', 'sales_channel_id'], axis=1)
    df_client['created_date'] = pd.to_datetime(df_client['created_date'], format='%Y-%m-%d %H:%M:%S.%f %z')
    df_client = df_client.sort_values('created_date').reset_index(drop=True)
    df_client['created_date'] = df_client['created_date'].dt.strftime("%Y-%m-%d %H:00:00").reset_index(drop=True)

    df_client_mod = df_client.groupby('created_date').agg(price_total_agg=('price_total', 'sum'), n_orders=('created_date', 'count'))
    df_client_mod.index = pd.to_datetime(df_client_mod.index, format='%Y-%m-%d %H:00:00')

    end_date = pd.to_datetime(END_DATE, format='%Y-%m-%d %H:%M:%S')
    start_date = end_date - relativedelta(months=LOOKBACK)
    date_index = pd.Series(pd.date_range(start=start_date, end=end_date, freq='h', name='created_date'))
    df_client_mod = pd.merge(date_index, df_client_mod, how='left', on='created_date').set_index('created_date')
    
    weights_chan[account_id] = {} if account_id not in weights_chan else weights_chan[account_id]
    
    df = df_client_mod['n_orders'].fillna(0)
    df = df.loc[df.index < START_DATE].copy()
    
    weights_chan[account_id][sales_channel_id] = df.median()

100%|██████████| 277/277 [05:25<00:00,  1.17s/it]

In [13]:
weights_df = pd.DataFrame(weights_chan)

weights_df

,5f5ed10c-7792-4080-970c-b11398e3f58f,9d39683a-47b3-4a18-942d-f1d741a47e8c,05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6,74abffac-6542-4eff-8eae-cc85463a5d02,f9129295-bb08-4330-b60c-9f0beadda521,60c8f748-e29d-4fce-9e66-584117ca2baf,40074fa8-e02b-4c91-a819-fe1e639b540d,173e2b27-8bc6-44d1-b581-a1913d6b1894,478cd985-f4fc-45b4-ac71-bf78cf11e07b,bfcbb283-4e53-41fd-9b31-aa818f7f23ce,...,b009c05b-326e-4ebe-988c-8d2229ec3a4c,22fde42e-45d7-46cd-9d6f-3a4dbabbc579,4f1c8b04-eb4b-4887-8c69-a096f0fda3ab,3dc15e4b-b60d-4c49-aae8-97cf9664af51,423a069b-27b8-44ed-9ef3-ca3cf9470970,0ad2f65b-ee0e-4d50-93e2-84b76282325f,aabe992c-cfad-4049-b5df-36c41f900a67,9d1296ca-9e4f-4840-b7b5-e12172acab78,457bce7b-9300-4c10-9a97-070b3c0d081d,2058f680-aace-4b31-aed4-f34397b75096
1,0.0,93.0,0.0,21.0,65.0,18.0,31.0,12.0,1.0,0.0,...,1.0,0.0,9.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0
9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
7,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,0.0,NaN,62.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN
20,0.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
35,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0.0,NaN,40.0,NaN,0.0,NaN,NaN,0.0,0.0,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
5,0.0,NaN,6.0,NaN,0.0,NaN,NaN,1.0,0.0,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
4,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
13,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,0.0,NaN,NaN,NaN,9.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,0.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,0.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,NaN,0.0,12.0,0.0,NaN,0.0,0.0,NaN,...,NaN,0.0,3.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
12,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0.0,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,0.0,NaN,NaN,NaN,6.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,0.0,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
weights_df = weights_df.stack().reset_index().rename(columns={'level_0': 'sales_channel_id', 'level_1': 'account_id', 0: 'weights'}).sort_values(by=['account_id', 'sales_channel_id'])

weights_df

     sales_channel_id                            account_id  weights
2                   1  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6      0.0
65                  3  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6     62.0
135                 4  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6      0.0
117                 5  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6      6.0
101                 6  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6     40.0
..                ...                                   ...      ...
253                36  f9129295-bb08-4330-b60c-9f0beadda521      0.0
274                38  f9129295-bb08-4330-b60c-9f0beadda521      6.0
217                39  f9129295-bb08-4330-b60c-9f0beadda521      0.0
272                42  f9129295-bb08-4330-b60c-9f0beadda521      0.0
275                43  f9129295-bb08-4330-b60c-9f0beadda521      0.0

[277 rows x 3 columns]

In [15]:
weights_chan_df = weights_df.groupby('account_id')['weights'].apply(lambda x: x / x.sum()).fillna(0).reset_index().rename(columns={0: 'weights'}).drop('level_1', axis=1)

weights_chan_df = pd.concat([weights_df['sales_channel_id'].reset_index(drop=True), weights_chan_df], axis=1)

weights_chan_df

     sales_channel_id                            account_id   weights
0                   1  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6  0.000000
1                   3  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6  0.574074
2                   4  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6  0.000000
3                   5  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6  0.055556
4                   6  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6  0.370370
..                ...                                   ...       ...
272                36  f9129295-bb08-4330-b60c-9f0beadda521  0.000000
273                38  f9129295-bb08-4330-b60c-9f0beadda521  0.049180
274                39  f9129295-bb08-4330-b60c-9f0beadda521  0.000000
275                42  f9129295-bb08-4330-b60c-9f0beadda521  0.000000
276                43  f9129295-bb08-4330-b60c-9f0beadda521  0.000000

[277 rows x 3 columns]

In [16]:
weights_acc_df = weights_df.groupby('account_id')['weights'].sum() / weights_df.groupby('account_id')['weights'].sum().sum()

weights_acc_df

account_id
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6    0.233261
0661e926-f219-456e-bde5-612fee6f891c    0.004320
0ad2f65b-ee0e-4d50-93e2-84b76282325f    0.006479
173e2b27-8bc6-44d1-b581-a1913d6b1894    0.028078
2058f680-aace-4b31-aed4-f34397b75096    0.000000
22fde42e-45d7-46cd-9d6f-3a4dbabbc579    0.000000
23797b7c-9df5-45e7-89cd-548bbb7bd98f    0.000000
3dc15e4b-b60d-4c49-aae8-97cf9664af51    0.000000
40074fa8-e02b-4c91-a819-fe1e639b540d    0.066955
423a069b-27b8-44ed-9ef3-ca3cf9470970    0.000000
457bce7b-9300-4c10-9a97-070b3c0d081d    0.000000
478cd985-f4fc-45b4-ac71-bf78cf11e07b    0.002160
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab    0.025918
50409b57-b000-43d5-9358-44c3081c4132    0.002160
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb    0.017279
5f5ed10c-7792-4080-970c-b11398e3f58f    0.000000
60c8f748-e29d-4fce-9e66-584117ca2baf    0.038877
60ca8452-5b14-481f-a637-8756f527aee8    0.000000
6276b87c-ebb2-11ed-a05b-0242ac120003    0.008639
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b    0.000000
7412074f-0f3a-4724-b035-7fb4db3174c8    0.000000
74abffac-6542-4eff-8eae-cc85463a5d02    0.045356
775dcad4-0733-4c22-8dbd-cd3ce344e891    0.004320
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b    0.002160
7db6eaca-fe22-41d7-bfb8-1fdde880feb8    0.002160
8fa00df1-38eb-426f-81a6-1185983e14cb    0.000000
92f116fe-5818-41db-9eb5-87445ad3818e    0.004320
9d1296ca-9e4f-4840-b7b5-e12172acab78    0.000000
9d39683a-47b3-4a18-942d-f1d741a47e8c    0.200864
aabe992c-cfad-4049-b5df-36c41f900a67    0.000000
ad942d1a-15ab-4a0d-83a8-ae82183ece53    0.012959
adc6fb62-09e7-44fd-a619-f787ecfd140b    0.006479
b009c05b-326e-4ebe-988c-8d2229ec3a4c    0.002160
b8c6ac4b-2999-40f4-ad33-17649fb2f0aa    0.002160
bfcbb283-4e53-41fd-9b31-aa818f7f23ce    0.000000
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4    0.000000
ca35e88d-d191-4722-b90c-92f4a249869b    0.004320
d639773a-df2c-421e-ac87-6918a754572f    0.000000
e2de40dd-743b-4105-9077-3f343fea980d    0.015119
f4471620-212b-4991-98d3-b498835d0c29    0.000000
f9129295-bb08-4330-b60c-9f0beadda521    0.263499
Name: weights, dtype: float64

In [17]:
weights_acc_df.sort_values(ascending=False)

account_id
f9129295-bb08-4330-b60c-9f0beadda521    0.263499
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6    0.233261
9d39683a-47b3-4a18-942d-f1d741a47e8c    0.200864
40074fa8-e02b-4c91-a819-fe1e639b540d    0.066955
74abffac-6542-4eff-8eae-cc85463a5d02    0.045356
60c8f748-e29d-4fce-9e66-584117ca2baf    0.038877
173e2b27-8bc6-44d1-b581-a1913d6b1894    0.028078
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab    0.025918
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb    0.017279
e2de40dd-743b-4105-9077-3f343fea980d    0.015119
ad942d1a-15ab-4a0d-83a8-ae82183ece53    0.012959
6276b87c-ebb2-11ed-a05b-0242ac120003    0.008639
adc6fb62-09e7-44fd-a619-f787ecfd140b    0.006479
0ad2f65b-ee0e-4d50-93e2-84b76282325f    0.006479
0661e926-f219-456e-bde5-612fee6f891c    0.004320
ca35e88d-d191-4722-b90c-92f4a249869b    0.004320
775dcad4-0733-4c22-8dbd-cd3ce344e891    0.004320
92f116fe-5818-41db-9eb5-87445ad3818e    0.004320
50409b57-b000-43d5-9358-44c3081c4132    0.002160
478cd985-f4fc-45b4-ac71-bf78cf11e07b    0.002160
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b    0.002160
7db6eaca-fe22-41d7-bfb8-1fdde880feb8    0.002160
b8c6ac4b-2999-40f4-ad33-17649fb2f0aa    0.002160
b009c05b-326e-4ebe-988c-8d2229ec3a4c    0.002160
22fde42e-45d7-46cd-9d6f-3a4dbabbc579    0.000000
f4471620-212b-4991-98d3-b498835d0c29    0.000000
2058f680-aace-4b31-aed4-f34397b75096    0.000000
d639773a-df2c-421e-ac87-6918a754572f    0.000000
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4    0.000000
bfcbb283-4e53-41fd-9b31-aa818f7f23ce    0.000000
9d1296ca-9e4f-4840-b7b5-e12172acab78    0.000000
23797b7c-9df5-45e7-89cd-548bbb7bd98f    0.000000
aabe992c-cfad-4049-b5df-36c41f900a67    0.000000
3dc15e4b-b60d-4c49-aae8-97cf9664af51    0.000000
5f5ed10c-7792-4080-970c-b11398e3f58f    0.000000
8fa00df1-38eb-426f-81a6-1185983e14cb    0.000000
423a069b-27b8-44ed-9ef3-ca3cf9470970    0.000000
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b    0.000000
457bce7b-9300-4c10-9a97-070b3c0d081d    0.000000
60ca8452-5b14-481f-a637-8756f527aee8    0.000000
7412074f-0f3a-4724-b035-7fb4db3174c8    0.000000
Name: weights, dtype: float64

In [18]:
dbname = 'railway'
username = 'sinatra'
pwd = '781B3XjpeuqE'
hostname = 'monorail.proxy.rlwy.net'
port = 25096

connection = psycopg2.connect(database=dbname, user=username, password=pwd, host=hostname, port=port)
cursor = connection.cursor()

In [19]:
id_pairs_tbats = cursor.execute("select distinct account_id, channel from public.forecast where model='TBATS_10';")
res_tbats = cursor.fetchall()

id_pairs_gb = cursor.execute("select distinct account_id, channel from public.forecast where model='GradientBoosting_10';")
res_gb = cursor.fetchall()

id_pairs_lstm = cursor.execute("select distinct account_id, channel from public.forecast where model='LSTM_10';")
res_lstm = cursor.fetchall()

id_pairs_ens = cursor.execute("select distinct account_id, channel from public.forecast where model='Ensemble_10';")
res_ens = cursor.fetchall()

id_pairs_chronos = cursor.execute("select distinct account_id, channel from public.forecast where model='amazon/chronos-bolt-base:v2025-03-09:cl(370):q(0.3,0.7)' and channel!='ALL';")
res_chronos = cursor.fetchall()

id_pairs_median = cursor.execute("select distinct account_id, channel from public.forecast where model='MEDIAN_MAD_60' and channel!='ALL';")
res_median = cursor.fetchall()

In [20]:
id_pairs = (
    set(res_tbats)
    .intersection(set(res_gb))
    .intersection(set(res_lstm))
    .intersection(set(res_ens))
    .intersection(set(res_chronos))
    .intersection(set(res_median))
)

id_pairs = set(res_tbats).intersection(set(res_gb))

In [21]:
id_pairs

{('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '1'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '3'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '4'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '5'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '6'),
 ('9d39683a-47b3-4a18-942d-f1d741a47e8c', '1'),
 ('9d39683a-47b3-4a18-942d-f1d741a47e8c', '2'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '1'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '10'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '11'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '13'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '15'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '16'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '17'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '18'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '19'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '2'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '20'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '21'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '22'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '24'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '25'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '26'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '27'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '29'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '3'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '31'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '32'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '33'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '34'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '35'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '36'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '38'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '39'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '4'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '42'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '43'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '5'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '6'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '7'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '8')}

In [22]:
gb_models = [f'GradientBoosting_{int(10*n)}' for n in range(1, 10)]
lstm_models = [f'LSTM_{int(10*n)}' for n in range(1, 10)]
tbats_models = [f'TBATS_{int(10*n)}' for n in range(1, 10)]
ens_models = [f'Ensemble_{int(10*n)}' for n in range(1, 10)]

In [23]:
id_pairs

{('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '1'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '3'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '4'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '5'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '6'),
 ('9d39683a-47b3-4a18-942d-f1d741a47e8c', '1'),
 ('9d39683a-47b3-4a18-942d-f1d741a47e8c', '2'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '1'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '10'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '11'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '13'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '15'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '16'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '17'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '18'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '19'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '2'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '20'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '21'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '22'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '24'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '25'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '26'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '27'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '29'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '3'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '31'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '32'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '33'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '34'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '35'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '36'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '38'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '39'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '4'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '42'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '43'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '5'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '6'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '7'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '8')}

In [24]:
df_forecast_metrics_norm = {}
scores = {}
# for model in gb_models + lstm_models + tbats_models + ens_models + ['amazon/chronos-bolt-base:v2025-03-09:cl(370):q(0.3,0.7)', 'MEDIAN_MAD_60']:
for model in gb_models + tbats_models:
    print('\n\n')
    print(model)
    df_forecast_metrics_norm[model] = {}
    
    for account_id, sales_channel_id in id_pairs:
        
        if sales_channel_id == 'ALL':
            cond = (sales['account_id'] == account_id) & \
                   (sales['status'].notna())
        else:
            cond = (sales['account_id'] == account_id) & \
                   (sales['sales_channel_id'] == int(sales_channel_id)) & \
                   (sales['status'].notna())

        df_client = sales[cond].drop(['account_id', 'sales_channel_id'], axis=1)
        df_client['created_date'] = pd.to_datetime(df_client['created_date'], format='%Y-%m-%d %H:%M:%S.%f %z')
        df_client = df_client.sort_values('created_date').reset_index(drop=True)
        df_client['created_date'] = df_client['created_date'].dt.strftime("%Y-%m-%d %H:00:00").reset_index(drop=True)

        df_client_mod = df_client.groupby('created_date').agg(price_total_agg=('price_total', 'sum'), n_orders=('created_date', 'count'))
        df_client_mod.index = pd.to_datetime(df_client_mod.index, format='%Y-%m-%d %H:00:00')

        end_date = pd.to_datetime(END_DATE, format='%Y-%m-%d %H:%M:%S')
        start_date = end_date - relativedelta(months=LOOKBACK)
        date_index = pd.Series(pd.date_range(start=start_date, end=end_date, freq='h', name='created_date'))
        df_client_mod = pd.merge(date_index, df_client_mod, how='left', on='created_date').set_index('created_date')\
        
        df_forecast_metrics_norm[model][account_id] = {} if account_id not in df_forecast_metrics_norm[model] else df_forecast_metrics_norm[model][account_id]
        for dataset in ['sales', 'orders']:
            if dataset == 'sales':
                col = 'price_total_agg'
            else:
                col = 'n_orders'
            
            df = df_client_mod[col].fillna(0)
            
            y_test = df.loc[(df.index >= START_DATE) & (df.index <= END_DATE)].copy()
        
            cursor.execute(f"select start, {dataset}_high, {dataset}_low, {dataset}_mean from public.forecast where account_id = '{account_id}' and channel = '{sales_channel_id}' and model = '{model}'")
            res = cursor.fetchall()
            
            df_forecast = pd.DataFrame(res, columns=['start', f'{dataset}_high', f'{dataset}_low', f'{dataset}_mean']) #[:len(y_test)].set_index(y_test.index)
            
            df_forecast[f'{dataset}_mean'].index = y_test.index
            df_forecast[f'{dataset}_low'].index = y_test.index
            df_forecast[f'{dataset}_high'].index = y_test.index
            
            forecast_mean = df_forecast[f'{dataset}_mean']
            forecast_low = df_forecast[f'{dataset}_low']
            forecast_high = df_forecast[f'{dataset}_high']
            
            forecast = pd.concat([y_test, forecast_mean, forecast_low, forecast_high], axis=1)
            forecast.columns = ['actual', 'forecast', 'lower', 'upper']
            
            df_forecast = forecast.assign(
                covered_pts=lambda x:
                    4*x['actual'].between(x['lower'], x['upper'], inclusive='both') +
                    2*(x['actual'].between(2*x['lower']-x['forecast'], x['lower'], inclusive='left') + x['actual'].between(x['upper'], 2*x['upper']-x['forecast'], inclusive='right')) +
                    1*(x['actual'].between(3*x['lower']-2*x['forecast'], 2*x['lower']-x['forecast'], inclusive='left') + x['actual'].between(2*x['upper']-x['forecast'], 3*x['upper']-2*x['forecast'], inclusive='right')),
                covered_width=lambda x: x['upper'] - x['lower'],
            )
            
            df_forecast_metrics = {}
            df_forecast_metrics['total_covered'] = df_forecast['covered_pts'].sum()
            df_forecast_metrics['avg_covered'] = df_forecast['covered_pts'].mean()
            df_forecast_metrics['avg_covered_width'] = df_forecast['covered_width'].mean()
            
            if dataset == 'orders':
                df_forecast_orders_metrics_norm = df_forecast_metrics['avg_covered'] / (1 + np.log(1+df_forecast_metrics['avg_covered_width']))
            else:
                df_forecast_sales_metrics_norm = df_forecast_metrics['avg_covered'] / (1 + np.log(1+df_forecast_metrics['avg_covered_width']))
        
        weight_chan = weights_chan_df.loc[(weights_chan_df['account_id'] == account_id) & (weights_chan_df['sales_channel_id'] == int(sales_channel_id)), 'weights'].values[0]
        df_forecast_metrics_norm[model][account_id][sales_channel_id] = weight_chan * (1/3*df_forecast_sales_metrics_norm + 2/3*df_forecast_orders_metrics_norm)
        
    scores[model] = np.sum([weights_acc_df[acc_id] * np.sum(list(df_forecast_metrics_norm[model][acc_id].values())) for acc_id in df_forecast_metrics_norm[model].keys()])

GradientBoosting_10
sales 47.669202125
orders 0.085734875
sales 56.97368816666667
orders 0.005812
sales 156.602127125
orders 0.147191125
sales 599.1236120833333
orders 0.22852562499999998
sales 20.95133720833333
orders 0.003479
sales 6711.045224583333
orders 0.9150155833333334
sales 179.04718516666665
orders 0.012879
sales 309.8672923333333
orders 0.49215241666666665
sales 0.0
orders 0.0
sales 427.5401616666666
orders 0.09313179166666667
sales 137.05355908333334
orders 0.06659933333333333
sales 121.09057970833334
orders 0.06300608333333334
sales 2.235588
orders 0.003273
sales 109.04678704166668
orders 0.056692791666666666
sales 1079.2183920416667
orders 0.144975375
sales 420.89998045833335
orders 0.9225365
sales 0.0
orders 0.0
sales 0.0
orders 0.0
sales 2962.0593900416666
orders 0.7167977916666667
sales 13.371590958333334
orders 0.0015555416666666667
sales 49.19008420833333
orders 0.10676175
sales 0.88405625
orders 0.0043805833333333336
sales 10.42432725
orders 0.017105833333333334
sales 32.638271833333334
orders 0.03277875
sales 0.0
orders 0.0
sales 636.724930875
orders 0.17542920833333334
sales 1153.386022875
orders 1.33762325
sales 0.5423
orders 0.000726
sales 0.0
orders 0.0
sales 628.2073525833333
orders 0.10756720833333333
sales 0.963691
orders 0.000488
sales 72.09083604166666
orders 0.12659791666666667
sales 685.2087252083334
orders 0.23525870833333332
sales 467.12981679166666
orders 0.07615958333333334
sales 0.0
orders 0.0
sales 35.67827716666667
orders 0.013090041666666668
sales 38.47588183333333
orders 0.005095958333333333
sales 42.618267583333335
orders 0.044287041666666666
sales 793.9282117500001
orders 0.24354345833333335
sales 0.0
orders 0.0
sales 181.39753195833336
orders 0.07484533333333333



GradientBoosting_20
sales 371.62970125
orders 0.245776875
sales 109.406964
orders 0.018719
sales 134.169259875
orders 0.2327567083333333
sales 1589.012673833333
orders 0.6042785
sales 20.67208125
orders 0.009312958333333333
sales 9589.533730000001
orders 1.7936811666666665
sales 262.810396
orders 0.091792
sales 507.7608118333333
orders 1.03279275
sales 0.0
orders 0.0
sales 581.714734375
orders 0.1366955
sales 371.99994033333337
orders 0.10156275
sales 114.38110883333333
orders 0.017264458333333333
sales 2.920731
orders 0.004004
sales 228.71985412499998
orders 0.08683941666666667
sales 2672.3717442083334
orders 0.4969699166666666
sales 799.313354625
orders 1.88566375
sales 0.0
orders 0.0
sales 0.0
orders 0.0
sales 4844.39289975
orders 1.6985253333333334
sales 59.66423604166667
orders 0.011588625
sales 175.08754208333335
orders 0.17295029166666667
sales 8.320465583333332
orders 0.009212958333333333
sales 35.24663820833333
orders 0.03733145833333333
sales 90.40795945833334
orders 0.08205074999999999
sales 0.0
orders 0.0
sales 1482.0785119166667
orders 0.3301292083333333
sales 3467.397969125
orders 2.0115607916666667
sales 4.836963
orders 0.00201
sales 0.0
orders 0.0
sales 1743.5659670416665
orders 0.17697983333333334
sales 8.0152
orders 0.00012
sales 139.83802041666667
orders 0.269582
sales 1751.7209825416667
orders 0.4353549583333333
sales 459.00024129166667
orders 0.16522916666666668
sales 0.0
orders 0.0
sales 42.94290220833333
orders 0.024385
sales 133.64682220833333
orders 0.04318875
sales 94.050780375
orders 0.07782708333333334
sales 1501.1848037083334
orders 0.466797875
sales 0.0
orders 0.0
sales 455.73404745833335
orders 0.16627916666666667



GradientBoosting_30
sales 290.380838375
orders 0.341270875
sales 124.83439604166666
orders 0.06351
sales 219.12328570833333
orders 0.294027125
sales 1878.7888397083334
orders 0.8154210833333333
sales 54.93778170833334
orders 0.010085708333333334
sales 14231.085403208332
orders 4.0294458749999995
sales 211.09876970833332
orders 0.11592000000000001
sales 639.1140672916666
orders 1.6113404166666667
sales 0.0
orders 0.0
sales 1320.4969665
orders 0.20225295833333334
sales 526.8213107916666
orders 0.14507633333333333
sales 234.79728491666665
orders 0.07263629166666667
sales 1.973731
orders 0.0028750000000000004
sales 461.87939
orders 0.2394777916666667
sales 3645.948479916667
orders 1.1777900833333332
sales 1182.8280107916667
orders 2.79339575
sales 0.0
orders 0.0
sales 0.0
orders 0.0
sales 7126.795153874999
orders 3.214508541666667
sales 40.989925416666665
orders 0.015108708333333333
sales 182.3435967083333
orders 0.22668891666666668
sales 5.236903541666667
orders 0.018488374999999998
sales 45.09985866666667
orders 0.048755875000000004
sales 118.366308125
orders 0.1200845
sales 0.0
orders 0.0
sales 1695.2826345833334
orders 0.49215020833333334
sales 3297.3640051666666
orders 2.5754024583333335
sales 16.719808
orders 0.002246
sales 0.0
orders 0.0
sales 2879.2802991666667
orders 0.34331429166666666
sales 9.295862999999999
orders 0.0013889999999999998
sales 198.193420125
orders 0.45938029166666666
sales 2657.844368875
orders 0.65333975
sales 1180.7745656666666
orders 0.18086483333333334
sales 0.0
orders 0.0
sales 52.34837641666667
orders 0.029591875
sales 182.98333316666665
orders 0.03556354166666666
sales 183.5470485
orders 0.143064625
sales 2131.988348375
orders 0.7001832083333334
sales 0.0
orders 0.0
sales 713.3571378749999
orders 0.23798370833333335



GradientBoosting_40
sales 480.66184545833335
orders 0.4270545416666667
sales 127.88793779166667
orders 0.078494
sales 285.4376522083333
orders 0.4748229583333334
sales 2814.7401253333333
orders 1.066008
sales 73.10823970833333
orders 0.021114624999999998
sales 20875.758542291667
orders 3.6265557916666666
sales 399.4629775416667
orders 0.228642
sales 1033.0466772500001
orders 2.150114541666667
sales 0.0
orders 0.0
sales 2143.859471625
orders 0.23827170833333333
sales 1073.9925159166667
orders 0.169179875
sales 297.77255383333335
orders 0.10669545833333333
sales 7.621052
orders 0.00559
sales 489.915676875
orders 0.18658716666666667
sales 4756.904020041667
orders 1.2317935833333333
sales 1562.5716043749999
orders 3.2831819583333335
sales 0.0
orders 0.0
sales 0.0
orders 0.0
sales 11633.553678125
orders 3.7302360833333332
sales 48.263436750000004
orders 0.01313225
sales 227.99426633333334
orders 0.3307977916666667
sales 11.829163041666668
orders 0.023049833333333335
sales 58.348413083333334
orders 0.09096549999999999
sales 189.87787225
orders 0.14338083333333332
sales 0.0
orders 0.0
sales 2958.8814294166664
orders 0.824638625
sales 4761.188062125
orders 4.411480500000001
sales 8.82852
orders 0.002072
sales 0.0
orders 0.0
sales 3221.278263375
orders 0.46942212499999997
sales 9.082921
orders 0.001956
sales 239.49391420833334
orders 0.5727164583333334
sales 3790.1477945416664
orders 0.8309780833333332
sales 1645.8507438333334
orders 0.319832875
sales 0.0
orders 0.0
sales 123.63096995833332
orders 0.05542875
sales 318.1498075416667
orders 0.06144129166666667
sales 153.82886908333333
orders 0.217817
sales 2760.9914285
orders 0.7422959166666666
sales 0.0
orders 0.0
sales 1118.9439519999999
orders 0.2972876666666667



GradientBoosting_50
sales 478.7735054583333
orders 0.36611004166666666
sales 248.85217866666667
orders 0.087187
sales 593.2710849166666
orders 0.4561807916666667
sales 4829.809627208333
orders 1.0992700416666665
sales 80.14987466666666
orders 0.010893166666666667
sales 22686.682555249998
orders 5.157499625
sales 991.7452023333334
orders 0.375855
sales 1405.2708488333335
orders 2.285381166666667
sales 0.0
orders 0.0
sales 2251.5428909583334
orders 0.370640625
sales 801.2401799166668
orders 0.21399695833333332
sales 313.91802566666667
orders 0.121368875
sales 23.614856
orders 0.010782
sales 569.6270011666667
orders 0.18008433333333332
sales 6931.063365166666
orders 1.6740590833333335
sales 2104.480592375
orders 4.815227875
sales 0.0
orders 0.0
sales 0.0
orders 0.0
sales 13946.388274916666
orders 4.5079162083333335
sales 83.251698625
orders 0.011109250000000001
sales 408.97708341666663
orders 0.5292959583333333
sales 38.74908691666666
orders 0.034110416666666664
sales 96.75087866666667
orders 0.103346875
sales 384.4720980833333
orders 0.17305945833333333
sales 0.0
orders 0.0
sales 3602.5540054166668
orders 1.0906494583333333
sales 6918.930337375
orders 5.213842416666666
sales 9.03499
orders 0.001485
sales 0.0
orders 0.0
sales 4993.310900083333
orders 0.56056525
sales 17.653418
orders 0.001335
sales 417.16791125000003
orders 0.7043979583333333
sales 4131.475743791667
orders 1.1855404166666668
sales 2000.5230805833335
orders 0.320285125
sales 0.0
orders 0.0
sales 139.88570979166667
orders 0.08798375000000001
sales 253.139753
orders 0.098298125
sales 196.04553233333334
orders 0.3084185
sales 3987.57490625
orders 1.1388371666666666
sales 0.0
orders 0.0
sales 1098.1946875833335
orders 0.40660308333333334



GradientBoosting_60
sales 674.556363875
orders 0.6902444583333334
sales 231.1622565
orders 0.169106
sales 593.2876794583334
orders 0.5136566666666667
sales 4818.15962725
orders 1.30851025
sales 105.16802125
orders 0.018930833333333334
sales 26383.919589333334
orders 7.110540833333334
sales 972.7322020833334
orders 0.30048800000000003
sales 1811.6355364166666
orders 2.8996567916666667
sales 0.0
orders 0.0
sales 3146.356611458333
orders 0.5070020833333333
sales 1205.0376135
orders 0.3306972083333333
sales 548.8374822083333
orders 0.241079625
sales 25.365539
orders 0.013845000000000001
sales 922.4395303333334
orders 0.48408141666666665
sales 6676.944838875
orders 1.7346955
sales 2675.586468541667
orders 5.2708315416666665
sales 0.0
orders 0.0
sales 0.0
orders 0.0
sales 16972.36465766667
orders 5.589797166666667
sales 145.14202933333334
orders 0.03399575
sales 550.46739925
orders 0.5105553333333334
sales 7.725978125
orders 0.02770483333333333
sales 71.5240915
orders 0.09491870833333334
sales 386.9486470833333
orders 0.22108379166666667
sales 0.0
orders 0.0
sales 3925.536268458334
orders 1.2192825
sales 8624.499947041668
orders 6.915549041666666
sales 10.706093000000001
orders 0.0032530000000000002
sales 0.0
orders 0.0
sales 6067.06826925
orders 0.618151625
sales 22.803537000000002
orders 0.0030670000000000003
sales 495.6169423333333
orders 1.0139095833333334
sales 4912.736224333333
orders 1.3867394583333335
sales 2179.262188166667
orders 0.4257417083333333
sales 0.0
orders 0.0
sales 177.48044037499997
orders 0.07424208333333333
sales 507.62801120833336
orders 0.07729895833333333
sales 381.1516347916667
orders 0.3112513333333333
sales 3648.278694458333
orders 1.4213785
sales 0.0
orders 0.0
sales 1282.944147875
orders 0.4739971666666667



GradientBoosting_70
sales 860.6241372916667
orders 1.0637976666666666
sales 394.1957650416667
orders 0.095423
sales 391.87103187499997
orders 0.9651087500000001
sales 6402.737457875
orders 1.8921069583333334
sales 170.82854583333335
orders 0.020983708333333333
sales 41720.88336120833
orders 6.327254458333333
sales 981.0820923333334
orders 0.366139
sales 1990.1234874166666
orders 3.6935482499999996
sales 0.0
orders 0.0
sales 3890.430478375
orders 0.6125780833333333
sales 1414.1140982916668
orders 0.3789175
sales 780.769679
orders 0.20513520833333332
sales 16.394491
orders 0.010066
sales 1328.333156375
orders 0.5169922916666666
sales 9461.877977166667
orders 2.369588166666667
sales 3402.4802320833332
orders 6.7494400416666664
sales 0.0
orders 0.0
sales 0.0
orders 0.0
sales 23876.012669500004
orders 6.864036
sales 295.64099004166667
orders 0.03742425
sales 762.34525725
orders 0.5953179583333333
sales 28.71355229166667
orders 0.043630833333333334
sales 144.184199625
orders 0.13168875
sales 383.1900412083333
orders 0.24206275
sales 0.0
orders 0.0
sales 5555.079529125
orders 1.6260632083333333
sales 7926.065443375
orders 8.592064458333333
sales 19.342026999999998
orders 0.004456
sales 0.0
orders 0.0
sales 9177.009344541666
orders 0.811604
sales 12.294579
orders 0.002623
sales 516.4234860416667
orders 0.9076787083333334
sales 6334.063018583333
orders 2.108056125
sales 4272.208415791666
orders 0.5759667083333333
sales 0.0
orders 0.0
sales 247.14674987499998
orders 0.10278387500000001
sales 573.9331225416666
orders 0.10580979166666667
sales 445.154268
orders 0.36264450000000004
sales 5763.176812625
orders 1.6652759583333332
sales 0.0
orders 0.0
sales 1881.371577875
orders 0.6265414583333333



GradientBoosting_80
sales 823.1642842083334
orders 0.9604746249999999
sales 373.00932825
orders 0.11866700000000001
sales 867.7643164166667
orders 1.0421434583333333
sales 6896.1104597916665
orders 2.6655801666666665
sales 238.110723625
orders 0.058935708333333336
sales 41675.8867405
orders 8.256858750000001
sales 1336.7157009999999
orders 0.641469
sales 2337.0335454583333
orders 4.64461325
sales 0.0
orders 0.0
sales 4013.0264722083334
orders 0.6653204583333333
sales 1616.1901243333332
orders 0.4591445416666667
sales 969.4676558333334
orders 0.16623725
sales 21.543342999999997
orders 0.018642
sales 1354.051757375
orders 0.5538945416666666
sales 12804.800485875
orders 3.0843175833333336
sales 3828.56042125
orders 8.080745458333334
sales 0.0
orders 0.0
sales 0.0
orders 0.0
sales 28441.442800583332
orders 8.611982041666666
sales 126.08462374999999
orders 0.04347958333333333
sales 771.3276720416667
orders 0.8863579583333333
sales 50.828401125
orders 0.05795004166666667
sales 167.294823125
orders 0.19650445833333333
sales 597.446453
orders 0.3356179166666667
sales 0.0
orders 0.0
sales 5466.298519249999
orders 1.9221005416666666
sales 10672.890856916667
orders 9.421357833333333
sales 32.71302
orders 0.0044870000000000005
sales 0.0
orders 0.0
sales 9431.585243625
orders 1.2100375833333332
sales 32.250657
orders 0.002035
sales 725.4616764583334
orders 1.333368125
sales 7346.839631874999
orders 2.1673251666666666
sales 3299.9233456666666
orders 0.6219447916666666
sales 0.0
orders 0.0
sales 291.0426987083333
orders 0.09542545833333334
sales 760.5518385
orders 0.11051274999999999
sales 635.3170343333334
orders 0.40754549999999995
sales 6130.027271166667
orders 2.1208059166666664
sales 0.0
orders 0.0
sales 2278.4767208333333
orders 0.6757664999999999



GradientBoosting_90
sales 1594.7809850833335
orders 1.328852125
sales 832.1753085416667
orders 0.21541200000000002
sales 1409.8423389166667
orders 1.4935150416666667
sales 11069.602392499999
orders 2.8659519583333335
sales 693.6604926250001
orders 0.04451691666666666
sales 51043.42569220834
orders 12.988249791666666
sales 1796.7727207083333
orders 0.499217
sales 2859.601834833333
orders 6.313480875
sales 0.0
orders 0.0
sales 4952.1833928333335
orders 0.902725125
sales 2140.3186940416667
orders 0.6369089166666667
sales 786.6344009583332
orders 0.15899583333333334
sales 40.414414
orders 0.022317
sales 1427.063083125
orders 0.8229643750000001
sales 11713.082994375
orders 3.5486715833333338
sales 5278.4250821666665
orders 9.55398325
sales 0.0
orders 0.0
sales 0.0
orders 0.0
sales 34258.810829291666
orders 11.268418375000001
sales 259.30410466666666
orders 0.06932545833333333
sales 1024.0718865000001
orders 1.0262549583333334
sales 82.83458908333334
orders 0.08117854166666667
sales 233.65102341666667
orders 0.21743041666666665
sales 762.7832350416667
orders 0.309915125
sales 0.0
orders 0.0
sales 8095.557191791667
orders 2.2057280833333333
sales 15212.983103375
orders 11.809574958333334
sales 19.128909
orders 0.006756000000000001
sales 0.0
orders 0.0
sales 10628.077458666667
orders 1.3328977916666667
sales 31.369488
orders 0.0034249999999999997
sales 976.3862285416667
orders 1.586362875
sales 9598.526435333333
orders 2.473123541666667
sales 4388.27633225
orders 0.8323454583333333
sales 0.0
orders 0.0
sales 433.73409979166667
orders 0.11439516666666666
sales 712.172882625
orders 0.10865545833333333
sales 1087.7406949166666
orders 0.6390615416666666
sales 7751.6733795833325
orders 2.2089482916666667
sales 0.0
orders 0.0
sales 2465.8821202916665
orders 0.7879740833333333



TBATS_10
sales 735.6997842916667
orders 1.347154625
sales 555.0917772916666
orders 0.16619608333333333
sales 821.30739525
orders 1.148034375
sales 3905.7540702499996
orders 1.0512049583333334
sales 218.72852645833333
orders 0.075434
sales 26567.00486425
orders 10.788679708333333
sales 800.0078505416667
orders 0.43696891666666665
sales 1092.3850950416665
orders 2.121080125
sales 0.0
orders 0.0
sales 1706.5505170416666
orders 0.3426784166666667
sales 1081.8679769166667
orders 0.316430375
sales 836.2467822499999
orders 0.20485033333333333
sales 80.847254
orders 0.044409874999999994
sales 534.028507625
orders 0.32937675
sales 5612.494164125
orders 1.5229065833333333
sales 2121.025481291667
orders 4.534934
sales 0.0
orders 0.0
sales 0.0
orders 0.0
sales 18230.894127208336
orders 4.915560166666666
sales 297.86884954166663
orders 0.09232316666666666
sales 421.08891620833333
orders 0.43730025
sales 69.78493300000001
orders 0.09917516666666666
sales 323.57743583333337
orders 0.18542470833333333
sales 534.335440875
orders 0.31232804166666667
sales 0.0
orders 0.0
sales 2555.4477437916667
orders 1.1930834166666666
sales 5920.0905238333335
orders 4.632308541666666
sales 72.54052066666667
orders 0.0163095
sales 0.0
orders 0.0
sales 11706.497971874998
orders 0.407313625
sales 61.477383
orders 0.009519999999999999
sales 355.88425925
orders 1.16544475
sales 2631.2389518333334
orders 1.1391250416666667
sales 1395.5863160833333
orders 0.26847662499999997
sales 0.0
orders 0.0
sales 425.7653963333333
orders 0.11575841666666666
sales 548.7239687916666
orders 0.141736375
sales 288.19595020833333
orders 0.213015875
sales 2934.727766875
orders 0.8302502083333333
sales 0.0
orders 0.0
sales 1092.8047496249999
orders 0.39707000000000003



TBATS_20
sales 1483.2517219583333
orders 2.7160117083333333
sales 1119.1261058333332
orders 0.3350693333333334
sales 1655.8460861249998
orders 2.314563666666667
sales 7874.429997791667
orders 2.119345
sales 440.980778375
orders 0.15208320833333333
sales 53562.005260875005
orders 21.751165416666666
sales 1612.9038602083335
orders 0.8809773750000001
sales 2202.3685587083332
orders 4.276330958333333
sales 0.0
orders 0.0
sales 3440.593632458333
orders 0.690877375
sales 2181.164891
orders 0.6379582083333334
sales 1685.96553425
orders 0.413000875
sales 162.99696058333333
orders 0.08953541666666666
sales 1076.660236
orders 0.6640597083333334
sales 11315.405838375
orders 3.0703469583333334
sales 4276.220769416666
orders 9.142925666666667
sales 0.0
orders 0.0
sales 0.0
orders 0.0
sales 36755.48870258334
orders 9.910310291666667
sales 600.5363787916666
orders 0.18613354166666665
sales 848.9615919166666
orders 0.881645625
sales 140.69410408333331
orders 0.19994820833333335
sales 652.3677175833333
orders 0.37383666666666665
sales 1077.2790472916665
orders 0.6296876666666666
sales 0.0
orders 0.0
sales 5152.063854708334
orders 2.4053872083333334
sales 11935.553947625
orders 9.339243666666666
sales 146.24967220833335
orders 0.03288183333333333
sales 0.0
orders 0.0
sales 23601.588103625003
orders 0.8211888333333334
sales 123.945169
orders 0.019192
sales 717.5018284166667
orders 2.3496650833333335
sales 5304.867270541667
orders 2.2966012499999997
sales 2813.655585125
orders 0.541278375
sales 0.0
orders 0.0
sales 858.3898907500001
orders 0.233381625
sales 1106.2879032083333
orders 0.28575625
sales 581.0347489166667
orders 0.4294633333333333
sales 5916.734118125
orders 1.6738759166666668
sales 0.0
orders 0.0
sales 2203.2146284166665
orders 0.8005365000000001



TBATS_30
sales 2255.9059814583334
orders 4.130834291666667
sales 1702.1003506666666
orders 0.5096134583333333
sales 2518.408059
orders 3.52026425
sales 11976.371554750001
orders 3.22335275
sales 670.6961204583333
orders 0.2313062916666667
sales 81463.48070862501
orders 33.0817645
sales 2453.096404125
orders 1.3398954583333333
sales 3349.624565416667
orders 6.5039538750000006
sales 0.0
orders 0.0
sales 5232.864819791666
orders 1.0507685416666666
sales 3317.3755006666665
orders 0.970282875
sales 2564.2173049166668
orders 0.628141
sales 247.90520254166665
orders 0.13617604166666666
sales 1637.5131951666665
orders 1.0099812083333333
sales 17209.817682041667
orders 4.669749708333334
sales 6503.78615325
orders 13.905650999999999
sales 0.0
orders 0.0
sales 0.0
orders 0.0

In [25]:
scores

{'GradientBoosting_10': np.float64(0.04837370077432962),
 'GradientBoosting_20': np.float64(0.08983507436464401),
 'GradientBoosting_30': np.float64(0.09349213409074955),
 'GradientBoosting_40': np.float64(0.16987421954403664),
 'GradientBoosting_50': np.float64(0.13828766067311277),
 'GradientBoosting_60': np.float64(0.11206200765285951),
 'GradientBoosting_70': np.float64(0.08438830487316965),
 'GradientBoosting_80': np.float64(0.10752557335695043),
 'GradientBoosting_90': np.float64(0.17054264615592468),
 'TBATS_10': np.float64(0.15266579879786793),
 'TBATS_20': np.float64(0.2610297349592931),
 'TBATS_30': np.float64(0.29242758372340993),
 'TBATS_40': np.float64(0.2576577095421148),
 'TBATS_50': np.float64(0.3986554530317775),
 'TBATS_60': np.float64(0.4433025500867279),
 'TBATS_70': np.float64(0.4638853034444387),
 'TBATS_80': np.float64(0.4576866804479057),
 'TBATS_90': np.float64(0.41140202184784536)}