In [1]:
import joblib
import numpy as np
import pandas as pd
import psycopg2
import pytz
from tqdm import tqdm
from datetime import timedelta
from dateutil.relativedelta import relativedelta

In [2]:
sales = pd.read_csv('pedidos-1743765883268.csv', sep=';', encoding='latin1')

In [3]:
df = sales[['account_id', 'sales_channel_id']].value_counts()
df = pd.DataFrame(df).reset_index()

In [4]:
# EPOCHS = 1000
# BATCH_SIZE = 32
# VALID_SPLIT = 0.1

In [5]:
SAO_PAULO_TZ = pytz.timezone('America/Sao_Paulo')
LOOKBACK = 1
# SEASONAL_PERIODS = (24, 24*7)
# COVERAGE = 0.33
END_DATE = pd.to_datetime(pd.to_datetime(sales['created_date'].max()).strftime("%Y-%m-%d %H:00:00"))
# START_DATE = END_DATE - timedelta(hours=END_DATE.hour)
START_DATE = END_DATE - timedelta(hours=23)
# TEST_SIZE = int((END_DATE - START_DATE).seconds / 60**2 + 1)

In [6]:
# OOT_DATE = START_DATE + timedelta(hours=23)

In [7]:
# OOT_PERIODS = int((OOT_DATE - END_DATE).seconds / 60**2 + 1)

In [8]:
# oot_dates = pd.DatetimeIndex([END_DATE+timedelta(hours=h) for h in range(1, OOT_PERIODS)], freq='h')
# df_oot = pd.DataFrame(index=oot_dates)

In [9]:
df.drop('count', axis=1, inplace=True)
for account_id in df['account_id'].unique():
    df = pd.concat([df, pd.DataFrame({'account_id': [account_id], 'sales_channel_id': ['ALL']})], ignore_index=True)

In [10]:
# df

In [11]:
id_pairs = list(zip(df['account_id'], df['sales_channel_id']))
# id_pairs = list(zip(df_filtered['account_id'], df_filtered['sales_channel_id']))

In [12]:
# weights_chan = {}
# for account_id, sales_channel_id in tqdm(id_pairs):
#     if sales_channel_id == 'ALL':
#         cond = (sales['account_id'] == account_id) & \
#                (sales['status'].notna())
#     else:
#         cond = (sales['account_id'] == account_id) & \
#                (sales['sales_channel_id'] == sales_channel_id) & \
#                (sales['status'].notna())

#     df_client = sales[cond].drop(['account_id', 'sales_channel_id'], axis=1)
#     df_client['created_date'] = pd.to_datetime(df_client['created_date'], format='%Y-%m-%d %H:%M:%S.%f %z')
#     df_client = df_client.sort_values('created_date').reset_index(drop=True)
#     df_client['created_date'] = df_client['created_date'].dt.strftime("%Y-%m-%d %H:00:00").reset_index(drop=True)

#     df_client_mod = df_client.groupby('created_date').agg(price_total_agg=('price_total', 'sum'), n_orders=('created_date', 'count'))
#     df_client_mod.index = pd.to_datetime(df_client_mod.index, format='%Y-%m-%d %H:00:00')

#     end_date = pd.to_datetime(END_DATE, format='%Y-%m-%d %H:%M:%S')
#     start_date = end_date - relativedelta(months=LOOKBACK)
#     date_index = pd.Series(pd.date_range(start=start_date, end=end_date, freq='h', name='created_date'))
#     df_client_mod = pd.merge(date_index, df_client_mod, how='left', on='created_date').set_index('created_date')
    
#     weights_chan[account_id] = {} if account_id not in weights_chan else weights_chan[account_id]
    
#     df = df_client_mod['n_orders'].fillna(0)
#     df = df.loc[df.index < START_DATE].copy()
    
#     weights_chan[account_id][sales_channel_id] = df.median()

In [13]:
# weights_df = pd.DataFrame(weights_chan)

# weights_df

In [14]:
# weights_df = weights_df.stack().reset_index().rename(columns={'level_0': 'sales_channel_id', 'level_1': 'account_id', 0: 'weights'}).sort_values(by=['account_id', 'sales_channel_id'])

# weights_df

In [15]:
# weights_chan_df = weights_df.groupby('account_id')['weights'].apply(lambda x: x / x.sum()).fillna(0).reset_index().rename(columns={0: 'weights'}).drop('level_1', axis=1)

# weights_chan_df = pd.concat([weights_df['sales_channel_id'].reset_index(drop=True), weights_chan_df], axis=1)

# weights_chan_df

In [16]:
# weights_acc_df = weights_df.groupby('account_id')['weights'].sum() / weights_df.groupby('account_id')['weights'].sum().sum()

# weights_acc_df

In [17]:
# weights_acc_df.sort_values(ascending=False)

In [18]:
# joblib.dump(weights_chan_df, 'weights_chan_df.pkl')
# joblib.dump(weights_acc_df, 'weights_acc_df.pkl')

weights_chan_df = joblib.load('weights_chan_df.pkl')
weights_acc_df = joblib.load('weights_acc_df.pkl')

In [19]:
dbname = 'railway'
username = 'sinatra'
pwd = '781B3XjpeuqE'
hostname = 'monorail.proxy.rlwy.net'
port = 25096

connection = psycopg2.connect(database=dbname, user=username, password=pwd, host=hostname, port=port)
cursor = connection.cursor()

In [20]:
cursor.execute("select distinct account_id, channel from public.forecast where model='TBATS';")
res_tbats = cursor.fetchall()

cursor.execute("select distinct account_id, channel from public.forecast where model='GradientBoosting';")
res_gb = cursor.fetchall()

cursor.execute("select distinct account_id, channel from public.forecast where model='LSTM';")
res_lstm = cursor.fetchall()

cursor.execute("select distinct account_id, channel from public.forecast where model='Ensemble';")
res_ens = cursor.fetchall()

cursor.execute("select distinct account_id, channel from public.forecast where model='amazon/chronos-bolt-base:v2025-03-09:cl(370):q(0.3,0.7)';")
res_chronos1 = cursor.fetchall()

cursor.execute("select distinct account_id, channel from public.forecast where model='Chronos';")
res_chronos2 = cursor.fetchall()

cursor.execute("select distinct account_id, channel from public.forecast where model='MEDIAN_MAD_60';")
res_median = cursor.fetchall()

In [21]:
id_pairs = (
    set(res_tbats)
    .intersection(set(res_gb))
    .intersection(set(res_lstm))
    .intersection(set(res_ens))
    .intersection(set(res_chronos1))
    .intersection(set(res_chronos2))
    .intersection(set(res_median))
)


# id_pairs = set(res_tbats).intersection(set(res_gb))

In [22]:
id_pairs

{('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '1'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '3'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '5'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '6'),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', 'ALL'),
 ('0661e926-f219-456e-bde5-612fee6f891c', '1'),
 ('0661e926-f219-456e-bde5-612fee6f891c', 'ALL'),
 ('0ad2f65b-ee0e-4d50-93e2-84b76282325f', '1'),
 ('0ad2f65b-ee0e-4d50-93e2-84b76282325f', '2'),
 ('0ad2f65b-ee0e-4d50-93e2-84b76282325f', 'ALL'),
 ('173e2b27-8bc6-44d1-b581-a1913d6b1894', '1'),
 ('173e2b27-8bc6-44d1-b581-a1913d6b1894', '11'),
 ('173e2b27-8bc6-44d1-b581-a1913d6b1894', '14'),
 ('173e2b27-8bc6-44d1-b581-a1913d6b1894', '16'),
 ('173e2b27-8bc6-44d1-b581-a1913d6b1894', '18'),
 ('173e2b27-8bc6-44d1-b581-a1913d6b1894', '5'),
 ('173e2b27-8bc6-44d1-b581-a1913d6b1894', '8'),
 ('173e2b27-8bc6-44d1-b581-a1913d6b1894', '9'),
 ('173e2b27-8bc6-44d1-b581-a1913d6b1894', 'ALL'),
 ('2058f680-aace-4b31-aed4-f34397b75096', '1'),
 ('2058f680-aace-4b31-aed4-f34397b75096', 'ALL'),
 ('22fde42e-45d7-46cd-9d6f-3a4dbabbc579', '1'),
 ('22fde42e-45d7-46cd-9d6f-3a4dbabbc579', '10'),
 ('22fde42e-45d7-46cd-9d6f-3a4dbabbc579', '5'),
 ('22fde42e-45d7-46cd-9d6f-3a4dbabbc579', '6'),
 ('22fde42e-45d7-46cd-9d6f-3a4dbabbc579', '9'),
 ('22fde42e-45d7-46cd-9d6f-3a4dbabbc579', 'ALL'),
 ('3dc15e4b-b60d-4c49-aae8-97cf9664af51', '1'),
 ('3dc15e4b-b60d-4c49-aae8-97cf9664af51', '2'),
 ('3dc15e4b-b60d-4c49-aae8-97cf9664af51', 'ALL'),
 ('423a069b-27b8-44ed-9ef3-ca3cf9470970', '1'),
 ('423a069b-27b8-44ed-9ef3-ca3cf9470970', '2'),
 ('423a069b-27b8-44ed-9ef3-ca3cf9470970', 'ALL'),
 ('457bce7b-9300-4c10-9a97-070b3c0d081d', '1'),
 ('457bce7b-9300-4c10-9a97-070b3c0d081d', '3'),
 ('457bce7b-9300-4c10-9a97-070b3c0d081d', '5'),
 ('457bce7b-9300-4c10-9a97-070b3c0d081d', 'ALL'),
 ('478cd985-f4fc-45b4-ac71-bf78cf11e07b', '1'),
 ('478cd985-f4fc-45b4-ac71-bf78cf11e07b', '2'),
 ('478cd985-f4fc-45b4-ac71-bf78cf11e07b', '4'),
 ('478cd985-f4fc-45b4-ac71-bf78cf11e07b', '5'),
 ('478cd985-f4fc-45b4-ac71-bf78cf11e07b', '6'),
 ('478cd985-f4fc-45b4-ac71-bf78cf11e07b', 'ALL'),
 ('4f1c8b04-eb4b-4887-8c69-a096f0fda3ab', '1'),
 ('4f1c8b04-eb4b-4887-8c69-a096f0fda3ab', '2'),
 ('4f1c8b04-eb4b-4887-8c69-a096f0fda3ab', 'ALL'),
 ('50409b57-b000-43d5-9358-44c3081c4132', '1'),
 ('50409b57-b000-43d5-9358-44c3081c4132', 'ALL'),
 ('5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb', '1'),
 ('5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb', 'ALL'),
 ('60c8f748-e29d-4fce-9e66-584117ca2baf', '1'),
 ('60c8f748-e29d-4fce-9e66-584117ca2baf', '4'),
 ('60c8f748-e29d-4fce-9e66-584117ca2baf', 'ALL'),
 ('60ca8452-5b14-481f-a637-8756f527aee8', '1'),
 ('60ca8452-5b14-481f-a637-8756f527aee8', '10'),
 ('60ca8452-5b14-481f-a637-8756f527aee8', '6'),
 ('60ca8452-5b14-481f-a637-8756f527aee8', 'ALL'),
 ('6276b87c-ebb2-11ed-a05b-0242ac120003', '1'),
 ('6276b87c-ebb2-11ed-a05b-0242ac120003', '3'),
 ('6276b87c-ebb2-11ed-a05b-0242ac120003', '6'),
 ('6276b87c-ebb2-11ed-a05b-0242ac120003', '8'),
 ('6276b87c-ebb2-11ed-a05b-0242ac120003', '9'),
 ('6276b87c-ebb2-11ed-a05b-0242ac120003', 'ALL'),
 ('6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b', '1'),
 ('6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b', 'ALL'),
 ('7412074f-0f3a-4724-b035-7fb4db3174c8', '1'),
 ('7412074f-0f3a-4724-b035-7fb4db3174c8', '11'),
 ('7412074f-0f3a-4724-b035-7fb4db3174c8', '15'),
 ('7412074f-0f3a-4724-b035-7fb4db3174c8', '16'),
 ('7412074f-0f3a-4724-b035-7fb4db3174c8', '17'),
 ('7412074f-0f3a-4724-b035-7fb4db3174c8', '18'),
 ('7412074f-0f3a-4724-b035-7fb4db3174c8', '8'),
 ('7412074f-0f3a-4724-b035-7fb4db3174c8', 'ALL'),
 ('74abffac-6542-4eff-8eae-cc85463a5d02', '1'),
 ('74abffac-6542-4eff-8eae-cc85463a5d02', '2'),
 ('74abffac-6542-4eff-8eae-cc85463a5d02', 'ALL'),
 ('775dcad4-0733-4c22-8dbd-cd3ce344e891', '1'),
 ('775dcad4-0733-4c22-8dbd-cd3ce344e891', '2'),
 ('775dcad4-0733-4c22-8dbd-cd3ce344e891', 'ALL'),
 ('789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b', '1'),
 ('789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b', '3'),
 ('789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b', 'ALL'),
 ('7db6eaca-fe22-41d7-bfb8-1fdde880feb8', '1'),
 ('7db6eaca-fe22-41d7-bfb8-1fdde880feb8', '2'),
 ('7db6eaca-fe22-41d7-bfb8-1fdde880feb8', 'ALL'),
 ('8fa00df1-38eb-426f-81a6-1185983e14cb', '1'),
 ('8fa00df1-38eb-426f-81a6-1185983e14cb', 'ALL'),
 ('92f116fe-5818-41db-9eb5-87445ad3818e', '2'),
 ('92f116fe-5818-41db-9eb5-87445ad3818e', '5'),
 ('92f116fe-5818-41db-9eb5-87445ad3818e', 'ALL'),
 ('9d1296ca-9e4f-4840-b7b5-e12172acab78', '1'),
 ('9d1296ca-9e4f-4840-b7b5-e12172acab78', '4'),
 ('9d1296ca-9e4f-4840-b7b5-e12172acab78', '5'),
 ('9d1296ca-9e4f-4840-b7b5-e12172acab78', '9'),
 ('9d1296ca-9e4f-4840-b7b5-e12172acab78', 'ALL'),
 ('9d39683a-47b3-4a18-942d-f1d741a47e8c', '1'),
 ('9d39683a-47b3-4a18-942d-f1d741a47e8c', 'ALL'),
 ('aabe992c-cfad-4049-b5df-36c41f900a67', '1'),
 ('aabe992c-cfad-4049-b5df-36c41f900a67', '2'),
 ('aabe992c-cfad-4049-b5df-36c41f900a67', 'ALL'),
 ('ad942d1a-15ab-4a0d-83a8-ae82183ece53', '1'),
 ('ad942d1a-15ab-4a0d-83a8-ae82183ece53', '2'),
 ('ad942d1a-15ab-4a0d-83a8-ae82183ece53', 'ALL'),
 ('adc6fb62-09e7-44fd-a619-f787ecfd140b', '1'),
 ('adc6fb62-09e7-44fd-a619-f787ecfd140b', '2'),
 ('adc6fb62-09e7-44fd-a619-f787ecfd140b', 'ALL'),
 ('b009c05b-326e-4ebe-988c-8d2229ec3a4c', '1'),
 ('b009c05b-326e-4ebe-988c-8d2229ec3a4c', 'ALL'),
 ('bfcbb283-4e53-41fd-9b31-aa818f7f23ce', '1'),
 ('bfcbb283-4e53-41fd-9b31-aa818f7f23ce', '9'),
 ('bfcbb283-4e53-41fd-9b31-aa818f7f23ce', 'ALL'),
 ('c0cc925b-66c1-4b1c-b609-1bddc82ef4a4', '1'),
 ('c0cc925b-66c1-4b1c-b609-1bddc82ef4a4', 'ALL'),
 ('ca35e88d-d191-4722-b90c-92f4a249869b', '1'),
 ('ca35e88d-d191-4722-b90c-92f4a249869b', '12'),
 ('ca35e88d-d191-4722-b90c-92f4a249869b', '7'),
 ('ca35e88d-d191-4722-b90c-92f4a249869b', 'ALL'),
 ('d639773a-df2c-421e-ac87-6918a754572f', '1'),
 ('d639773a-df2c-421e-ac87-6918a754572f', '14'),
 ('d639773a-df2c-421e-ac87-6918a754572f', 'ALL'),
 ('e2de40dd-743b-4105-9077-3f343fea980d', '1'),
 ('e2de40dd-743b-4105-9077-3f343fea980d', 'ALL'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '1'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '10'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '11'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '15'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '16'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '17'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '18'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '19'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '2'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '20'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '21'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '22'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '24'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '25'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '26'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '27'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '29'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '3'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '31'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '32'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '33'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '34'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '35'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '36'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '38'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '39'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '4'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '42'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '43'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '5'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '6'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '7'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', '8'),
 ('f9129295-bb08-4330-b60c-9f0beadda521', 'ALL')}

In [23]:
len(id_pairs)

156

In [24]:
# gb_models = [f'GradientBoosting_{int(10*n)}' for n in range(1, 10)]
# lstm_models = [f'LSTM_{int(10*n)}' for n in range(1, 10)]
# tbats_models = [f'TBATS_{int(10*n)}' for n in range(1, 10)]
# ens_models = [f'Ensemble_{int(10*n)}' for n in range(1, 10)]
# chronos_models = [f'Chronos_{int(10*n)}' for n in range(1, 10)]

In [25]:
df_forecast_metrics1_norm, df_forecast_metrics2_norm = {}, {}
scores11, scores12 = {}, {}
# for model in gb_models + lstm_models + tbats_models + ens_models + chronos_models:
for model in ['GradientBoosting', 'LSTM', 'TBATS', 'Ensemble', 'Chronos']:
    print('\n\n')
    print(model)
    df_forecast_metrics1_norm[model], df_forecast_metrics2_norm[model]= {}, {}
    
    for account_id, sales_channel_id in id_pairs:
        
        print(account_id, sales_channel_id)
        
        if sales_channel_id == 'ALL':
            cond = (sales['account_id'] == account_id) & \
                   (sales['status'].notna())
        else:
            sales_channel_id = int(sales_channel_id)
            cond = (sales['account_id'] == account_id) & \
                   (sales['sales_channel_id'] == sales_channel_id) & \
                   (sales['status'].notna())

        df_client = sales[cond].drop(['account_id', 'sales_channel_id'], axis=1)
        df_client['created_date'] = pd.to_datetime(df_client['created_date'], format='%Y-%m-%d %H:%M:%S.%f %z')
        df_client = df_client.sort_values('created_date').reset_index(drop=True)
        df_client['created_date'] = df_client['created_date'].dt.strftime("%Y-%m-%d %H:00:00").reset_index(drop=True)

        df_client_mod = df_client.groupby('created_date').agg(price_total_agg=('price_total', 'sum'), n_orders=('created_date', 'count'))
        df_client_mod.index = pd.to_datetime(df_client_mod.index, format='%Y-%m-%d %H:00:00')

        end_date = pd.to_datetime(END_DATE, format='%Y-%m-%d %H:%M:%S')
        start_date = end_date - relativedelta(months=LOOKBACK)
        date_index = pd.Series(pd.date_range(start=start_date, end=end_date, freq='h', name='created_date'))
        df_client_mod = pd.merge(date_index, df_client_mod, how='left', on='created_date').set_index('created_date')
        
        df_forecast_metrics1_norm[model][account_id] = {} if account_id not in df_forecast_metrics1_norm[model] else df_forecast_metrics1_norm[model][account_id]
        df_forecast_metrics2_norm[model][account_id] = {} if account_id not in df_forecast_metrics2_norm[model] else df_forecast_metrics2_norm[model][account_id]
        for dataset in ['sales', 'orders']:
            if dataset == 'sales':
                col = 'price_total_agg'
            else:
                col = 'n_orders'
            
            df = df_client_mod[col].fillna(0)
            
            y_test = df.loc[(df.index >= START_DATE) & (df.index <= END_DATE)].copy()
        
            cursor.execute(f"select start, {dataset}_high, {dataset}_low, {dataset}_mean from public.forecast where account_id = '{account_id}' and channel = '{sales_channel_id}' and model = '{model}'")
            res = cursor.fetchall()
            
            df_forecast = pd.DataFrame(res, columns=['start', f'{dataset}_high', f'{dataset}_low', f'{dataset}_mean']) #[:len(y_test)].set_index(y_test.index)
            
            df_forecast[f'{dataset}_mean'].index = y_test.index
            df_forecast[f'{dataset}_low'].index = y_test.index
            df_forecast[f'{dataset}_high'].index = y_test.index
            
            forecast_mean = df_forecast[f'{dataset}_mean']
            forecast_low = df_forecast[f'{dataset}_low']
            forecast_high = df_forecast[f'{dataset}_high']
            
            forecast = pd.concat([y_test, forecast_mean, forecast_low, forecast_high], axis=1)
            forecast.columns = ['actual', 'forecast', 'lower', 'upper']
            
            df_forecast = forecast.assign(
                covered_pts1=lambda x:
                    4*x['actual'].between(x['lower'], x['upper'], inclusive='both') +
                    2*(x['actual'].between(2*x['lower']-x['forecast'], x['lower'], inclusive='left') + x['actual'].between(x['upper'], 2*x['upper']-x['forecast'], inclusive='right')) +
                    1*(x['actual'].between(3*x['lower']-2*x['forecast'], 2*x['lower']-x['forecast'], inclusive='left') + x['actual'].between(2*x['upper']-x['forecast'], 3*x['upper']-2*x['forecast'], inclusive='right')),
                covered_pts2=lambda x: x['actual'].between(3*x['lower']-2*x['forecast'], 3*x['upper']-2*x['forecast'], inclusive='both'),
                covered_width=lambda x: x['upper'] - x['lower']
            )
            
            df_forecast_metrics = {}
            df_forecast_metrics['total_covered1'] = df_forecast['covered_pts1'].sum()
            df_forecast_metrics['median_covered1'] = df_forecast['covered_pts1'].median()
            df_forecast_metrics['total_covered2'] = df_forecast['covered_pts2'].sum()
            df_forecast_metrics['median_covered2'] = df_forecast['covered_pts2'].median()
            df_forecast_metrics['median_covered_width'] = df_forecast['covered_width'].median()
            
            if dataset == 'orders':
                df_forecast_orders_metrics1_norm = df_forecast_metrics['median_covered1'] / (1 + np.log(1+df_forecast_metrics['median_covered_width']))
                df_forecast_orders_metrics2_norm = 10*df_forecast_metrics['median_covered2'] / (1 + np.log(1+df_forecast_metrics['median_covered_width']))
            else:
                df_forecast_sales_metrics1_norm = df_forecast_metrics['median_covered1'] / (1 + np.log(1+df_forecast_metrics['median_covered_width']))
                df_forecast_sales_metrics2_norm = 10*df_forecast_metrics['median_covered2'] / (1 + np.log(1+df_forecast_metrics['median_covered_width']))
        
        weight_chan = weights_chan_df.loc[(weights_chan_df['account_id'] == account_id) & (weights_chan_df['sales_channel_id'] == sales_channel_id), 'weights'].values[0]
        
        df_forecast_metrics1_norm[model][account_id][sales_channel_id] = weight_chan * (1/3*df_forecast_sales_metrics1_norm + 2/3*df_forecast_orders_metrics1_norm)
        # df_forecast_metrics1_norm[model][(account_id, sales_channel_id)] = weight_chan * (1/3*df_forecast_sales_metrics1_norm + 2/3*df_forecast_sales_metrics2_norm)
        
        df_forecast_metrics2_norm[model][account_id][sales_channel_id] = weight_chan * (1/3*df_forecast_orders_metrics2_norm + 2/3*df_forecast_sales_metrics2_norm)
        # df_forecast_metrics2_norm[model][(account_id, sales_channel_id)] = weight_chan * (1/3*df_forecast_orders_metrics2_norm + 2/3*df_forecast_sales_metrics2_norm)
        
    scores11[model] = np.sum([weights_acc_df[acc_id] * np.sum(list(df_forecast_metrics1_norm[model][acc_id].values())) for acc_id in df_forecast_metrics1_norm[model].keys()])
    scores12[model] = np.sum([weights_acc_df[acc_id] * np.sum(list(df_forecast_metrics2_norm[model][acc_id].values())) for acc_id in df_forecast_metrics2_norm[model].keys()])
    
    print(scores11[model], scores12[model]) # ()

GradientBoosting
f9129295-bb08-4330-b60c-9f0beadda521 32
60ca8452-5b14-481f-a637-8756f527aee8 10
775dcad4-0733-4c22-8dbd-cd3ce344e891 ALL
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 6
ca35e88d-d191-4722-b90c-92f4a249869b 7
f9129295-bb08-4330-b60c-9f0beadda521 8
775dcad4-0733-4c22-8dbd-cd3ce344e891 2
9d1296ca-9e4f-4840-b7b5-e12172acab78 1
9d1296ca-9e4f-4840-b7b5-e12172acab78 ALL
173e2b27-8bc6-44d1-b581-a1913d6b1894 9
f9129295-bb08-4330-b60c-9f0beadda521 34
f9129295-bb08-4330-b60c-9f0beadda521 6
6276b87c-ebb2-11ed-a05b-0242ac120003 8
74abffac-6542-4eff-8eae-cc85463a5d02 1
f9129295-bb08-4330-b60c-9f0beadda521 33
92f116fe-5818-41db-9eb5-87445ad3818e ALL
f9129295-bb08-4330-b60c-9f0beadda521 10
e2de40dd-743b-4105-9077-3f343fea980d ALL
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b 1
6276b87c-ebb2-11ed-a05b-0242ac120003 6
92f116fe-5818-41db-9eb5-87445ad3818e 2
7412074f-0f3a-4724-b035-7fb4db3174c8 1
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 ALL
d639773a-df2c-421e-ac87-6918a754572f ALL
8fa00df1-38eb-426f-81a6-1185983e14cb 1
6276b87c-ebb2-11ed-a05b-0242ac120003 9
478cd985-f4fc-45b4-ac71-bf78cf11e07b 4
478cd985-f4fc-45b4-ac71-bf78cf11e07b 1
2058f680-aace-4b31-aed4-f34397b75096 ALL
60ca8452-5b14-481f-a637-8756f527aee8 1
60ca8452-5b14-481f-a637-8756f527aee8 ALL
478cd985-f4fc-45b4-ac71-bf78cf11e07b 5
0661e926-f219-456e-bde5-612fee6f891c 1
775dcad4-0733-4c22-8dbd-cd3ce344e891 1
0661e926-f219-456e-bde5-612fee6f891c ALL
7412074f-0f3a-4724-b035-7fb4db3174c8 11
9d1296ca-9e4f-4840-b7b5-e12172acab78 4
7412074f-0f3a-4724-b035-7fb4db3174c8 17
7412074f-0f3a-4724-b035-7fb4db3174c8 8
f9129295-bb08-4330-b60c-9f0beadda521 21
457bce7b-9300-4c10-9a97-070b3c0d081d ALL
f9129295-bb08-4330-b60c-9f0beadda521 42
f9129295-bb08-4330-b60c-9f0beadda521 18
aabe992c-cfad-4049-b5df-36c41f900a67 2
f9129295-bb08-4330-b60c-9f0beadda521 38
173e2b27-8bc6-44d1-b581-a1913d6b1894 16
f9129295-bb08-4330-b60c-9f0beadda521 19
9d1296ca-9e4f-4840-b7b5-e12172acab78 5
f9129295-bb08-4330-b60c-9f0beadda521 ALL
0ad2f65b-ee0e-4d50-93e2-84b76282325f ALL
e2de40dd-743b-4105-9077-3f343fea980d 1
b009c05b-326e-4ebe-988c-8d2229ec3a4c ALL
f9129295-bb08-4330-b60c-9f0beadda521 2
478cd985-f4fc-45b4-ac71-bf78cf11e07b 6
7db6eaca-fe22-41d7-bfb8-1fdde880feb8 ALL
0ad2f65b-ee0e-4d50-93e2-84b76282325f 2
f9129295-bb08-4330-b60c-9f0beadda521 31
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab 2
7db6eaca-fe22-41d7-bfb8-1fdde880feb8 2
f9129295-bb08-4330-b60c-9f0beadda521 16
d639773a-df2c-421e-ac87-6918a754572f 14
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 1
d639773a-df2c-421e-ac87-6918a754572f 1
f9129295-bb08-4330-b60c-9f0beadda521 27
bfcbb283-4e53-41fd-9b31-aa818f7f23ce ALL
ad942d1a-15ab-4a0d-83a8-ae82183ece53 ALL
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 3
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 5
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b ALL
2058f680-aace-4b31-aed4-f34397b75096 1
457bce7b-9300-4c10-9a97-070b3c0d081d 3
f9129295-bb08-4330-b60c-9f0beadda521 24
ad942d1a-15ab-4a0d-83a8-ae82183ece53 2
173e2b27-8bc6-44d1-b581-a1913d6b1894 18
423a069b-27b8-44ed-9ef3-ca3cf9470970 ALL
f9129295-bb08-4330-b60c-9f0beadda521 3
7412074f-0f3a-4724-b035-7fb4db3174c8 15
3dc15e4b-b60d-4c49-aae8-97cf9664af51 ALL
173e2b27-8bc6-44d1-b581-a1913d6b1894 14
9d1296ca-9e4f-4840-b7b5-e12172acab78 9
423a069b-27b8-44ed-9ef3-ca3cf9470970 2
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 1
3dc15e4b-b60d-4c49-aae8-97cf9664af51 2
457bce7b-9300-4c10-9a97-070b3c0d081d 1
173e2b27-8bc6-44d1-b581-a1913d6b1894 ALL
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 ALL
aabe992c-cfad-4049-b5df-36c41f900a67 ALL
ca35e88d-d191-4722-b90c-92f4a249869b ALL
f9129295-bb08-4330-b60c-9f0beadda521 25
6276b87c-ebb2-11ed-a05b-0242ac120003 3
74abffac-6542-4eff-8eae-cc85463a5d02 2
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 6
f9129295-bb08-4330-b60c-9f0beadda521 1
0ad2f65b-ee0e-4d50-93e2-84b76282325f 1
b009c05b-326e-4ebe-988c-8d2229ec3a4c 1
adc6fb62-09e7-44fd-a619-f787ecfd140b ALL
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b 3
f9129295-bb08-4330-b60c-9f0beadda521 22
7db6eaca-fe22-41d7-bfb8-1fdde880feb8 1
adc6fb62-09e7-44fd-a619-f787ecfd140b 2
f9129295-bb08-4330-b60c-9f0beadda521 26
9d39683a-47b3-4a18-942d-f1d741a47e8c ALL
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab ALL
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 9
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4 ALL
92f116fe-5818-41db-9eb5-87445ad3818e 5
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb ALL
6276b87c-ebb2-11ed-a05b-0242ac120003 ALL
ca35e88d-d191-4722-b90c-92f4a249869b 12
60ca8452-5b14-481f-a637-8756f527aee8 6
7412074f-0f3a-4724-b035-7fb4db3174c8 16
478cd985-f4fc-45b4-ac71-bf78cf11e07b 2
f9129295-bb08-4330-b60c-9f0beadda521 36
bfcbb283-4e53-41fd-9b31-aa818f7f23ce 1
ad942d1a-15ab-4a0d-83a8-ae82183ece53 1
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b 1
60c8f748-e29d-4fce-9e66-584117ca2baf ALL
f9129295-bb08-4330-b60c-9f0beadda521 11
f9129295-bb08-4330-b60c-9f0beadda521 17
423a069b-27b8-44ed-9ef3-ca3cf9470970 1
f9129295-bb08-4330-b60c-9f0beadda521 29
3dc15e4b-b60d-4c49-aae8-97cf9664af51 1
f9129295-bb08-4330-b60c-9f0beadda521 20
f9129295-bb08-4330-b60c-9f0beadda521 7
173e2b27-8bc6-44d1-b581-a1913d6b1894 1
aabe992c-cfad-4049-b5df-36c41f900a67 1
ca35e88d-d191-4722-b90c-92f4a249869b 1
74abffac-6542-4eff-8eae-cc85463a5d02 ALL
50409b57-b000-43d5-9358-44c3081c4132 1
50409b57-b000-43d5-9358-44c3081c4132 ALL
7412074f-0f3a-4724-b035-7fb4db3174c8 18
173e2b27-8bc6-44d1-b581-a1913d6b1894 5
f9129295-bb08-4330-b60c-9f0beadda521 4
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 5
adc6fb62-09e7-44fd-a619-f787ecfd140b 1
457bce7b-9300-4c10-9a97-070b3c0d081d 5
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b ALL
9d39683a-47b3-4a18-942d-f1d741a47e8c 1
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab 1
7412074f-0f3a-4724-b035-7fb4db3174c8 ALL
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4 1
f9129295-bb08-4330-b60c-9f0beadda521 35
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 10
8fa00df1-38eb-426f-81a6-1185983e14cb ALL
f9129295-bb08-4330-b60c-9f0beadda521 5
6276b87c-ebb2-11ed-a05b-0242ac120003 1
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb 1
173e2b27-8bc6-44d1-b581-a1913d6b1894 11
478cd985-f4fc-45b4-ac71-bf78cf11e07b ALL
bfcbb283-4e53-41fd-9b31-aa818f7f23ce 9
173e2b27-8bc6-44d1-b581-a1913d6b1894 8
f9129295-bb08-4330-b60c-9f0beadda521 39
f9129295-bb08-4330-b60c-9f0beadda521 43
60c8f748-e29d-4fce-9e66-584117ca2baf 4
60c8f748-e29d-4fce-9e66-584117ca2baf 1
f9129295-bb08-4330-b60c-9f0beadda521 15
0.638228483593443 1.3326538805840833



LSTM
f9129295-bb08-4330-b60c-9f0beadda521 32
60ca8452-5b14-481f-a637-8756f527aee8 10
775dcad4-0733-4c22-8dbd-cd3ce344e891 ALL
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 6
ca35e88d-d191-4722-b90c-92f4a249869b 7
f9129295-bb08-4330-b60c-9f0beadda521 8
775dcad4-0733-4c22-8dbd-cd3ce344e891 2
9d1296ca-9e4f-4840-b7b5-e12172acab78 1
9d1296ca-9e4f-4840-b7b5-e12172acab78 ALL
173e2b27-8bc6-44d1-b581-a1913d6b1894 9
f9129295-bb08-4330-b60c-9f0beadda521 34
f9129295-bb08-4330-b60c-9f0beadda521 6
6276b87c-ebb2-11ed-a05b-0242ac120003 8
74abffac-6542-4eff-8eae-cc85463a5d02 1
f9129295-bb08-4330-b60c-9f0beadda521 33
92f116fe-5818-41db-9eb5-87445ad3818e ALL
f9129295-bb08-4330-b60c-9f0beadda521 10
e2de40dd-743b-4105-9077-3f343fea980d ALL
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b 1
6276b87c-ebb2-11ed-a05b-0242ac120003 6
92f116fe-5818-41db-9eb5-87445ad3818e 2
7412074f-0f3a-4724-b035-7fb4db3174c8 1
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 ALL
d639773a-df2c-421e-ac87-6918a754572f ALL
8fa00df1-38eb-426f-81a6-1185983e14cb 1
6276b87c-ebb2-11ed-a05b-0242ac120003 9
478cd985-f4fc-45b4-ac71-bf78cf11e07b 4
478cd985-f4fc-45b4-ac71-bf78cf11e07b 1
2058f680-aace-4b31-aed4-f34397b75096 ALL
60ca8452-5b14-481f-a637-8756f527aee8 1
60ca8452-5b14-481f-a637-8756f527aee8 ALL
478cd985-f4fc-45b4-ac71-bf78cf11e07b 5
0661e926-f219-456e-bde5-612fee6f891c 1
775dcad4-0733-4c22-8dbd-cd3ce344e891 1
0661e926-f219-456e-bde5-612fee6f891c ALL
7412074f-0f3a-4724-b035-7fb4db3174c8 11
9d1296ca-9e4f-4840-b7b5-e12172acab78 4
7412074f-0f3a-4724-b035-7fb4db3174c8 17
7412074f-0f3a-4724-b035-7fb4db3174c8 8
f9129295-bb08-4330-b60c-9f0beadda521 21
457bce7b-9300-4c10-9a97-070b3c0d081d ALL
f9129295-bb08-4330-b60c-9f0beadda521 42
f9129295-bb08-4330-b60c-9f0beadda521 18
aabe992c-cfad-4049-b5df-36c41f900a67 2
f9129295-bb08-4330-b60c-9f0beadda521 38
173e2b27-8bc6-44d1-b581-a1913d6b1894 16
f9129295-bb08-4330-b60c-9f0beadda521 19
9d1296ca-9e4f-4840-b7b5-e12172acab78 5
f9129295-bb08-4330-b60c-9f0beadda521 ALL
0ad2f65b-ee0e-4d50-93e2-84b76282325f ALL
e2de40dd-743b-4105-9077-3f343fea980d 1
b009c05b-326e-4ebe-988c-8d2229ec3a4c ALL
f9129295-bb08-4330-b60c-9f0beadda521 2
478cd985-f4fc-45b4-ac71-bf78cf11e07b 6
7db6eaca-fe22-41d7-bfb8-1fdde880feb8 ALL
0ad2f65b-ee0e-4d50-93e2-84b76282325f 2
f9129295-bb08-4330-b60c-9f0beadda521 31
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab 2
7db6eaca-fe22-41d7-bfb8-1fdde880feb8 2
f9129295-bb08-4330-b60c-9f0beadda521 16
d639773a-df2c-421e-ac87-6918a754572f 14
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 1
d639773a-df2c-421e-ac87-6918a754572f 1
f9129295-bb08-4330-b60c-9f0beadda521 27
bfcbb283-4e53-41fd-9b31-aa818f7f23ce ALL
ad942d1a-15ab-4a0d-83a8-ae82183ece53 ALL
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 3
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 5
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b ALL
2058f680-aace-4b31-aed4-f34397b75096 1
457bce7b-9300-4c10-9a97-070b3c0d081d 3
f9129295-bb08-4330-b60c-9f0beadda521 24
ad942d1a-15ab-4a0d-83a8-ae82183ece53 2
173e2b27-8bc6-44d1-b581-a1913d6b1894 18
423a069b-27b8-44ed-9ef3-ca3cf9470970 ALL
f9129295-bb08-4330-b60c-9f0beadda521 3
7412074f-0f3a-4724-b035-7fb4db3174c8 15
3dc15e4b-b60d-4c49-aae8-97cf9664af51 ALL
173e2b27-8bc6-44d1-b581-a1913d6b1894 14
9d1296ca-9e4f-4840-b7b5-e12172acab78 9
423a069b-27b8-44ed-9ef3-ca3cf9470970 2
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 1
3dc15e4b-b60d-4c49-aae8-97cf9664af51 2
457bce7b-9300-4c10-9a97-070b3c0d081d 1
173e2b27-8bc6-44d1-b581-a1913d6b1894 ALL
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 ALL
aabe992c-cfad-4049-b5df-36c41f900a67 ALL
ca35e88d-d191-4722-b90c-92f4a249869b ALL
f9129295-bb08-4330-b60c-9f0beadda521 25
6276b87c-ebb2-11ed-a05b-0242ac120003 3
74abffac-6542-4eff-8eae-cc85463a5d02 2
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 6
f9129295-bb08-4330-b60c-9f0beadda521 1
0ad2f65b-ee0e-4d50-93e2-84b76282325f 1
b009c05b-326e-4ebe-988c-8d2229ec3a4c 1
adc6fb62-09e7-44fd-a619-f787ecfd140b ALL
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b 3
f9129295-bb08-4330-b60c-9f0beadda521 22
7db6eaca-fe22-41d7-bfb8-1fdde880feb8 1
adc6fb62-09e7-44fd-a619-f787ecfd140b 2
f9129295-bb08-4330-b60c-9f0beadda521 26
9d39683a-47b3-4a18-942d-f1d741a47e8c ALL
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab ALL
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 9
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4 ALL
92f116fe-5818-41db-9eb5-87445ad3818e 5
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb ALL
6276b87c-ebb2-11ed-a05b-0242ac120003 ALL
ca35e88d-d191-4722-b90c-92f4a249869b 12
60ca8452-5b14-481f-a637-8756f527aee8 6
7412074f-0f3a-4724-b035-7fb4db3174c8 16
478cd985-f4fc-45b4-ac71-bf78cf11e07b 2
f9129295-bb08-4330-b60c-9f0beadda521 36
bfcbb283-4e53-41fd-9b31-aa818f7f23ce 1
ad942d1a-15ab-4a0d-83a8-ae82183ece53 1
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b 1
60c8f748-e29d-4fce-9e66-584117ca2baf ALL
f9129295-bb08-4330-b60c-9f0beadda521 11
f9129295-bb08-4330-b60c-9f0beadda521 17
423a069b-27b8-44ed-9ef3-ca3cf9470970 1
f9129295-bb08-4330-b60c-9f0beadda521 29
3dc15e4b-b60d-4c49-aae8-97cf9664af51 1
f9129295-bb08-4330-b60c-9f0beadda521 20
f9129295-bb08-4330-b60c-9f0beadda521 7
173e2b27-8bc6-44d1-b581-a1913d6b1894 1
aabe992c-cfad-4049-b5df-36c41f900a67 1
ca35e88d-d191-4722-b90c-92f4a249869b 1
74abffac-6542-4eff-8eae-cc85463a5d02 ALL
50409b57-b000-43d5-9358-44c3081c4132 1
50409b57-b000-43d5-9358-44c3081c4132 ALL
7412074f-0f3a-4724-b035-7fb4db3174c8 18
173e2b27-8bc6-44d1-b581-a1913d6b1894 5
f9129295-bb08-4330-b60c-9f0beadda521 4
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 5
adc6fb62-09e7-44fd-a619-f787ecfd140b 1
457bce7b-9300-4c10-9a97-070b3c0d081d 5
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b ALL
9d39683a-47b3-4a18-942d-f1d741a47e8c 1
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab 1
7412074f-0f3a-4724-b035-7fb4db3174c8 ALL
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4 1
f9129295-bb08-4330-b60c-9f0beadda521 35
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 10
8fa00df1-38eb-426f-81a6-1185983e14cb ALL
f9129295-bb08-4330-b60c-9f0beadda521 5
6276b87c-ebb2-11ed-a05b-0242ac120003 1
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb 1
173e2b27-8bc6-44d1-b581-a1913d6b1894 11
478cd985-f4fc-45b4-ac71-bf78cf11e07b ALL
bfcbb283-4e53-41fd-9b31-aa818f7f23ce 9
173e2b27-8bc6-44d1-b581-a1913d6b1894 8
f9129295-bb08-4330-b60c-9f0beadda521 39
f9129295-bb08-4330-b60c-9f0beadda521 43
60c8f748-e29d-4fce-9e66-584117ca2baf 4
60c8f748-e29d-4fce-9e66-584117ca2baf 1
f9129295-bb08-4330-b60c-9f0beadda521 15
0.6095422158598462 1.3673718427337063



TBATS
f9129295-bb08-4330-b60c-9f0beadda521 32
60ca8452-5b14-481f-a637-8756f527aee8 10
775dcad4-0733-4c22-8dbd-cd3ce344e891 ALL
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 6
ca35e88d-d191-4722-b90c-92f4a249869b 7
f9129295-bb08-4330-b60c-9f0beadda521 8
775dcad4-0733-4c22-8dbd-cd3ce344e891 2
9d1296ca-9e4f-4840-b7b5-e12172acab78 1
9d1296ca-9e4f-4840-b7b5-e12172acab78 ALL
173e2b27-8bc6-44d1-b581-a1913d6b1894 9
f9129295-bb08-4330-b60c-9f0beadda521 34
f9129295-bb08-4330-b60c-9f0beadda521 6
6276b87c-ebb2-11ed-a05b-0242ac120003 8
74abffac-6542-4eff-8eae-cc85463a5d02 1
f9129295-bb08-4330-b60c-9f0beadda521 33
92f116fe-5818-41db-9eb5-87445ad3818e ALL
f9129295-bb08-4330-b60c-9f0beadda521 10
e2de40dd-743b-4105-9077-3f343fea980d ALL
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b 1
6276b87c-ebb2-11ed-a05b-0242ac120003 6
92f116fe-5818-41db-9eb5-87445ad3818e 2
7412074f-0f3a-4724-b035-7fb4db3174c8 1
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 ALL
d639773a-df2c-421e-ac87-6918a754572f ALL
8fa00df1-38eb-426f-81a6-1185983e14cb 1
6276b87c-ebb2-11ed-a05b-0242ac120003 9
478cd985-f4fc-45b4-ac71-bf78cf11e07b 4
478cd985-f4fc-45b4-ac71-bf78cf11e07b 1
2058f680-aace-4b31-aed4-f34397b75096 ALL
60ca8452-5b14-481f-a637-8756f527aee8 1
60ca8452-5b14-481f-a637-8756f527aee8 ALL
478cd985-f4fc-45b4-ac71-bf78cf11e07b 5
0661e926-f219-456e-bde5-612fee6f891c 1
775dcad4-0733-4c22-8dbd-cd3ce344e891 1
0661e926-f219-456e-bde5-612fee6f891c ALL
7412074f-0f3a-4724-b035-7fb4db3174c8 11
9d1296ca-9e4f-4840-b7b5-e12172acab78 4
7412074f-0f3a-4724-b035-7fb4db3174c8 17
7412074f-0f3a-4724-b035-7fb4db3174c8 8
f9129295-bb08-4330-b60c-9f0beadda521 21
457bce7b-9300-4c10-9a97-070b3c0d081d ALL
f9129295-bb08-4330-b60c-9f0beadda521 42
f9129295-bb08-4330-b60c-9f0beadda521 18
aabe992c-cfad-4049-b5df-36c41f900a67 2
f9129295-bb08-4330-b60c-9f0beadda521 38
173e2b27-8bc6-44d1-b581-a1913d6b1894 16
f9129295-bb08-4330-b60c-9f0beadda521 19
9d1296ca-9e4f-4840-b7b5-e12172acab78 5
f9129295-bb08-4330-b60c-9f0beadda521 ALL
0ad2f65b-ee0e-4d50-93e2-84b76282325f ALL
e2de40dd-743b-4105-9077-3f343fea980d 1
b009c05b-326e-4ebe-988c-8d2229ec3a4c ALL
f9129295-bb08-4330-b60c-9f0beadda521 2
478cd985-f4fc-45b4-ac71-bf78cf11e07b 6
7db6eaca-fe22-41d7-bfb8-1fdde880feb8 ALL
0ad2f65b-ee0e-4d50-93e2-84b76282325f 2
f9129295-bb08-4330-b60c-9f0beadda521 31
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab 2
7db6eaca-fe22-41d7-bfb8-1fdde880feb8 2
f9129295-bb08-4330-b60c-9f0beadda521 16
d639773a-df2c-421e-ac87-6918a754572f 14
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 1
d639773a-df2c-421e-ac87-6918a754572f 1
f9129295-bb08-4330-b60c-9f0beadda521 27
bfcbb283-4e53-41fd-9b31-aa818f7f23ce ALL
ad942d1a-15ab-4a0d-83a8-ae82183ece53 ALL
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 3
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 5
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b ALL
2058f680-aace-4b31-aed4-f34397b75096 1
457bce7b-9300-4c10-9a97-070b3c0d081d 3
f9129295-bb08-4330-b60c-9f0beadda521 24
ad942d1a-15ab-4a0d-83a8-ae82183ece53 2
173e2b27-8bc6-44d1-b581-a1913d6b1894 18
423a069b-27b8-44ed-9ef3-ca3cf9470970 ALL
f9129295-bb08-4330-b60c-9f0beadda521 3
7412074f-0f3a-4724-b035-7fb4db3174c8 15
3dc15e4b-b60d-4c49-aae8-97cf9664af51 ALL
173e2b27-8bc6-44d1-b581-a1913d6b1894 14
9d1296ca-9e4f-4840-b7b5-e12172acab78 9
423a069b-27b8-44ed-9ef3-ca3cf9470970 2
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 1
3dc15e4b-b60d-4c49-aae8-97cf9664af51 2
457bce7b-9300-4c10-9a97-070b3c0d081d 1
173e2b27-8bc6-44d1-b581-a1913d6b1894 ALL
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 ALL
aabe992c-cfad-4049-b5df-36c41f900a67 ALL
ca35e88d-d191-4722-b90c-92f4a249869b ALL
f9129295-bb08-4330-b60c-9f0beadda521 25
6276b87c-ebb2-11ed-a05b-0242ac120003 3
74abffac-6542-4eff-8eae-cc85463a5d02 2
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 6
f9129295-bb08-4330-b60c-9f0beadda521 1
0ad2f65b-ee0e-4d50-93e2-84b76282325f 1
b009c05b-326e-4ebe-988c-8d2229ec3a4c 1
adc6fb62-09e7-44fd-a619-f787ecfd140b ALL
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b 3
f9129295-bb08-4330-b60c-9f0beadda521 22
7db6eaca-fe22-41d7-bfb8-1fdde880feb8 1
adc6fb62-09e7-44fd-a619-f787ecfd140b 2
f9129295-bb08-4330-b60c-9f0beadda521 26
9d39683a-47b3-4a18-942d-f1d741a47e8c ALL
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab ALL
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 9
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4 ALL
92f116fe-5818-41db-9eb5-87445ad3818e 5
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb ALL
6276b87c-ebb2-11ed-a05b-0242ac120003 ALL
ca35e88d-d191-4722-b90c-92f4a249869b 12
60ca8452-5b14-481f-a637-8756f527aee8 6
7412074f-0f3a-4724-b035-7fb4db3174c8 16
478cd985-f4fc-45b4-ac71-bf78cf11e07b 2
f9129295-bb08-4330-b60c-9f0beadda521 36
bfcbb283-4e53-41fd-9b31-aa818f7f23ce 1
ad942d1a-15ab-4a0d-83a8-ae82183ece53 1
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b 1
60c8f748-e29d-4fce-9e66-584117ca2baf ALL
f9129295-bb08-4330-b60c-9f0beadda521 11
f9129295-bb08-4330-b60c-9f0beadda521 17
423a069b-27b8-44ed-9ef3-ca3cf9470970 1
f9129295-bb08-4330-b60c-9f0beadda521 29
3dc15e4b-b60d-4c49-aae8-97cf9664af51 1
f9129295-bb08-4330-b60c-9f0beadda521 20
f9129295-bb08-4330-b60c-9f0beadda521 7
173e2b27-8bc6-44d1-b581-a1913d6b1894 1
aabe992c-cfad-4049-b5df-36c41f900a67 1
ca35e88d-d191-4722-b90c-92f4a249869b 1
74abffac-6542-4eff-8eae-cc85463a5d02 ALL
50409b57-b000-43d5-9358-44c3081c4132 1
50409b57-b000-43d5-9358-44c3081c4132 ALL
7412074f-0f3a-4724-b035-7fb4db3174c8 18
173e2b27-8bc6-44d1-b581-a1913d6b1894 5
f9129295-bb08-4330-b60c-9f0beadda521 4
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 5
adc6fb62-09e7-44fd-a619-f787ecfd140b 1
457bce7b-9300-4c10-9a97-070b3c0d081d 5
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b ALL
9d39683a-47b3-4a18-942d-f1d741a47e8c 1
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab 1
7412074f-0f3a-4724-b035-7fb4db3174c8 ALL
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4 1
f9129295-bb08-4330-b60c-9f0beadda521 35
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 10
8fa00df1-38eb-426f-81a6-1185983e14cb ALL
f9129295-bb08-4330-b60c-9f0beadda521 5
6276b87c-ebb2-11ed-a05b-0242ac120003 1
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb 1
173e2b27-8bc6-44d1-b581-a1913d6b1894 11
478cd985-f4fc-45b4-ac71-bf78cf11e07b ALL
bfcbb283-4e53-41fd-9b31-aa818f7f23ce 9
173e2b27-8bc6-44d1-b581-a1913d6b1894 8
f9129295-bb08-4330-b60c-9f0beadda521 39
f9129295-bb08-4330-b60c-9f0beadda521 43
60c8f748-e29d-4fce-9e66-584117ca2baf 4
60c8f748-e29d-4fce-9e66-584117ca2baf 1
f9129295-bb08-4330-b60c-9f0beadda521 15
0.6902190187404204 1.3854279165077013



Ensemble
f9129295-bb08-4330-b60c-9f0beadda521 32
60ca8452-5b14-481f-a637-8756f527aee8 10
775dcad4-0733-4c22-8dbd-cd3ce344e891 ALL
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 6
ca35e88d-d191-4722-b90c-92f4a249869b 7
f9129295-bb08-4330-b60c-9f0beadda521 8
775dcad4-0733-4c22-8dbd-cd3ce344e891 2
9d1296ca-9e4f-4840-b7b5-e12172acab78 1
9d1296ca-9e4f-4840-b7b5-e12172acab78 ALL
173e2b27-8bc6-44d1-b581-a1913d6b1894 9
f9129295-bb08-4330-b60c-9f0beadda521 34
f9129295-bb08-4330-b60c-9f0beadda521 6
6276b87c-ebb2-11ed-a05b-0242ac120003 8
74abffac-6542-4eff-8eae-cc85463a5d02 1
f9129295-bb08-4330-b60c-9f0beadda521 33
92f116fe-5818-41db-9eb5-87445ad3818e ALL
f9129295-bb08-4330-b60c-9f0beadda521 10
e2de40dd-743b-4105-9077-3f343fea980d ALL
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b 1
6276b87c-ebb2-11ed-a05b-0242ac120003 6
92f116fe-5818-41db-9eb5-87445ad3818e 2
7412074f-0f3a-4724-b035-7fb4db3174c8 1
22fde42e-45d7-46cd-9d6f-3a4dbabbc579 ALL
d639773a-df2c-421e-ac87-6918a754572f ALL
8fa00df1-38eb-426f-81a6-1185983e14cb 1
6276b87c-ebb2-11ed-a05b-0242ac120003 9
478cd985-f4fc-45b4-ac71-bf78cf11e07b 4
478cd985-f4fc-45b4-ac71-bf78cf11e07b 1
2058f680-aace-4b31-aed4-f34397b75096 ALL
60ca8452-5b14-481f-a637-8756f527aee8 1
60ca8452-5b14-481f-a637-8756f527aee8 ALL

In [26]:
scores11

{'GradientBoosting': np.float64(0.638228483593443),
 'LSTM': np.float64(0.6095422158598462),
 'TBATS': np.float64(0.6902190187404204),
 'Ensemble': np.float64(0.6324611185319894),
 'Chronos': np.float64(0.6794345245122004)}

In [27]:
scores12

{'GradientBoosting': np.float64(1.3326538805840833),
 'LSTM': np.float64(1.3673718427337063),
 'TBATS': np.float64(1.3854279165077013),
 'Ensemble': np.float64(1.3135520820594917),
 'Chronos': np.float64(1.3637737101410874)}

In [28]:
joblib.dump(pd.DataFrame(scores11, columns=['weights']), 'scores11.pkl')
joblib.dump(pd.DataFrame(scores12, columns=['weights']), 'scores12.pkl');

In [29]:
scores12

{'GradientBoosting': np.float64(1.3326538805840833),
 'LSTM': np.float64(1.3673718427337063),
 'TBATS': np.float64(1.3854279165077013),
 'Ensemble': np.float64(1.3135520820594917),
 'Chronos': np.float64(1.3637737101410874)}

In [42]:
scores11 = joblib.load('scores11.pkl')
scores12 = joblib.load('scores12.pkl')
scores21 = joblib.load('scores21.pkl')
scores22 = joblib.load('scores22.pkl')

In [32]:
scores1 = pd.concat([scores11, scores21], axis=0)
joblib.dump(scores1, 'scores1.pkl')
scores1.to_csv('scores1.csv', sep=';', encoding='latin1', index=True)

scores1

/var/folders/k1/3tn1t6gd2hn967rvpqnz2k8m0000gp/T/ipykernel_82404/710657758.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  scores1 = pd.concat([scores11, scores21], axis=0)

                                                     weights
amazon/chronos-bolt-base:v2025-03-09:cl(370):q(...  0.438251
MEDIAN_MAD_60                                       0.645104

In [33]:
scores2 = pd.concat([scores12, scores22], axis=0).sort_values('weights', ascending=False)
joblib.dump(scores2, 'scores2.pkl')
scores2.to_csv('scores2.csv', sep=';', encoding='latin1', index=True)

scores2

/var/folders/k1/3tn1t6gd2hn967rvpqnz2k8m0000gp/T/ipykernel_82404/562971219.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  scores2 = pd.concat([scores12, scores22], axis=0).sort_values('weights', ascending=False)

                                                     weights
amazon/chronos-bolt-base:v2025-03-09:cl(370):q(...  1.472819
MEDIAN_MAD_60                                       1.289020

In [34]:
scores1.to_csv('scores1_overall.csv', sep=';', encoding='latin1', index=True)
scores2.to_csv('scores2_overall.csv', sep=';', encoding='latin1', index=True)

In [35]:
df11 = pd.DataFrame(df_forecast_metrics1_norm)
joblib.dump(df11, 'df_scores11.pkl')

df11

,GradientBoosting,LSTM,TBATS,Ensemble,Chronos
f9129295-bb08-4330-b60c-9f0beadda521,"{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10..."
60ca8452-5b14-481f-a637-8756f527aee8,"{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}"
775dcad4-0733-4c22-8dbd-cd3ce344e891,"{'ALL': 0.33556436846803506, 2: 0.629455854981...","{'ALL': 0.7348391676372723, 2: 0.4129745846807...","{'ALL': 0.32197191149112003, 2: 0.321198867643...","{'ALL': 0.5033465527020526, 2: 0.3362415513946...","{'ALL': 0.5365594604731142, 2: 0.5256906085751..."
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6,"{6: 0.14205120538873522, 3: 0.1957322293222127...","{6: 0.15189793773911958, 3: 0.2077912012187713...","{6: 0.1573731734328607, 3: 0.21148822909678192...","{6: 0.14205120538873522, 3: 0.1957322284375925...","{6: 0.144343256721419, 3: 0.19096455635730825,..."
ca35e88d-d191-4722-b90c-92f4a249869b,"{7: 0.0, 'ALL': 0.7842858343015582, 12: 0.0, 1...","{7: 0.0, 'ALL': 0.5171981435994957, 12: 0.0, 1...","{7: 0.0, 'ALL': 0.8052413948701183, 12: 0.0, 1...","{7: 0.0, 'ALL': 0.47486362649823854, 12: 0.0, ...","{7: 0.0, 'ALL': 0.6123338761715464, 12: 0.0, 1..."
9d1296ca-9e4f-4840-b7b5-e12172acab78,"{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}"
173e2b27-8bc6-44d1-b581-a1913d6b1894,"{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.2...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.3...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.2...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.4...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.3..."
6276b87c-ebb2-11ed-a05b-0242ac120003,"{8: 0.18326106533246228, 6: 0.0, 9: 0.15578382...","{8: 0.22696885595503102, 6: 0.0, 9: 0.12257260...","{8: 0.3487791709164587, 6: 0.0, 9: 0.184552312...","{8: 0.19581169661613199, 6: 0.0, 9: 0.19894295...","{8: 0.28654914517245184, 6: 0.0, 9: 0.26342971..."
74abffac-6542-4eff-8eae-cc85463a5d02,"{1: 0.42691774830664275, 2: 0.0, 'ALL': 0.4268...","{1: 0.25171724264465, 2: 0.0, 'ALL': 0.2516622...","{1: 0.361879115767993, 2: 0.0, 'ALL': 0.361172...","{1: 0.33008308864706254, 2: 0.0, 'ALL': 0.4268...","{1: 0.38885693337925126, 2: 0.0, 'ALL': 0.3878..."
92f116fe-5818-41db-9eb5-87445ad3818e,"{'ALL': 0.5687349620042466, 2: 0.0, 5: 0.37920...","{'ALL': 0.41483250622501744, 2: 0.0, 5: 0.4148...","{'ALL': 0.717576456100309, 2: 0.0, 5: 0.717390...","{'ALL': 0.3791566413361644, 2: 0.0, 5: 0.11718...","{'ALL': 0.5522120082303189, 2: 0.0, 5: 0.28910..."
e2de40dd-743b-4105-9077-3f343fea980d,"{'ALL': 0.3178137169897532, 1: 0.3178137169897...","{'ALL': 0.30422330765104505, 1: 0.304223307649...","{'ALL': 0.3143438532525315, 1: 0.3143438532525...","{'ALL': 0.27910490949249983, 1: 0.279104909492...","{'ALL': 0.4361808056018588, 1: 0.43955012930169}"
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b,"{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}"
7412074f-0f3a-4724-b035-7fb4db3174c8,"{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16..."
22fde42e-45d7-46cd-9d6f-3a4dbabbc579,"{'ALL': 0.8513695392006424, 1: 0.0, 5: 0.0, 6:...","{'ALL': 0.9278731650522143, 1: 0.0, 5: 0.0, 6:...","{'ALL': 1.4550731765156883, 1: 0.0, 5: 0.0, 6:...","{'ALL': 1.6008849858280871, 1: 0.0, 5: 0.0, 6:...","{'ALL': 1.1150348133262886, 1: 0.0, 5: 0.0, 6:..."
d639773a-df2c-421e-ac87-6918a754572f,"{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}"
8fa00df1-38eb-426f-81a6-1185983e14cb,"{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}"
478cd985-f4fc-45b4-ac71-bf78cf11e07b,"{4: 0.0, 1: 0.6698111844586713, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 0.7836775795970184, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 0.6351694588966396, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 0.6698111844586713, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 1.3333333333333333, 5: 0.0, 6: 0.0..."
2058f680-aace-4b31-aed4-f34397b75096,"{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}"
0661e926-f219-456e-bde5-612fee6f891c,"{1: 0.5097794107374761, 'ALL': 0.5097794107374...","{1: 0.5098890573973827, 'ALL': 0.5098890575889...","{1: 0.40382837513277886, 'ALL': 0.403828375132...","{1: 0.5097793943287842, 'ALL': 0.5097793943287...","{1: 0.5226197237158193, 'ALL': 0.5523754794596..."
457bce7b-9300-4c10-9a97-070b3c0d081d,"{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}"
aabe992c-cfad-4049-b5df-36c41f900a67,"{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}"
0ad2f65b-ee0e-4d50-93e2-84b76282325f,"{'ALL': 0.4500724264082394, 2: 0.0, 1: 0.31166...","{'ALL': 0.3502143586396694, 2: 0.0, 1: 0.33212...","{'ALL': 0.5726461890753668, 2: 0.0, 1: 0.57290...","{'ALL': 0.3291705278506425, 2: 0.0, 1: 0.32914...","{'ALL': 0.48700646804676906, 2: 0.0, 1: 0.5104..."
b009c05b-326e-4ebe-988c-8d2229ec3a4c,"{'ALL': 0.387508786865684, 1: 0.387508786865684}","{'ALL': 0.42372148538946264, 1: 0.423721584609...","{'ALL': 0.7129576343168427, 1: 0.7129576343168...","{'ALL': 0.387508786865684, 1: 0.387508786865684}","{'ALL': 0.5441240628780987, 1: 0.5375092855577..."
7db6eaca-fe22-41d7-bfb8-1fdde880feb8,"{'ALL': 0.1981336514628741, 2: 0.0, 1: 0.41554...","{'ALL': 0.21664103165800327, 2: 0.0, 1: 0.2120...","{'ALL': 0.3630849992621983, 2: 0.0, 1: 0.38111...","{'ALL': 0.17190159000485689, 2: 0.0, 1: 0.4014...","{'ALL': 0.45834107275909897, 2: 0.0, 1: 0.4733..."
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab,"{2: 0.04769477177005012, 'ALL': 0.117970916499...","{2: 0.0, 'ALL': 0.02001573947091513, 1: 0.0154...","{2: 0.04561887008802765, 'ALL': 0.121719198303...","{2: 0.0056468272883189565, 'ALL': 0.0193017708...","{2: 0.12752287009754845, 'ALL': 0.191257620920..."
bfcbb283-4e53-41fd-9b31-aa818f7f23ce,"{'ALL': 1.4555528938839275, 1: 0.0, 9: 0.0}","{'ALL': 1.5963177827985084, 1: 0.0, 9: 0.0}","{'ALL': 1.3807795251563477, 1: 0.0, 9: 0.0}","{'ALL': 1.4555528938839275, 1: 0.0, 9: 0.0}","{'ALL': 1.1234698572921173, 1: 0.0, 9: 0.0}"
ad942d1a-15ab-4a0d-83a8-ae82183ece53,"{'ALL': 0.5437368101665412, 2: 0.3548289091636...","{'ALL': 0.32096663410526804, 2: 0.418500519723...","{'ALL': 0.6201535515068005, 2: 0.3806639655404...","{'ALL': 0.5437368101733495, 2: 0.3548289091601...","{'ALL': 0.4698044626625527, 2: 0.2950462106051..."
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b,"{'ALL': 0.3403376387560597, 3: 0.0, 1: 0.34033...","{'ALL': 0.6937692093689474, 3: 0.0, 1: 0.37260...","{'ALL': 0.46307590367896684, 3: 0.0, 1: 0.4630...","{'ALL': 0.3403376387560597, 3: 0.0, 1: 0.34033...","{'ALL': 0.521094816459011, 3: 0.0, 1: 0.501747..."
423a069b-27b8-44ed-9ef3-ca3cf9470970,"{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}"
3dc15e4b-b60d-4c49-aae8-97cf9664af51,"{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}"
adc6fb62-09e7-44fd-a619-f787ecfd140b,"{'ALL': 0.6158498427135128, 2: 0.1876382703409...","{'ALL': 0.3606344890622168, 2: 0.1392852115446...","{'ALL': 0.3200285450025746, 2: 0.2426070017955...","{'ALL': 0.6158498427135128, 2: 0.2403094830116...","{'ALL': 0.4524784086819223, 2: 0.3133403524970..."
9d39683a-47b3-4a18-942d-f1d741a47e8c,"{'ALL': 0.3267742056993122, 1: 0.3267742056993...","{'ALL': 0.3457906387165968, 1: 0.3457906378285...","{'ALL': 0.3662783885695453, 1: 0.3662783885695...","{'ALL': 0.3267742056993122, 1: 0.3267742056993...","{'ALL': 0.32790934476434674, 1: 0.324759448561..."
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4,"{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}"
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb,"{'ALL': 0.49709520321481726, 1: 0.497095203214...","{'ALL': 0.29067579393589826, 1: 0.281058133187...","{'ALL': 0.5112335610713565, 1: 0.5112335610713...","{'ALL': 0.2856974441168944, 1: 0.2856974441168...","{'ALL': 0.4188457525647677, 1: 0.4093168468168..."
60c8f748-e29d-4fce-9e66-584117ca2baf,"{'ALL': 0.41316448091651925, 4: 0.0, 1: 0.4477...","{'ALL': 0.24135042205758123, 4: 0.0, 1: 0.2413...","{'ALL': 0.4505104288184157, 4: 0.0, 1: 0.45051...","{'ALL': 0.41316448091651925, 4: 0.0, 1: 0.4477...","{'ALL': 0.4051214119299109, 4: 0.0, 1: 0.38675..."
50409b57-b000-43d5-9358-44c3081c4132,"{1: 0.7938578863328096, 'ALL': 0.7938578863328...","{1: 0.8178806913624911, 'ALL': 0.8178806913624...","{1: 0.666739266680707, 'ALL': 0.666739266680707}","{1: 0.7938578124623552, 'ALL': 0.7938578124623...","{1: 0.5103879556754432, 'ALL': 0.5271321236933..."

In [36]:
df12 = pd.DataFrame(df_forecast_metrics2_norm)
joblib.dump(df12, 'df_scores12.pkl')

df12

,GradientBoosting,LSTM,TBATS,Ensemble,Chronos
f9129295-bb08-4330-b60c-9f0beadda521,"{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10..."
60ca8452-5b14-481f-a637-8756f527aee8,"{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}"
775dcad4-0733-4c22-8dbd-cd3ce344e891,"{'ALL': 1.1614784508165195, 2: 1.1633076055101...","{'ALL': 1.2544550119230111, 2: 1.2564723188462...","{'ALL': 1.11784757176871, 2: 1.115745022162797...","{'ALL': 1.1614784508165195, 2: 1.1633076957544...","{'ALL': 1.08108796822501, 2: 0.657113260718985..."
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6,"{6: 0.2687836755945146, 3: 0.3791340371395408,...","{6: 0.2840297365726457, 3: 0.39831999423898784...","{6: 0.28887472015507765, 3: 0.3998031356637399...","{6: 0.2687836755945146, 3: 0.37913403603376566...","{6: 0.27765032825534464, 3: 0.4106718769057024..."
ca35e88d-d191-4722-b90c-92f4a249869b,"{7: 0.0, 'ALL': 1.4628949108443339, 12: 0.0, 1...","{7: 0.0, 'ALL': 1.5809377284690926, 12: 0.0, 1...","{7: 0.0, 'ALL': 1.405972679101682, 12: 0.0, 1:...","{7: 0.0, 'ALL': 1.4628948479412456, 12: 0.0, 1...","{7: 0.0, 'ALL': 1.2801628784544734, 12: 0.0, 1..."
9d1296ca-9e4f-4840-b7b5-e12172acab78,"{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}"
173e2b27-8bc6-44d1-b581-a1913d6b1894,"{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.9...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.9...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.8...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.9...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.8..."
6276b87c-ebb2-11ed-a05b-0242ac120003,"{8: 0.6464121325862014, 6: 0.0, 9: 0.694655501...","{8: 0.6990106365337003, 6: 0.0, 9: 0.751080449...","{8: 0.6173376617776747, 6: 0.0, 9: 0.650031458...","{8: 0.6464121325862014, 6: 0.0, 9: 0.694655501...","{8: 0.5423233660326015, 6: 0.0, 9: 0.548432195..."
74abffac-6542-4eff-8eae-cc85463a5d02,"{1: 0.8799645234114103, 2: 0.0, 'ALL': 0.87984...","{1: 0.9374031652391575, 2: 0.0, 'ALL': 0.93726...","{1: 0.9405630602381798, 2: 0.0, 'ALL': 0.93931...","{1: 0.8799645172956823, 2: 0.0, 'ALL': 0.87984...","{1: 0.8644920553079056, 2: 0.0, 'ALL': 0.88037..."
92f116fe-5818-41db-9eb5-87445ad3818e,"{'ALL': 1.2836928467452888, 2: 0.0, 5: 1.28381...","{'ALL': 1.3873551053659365, 2: 0.0, 5: 1.38748...","{'ALL': 1.2182090765356826, 2: 0.0, 5: 1.21790...","{'ALL': 1.2836928467452888, 2: 0.0, 5: 0.86577...","{'ALL': 1.069847067375283, 2: 0.0, 5: 1.093341..."
e2de40dd-743b-4105-9077-3f343fea980d,"{'ALL': 0.9880783299606499, 1: 0.9880783299606...","{'ALL': 1.061643275406417, 1: 1.0616432753901404}","{'ALL': 0.9702833107933819, 1: 0.9702833107933...","{'ALL': 0.9880783299606499, 1: 0.9880783299606...","{'ALL': 0.8900056112766455, 1: 0.8903433791368..."
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b,"{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}"
7412074f-0f3a-4724-b035-7fb4db3174c8,"{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16..."
22fde42e-45d7-46cd-9d6f-3a4dbabbc579,"{'ALL': 2.8923324425097823, 1: 0.0, 5: 0.0, 6:...","{'ALL': 3.1211558171566844, 1: 0.0, 5: 0.0, 6:...","{'ALL': 2.510709584656852, 1: 0.0, 5: 0.0, 6: ...","{'ALL': 2.8923329258779815, 1: 0.0, 5: 0.0, 6:...","{'ALL': 1.3937935166578606, 1: 0.0, 5: 0.0, 6:..."
d639773a-df2c-421e-ac87-6918a754572f,"{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}"
8fa00df1-38eb-426f-81a6-1185983e14cb,"{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}"
478cd985-f4fc-45b4-ac71-bf78cf11e07b,"{4: 0.0, 1: 1.238696684724528, 5: 0.0, 6: 0.0,...","{4: 0.0, 1: 1.3388879677093661, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 1.1215817878002738, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 1.238696684724528, 5: 0.0, 6: 0.0,...","{4: 0.0, 1: 1.6666666666666665, 5: 0.0, 6: 0.0..."
2058f680-aace-4b31-aed4-f34397b75096,"{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}"
0661e926-f219-456e-bde5-612fee6f891c,"{1: 0.9469462634855225, 'ALL': 0.9469462634855...","{1: 1.0130325631496984, 'ALL': 1.013032565065393}","{1: 0.7858184083575777, 'ALL': 0.7858184083575...","{1: 0.9469462429746577, 'ALL': 0.9469462429746...","{1: 1.056538365959226, 'ALL': 1.0913607818329885}"
457bce7b-9300-4c10-9a97-070b3c0d081d,"{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}"
aabe992c-cfad-4049-b5df-36c41f900a67,"{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}"
0ad2f65b-ee0e-4d50-93e2-84b76282325f,"{'ALL': 1.041343146475989, 2: 0.0, 1: 1.041317...","{'ALL': 1.1238143559887415, 2: 0.0, 1: 1.12378...","{'ALL': 1.0120813085330855, 2: 0.0, 1: 1.01266...","{'ALL': 1.0413431464688145, 2: 0.0, 1: 1.04131...","{'ALL': 0.9269345902608628, 2: 0.0, 1: 0.94887..."
b009c05b-326e-4ebe-988c-8d2229ec3a4c,"{'ALL': 1.3022947663903435, 1: 1.3022947663903...","{'ALL': 1.40710057938879, 1: 1.407100827437873}","{'ALL': 1.2072129730516277, 1: 1.2072129730516...","{'ALL': 1.3022947663903435, 1: 1.3022947663903...","{'ALL': 1.0793117070004765, 1: 1.0715832237044..."
7db6eaca-fe22-41d7-bfb8-1fdde880feb8,"{'ALL': 1.3841491791846283, 2: 0.0, 1: 1.46163...","{'ALL': 1.4966282307197494, 2: 0.0, 1: 1.28305...","{'ALL': 1.27346556834477, 2: 0.0, 1: 1.3383750...","{'ALL': 0.8595079500242845, 2: 0.0, 1: 1.46163...","{'ALL': 0.5729263409488736, 2: 0.0, 1: 0.59166..."
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab,"{2: 0.2949421317334402, 'ALL': 0.8793811446872...","{2: 0.0, 'ALL': 0.40031478941830256, 1: 0.3087...","{2: 0.28282514775752726, 'ALL': 0.899506599461...","{2: 0.11293654576637914, 'ALL': 0.386035416252...","{2: 0.24279857096246882, 'ALL': 0.665473843727..."
bfcbb283-4e53-41fd-9b31-aa818f7f23ce,"{'ALL': 2.6189652224654374, 1: 0.0, 9: 0.0}","{'ALL': 2.8301028551409395, 1: 0.0, 9: 0.0}","{'ALL': 2.284620948318842, 1: 0.0, 9: 0.0}","{'ALL': 2.6189652224654374, 1: 0.0, 9: 0.0}","{'ALL': 2.3067300475297587, 1: 0.0, 9: 0.0}"
ad942d1a-15ab-4a0d-83a8-ae82183ece53,"{'ALL': 1.0838257658997361, 2: 0.6886914776015...","{'ALL': 1.1631188559239753, 2: 0.7424723936904...","{'ALL': 1.1183973298375205, 2: 0.6780825202687...","{'ALL': 1.08382576596782, 2: 0.688691477567132...","{'ALL': 1.0389243942325175, 2: 0.6334460310475..."
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b,"{'ALL': 1.2191424515144613, 3: 0.0, 1: 1.21914...","{'ALL': 1.3172518906895627, 3: 0.0, 1: 1.31725...","{'ALL': 0.9066914910305325, 3: 0.0, 1: 0.90669...","{'ALL': 1.2191424515144613, 3: 0.0, 1: 1.21914...","{'ALL': 0.896751454476378, 3: 0.0, 1: 0.871452..."
423a069b-27b8-44ed-9ef3-ca3cf9470970,"{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}"
3dc15e4b-b60d-4c49-aae8-97cf9664af51,"{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}"
adc6fb62-09e7-44fd-a619-f787ecfd140b,"{'ALL': 1.1462927640131022, 2: 0.8229591085896...","{'ALL': 1.2376331949840669, 2: 0.8894988684358...","{'ALL': 1.1088812331648867, 2: 0.7836616416434...","{'ALL': 1.1462927640131022, 2: 0.8229591909140...","{'ALL': 0.9777378196953058, 2: 0.6674421185302..."
9d39683a-47b3-4a18-942d-f1d741a47e8c,"{'ALL': 0.624000001471167, 1: 0.624000001471167}","{'ALL': 0.6536531710971303, 1: 0.6536531696626...","{'ALL': 0.678848535734115, 1: 0.678848535734115}","{'ALL': 0.624000001471167, 1: 0.624000001471167}","{'ALL': 0.6763001008491318, 1: 0.6765767564187..."
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4,"{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}"
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb,"{'ALL': 0.9464301259765222, 1: 0.9464301259765...","{'ALL': 1.0152193073017821, 1: 1.0152193073017...","{'ALL': 0.937621260577583, 1: 0.937621260577583}","{'ALL': 0.9464301259765222, 1: 0.9464301259765...","{'ALL': 0.8789431814639299, 1: 0.8695869455523..."
60c8f748-e29d-4fce-9e66-584117ca2baf,"{'ALL': 0.8192489152179053, 4: 0.0, 1: 0.81924...","{'ALL': 0.8714893257155459, 4: 0.0, 1: 0.87148...","{'ALL': 0.8205388504832023, 4: 0.0, 1: 0.82053...","{'ALL': 0.8192489152179053, 4: 0.0, 1: 0.81924...","{'ALL': 0.8327711092738616, 4: 0.0, 1: 0.81094..."
50409b57-b000-43d5-9358-44c3081c4132,"{1: 1.3486544157665221, 'ALL': 1.3486544157665...","{1: 1.4571144021869313, 'ALL': 1.4571144021869...","{1: 1.1551607151405554, 'ALL': 1.1551607151405...","{1: 1.3486543234284538, 'ALL': 1.3486543234284...","{1: 0.6379849445943039, 'ALL': 0.6589151546166..."

In [37]:
df_scores11 = joblib.load('df_scores11.pkl')
df_scores12 = joblib.load('df_scores12.pkl')
df_scores21 = joblib.load('df_scores21.pkl')
df_scores22 = joblib.load('df_scores22.pkl')

In [38]:
df_scores1 = df_scores11.merge(df_scores21, how='outer', left_index=True, right_index=True, sort=False)
joblib.dump(df_scores1, 'df_scores1.pkl')
df_scores1.to_csv('df_scores1.csv', sep=';', encoding='latin1', index=True)

df_scores1

,GradientBoosting,LSTM,TBATS,Ensemble,Chronos,"amazon/chronos-bolt-base:v2025-03-09:cl(370):q(0.3,0.7)",MEDIAN_MAD_60
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6,"{6: 0.14205120538873522, 3: 0.1957322293222127...","{6: 0.15189793773911958, 3: 0.2077912012187713...","{6: 0.1573731734328607, 3: 0.21148822909678192...","{6: 0.14205120538873522, 3: 0.1957322284375925...","{6: 0.144343256721419, 3: 0.19096455635730825,...","{6: 0.0974936067543283, 'ALL': 0.3818834440712...","{6: 0.13581602876671742, 'ALL': 0.315320889948..."
0661e926-f219-456e-bde5-612fee6f891c,"{1: 0.5097794107374761, 'ALL': 0.5097794107374...","{1: 0.5098890573973827, 'ALL': 0.5098890575889...","{1: 0.40382837513277886, 'ALL': 0.403828375132...","{1: 0.5097793943287842, 'ALL': 0.5097793943287...","{1: 0.5226197237158193, 'ALL': 0.5523754794596...","{'ALL': 0.24230124561810834, 1: 0.297588137544...","{'ALL': 0.10575993245413426, 1: 0.041990600614..."
0ad2f65b-ee0e-4d50-93e2-84b76282325f,"{'ALL': 0.4500724264082394, 2: 0.0, 1: 0.31166...","{'ALL': 0.3502143586396694, 2: 0.0, 1: 0.33212...","{'ALL': 0.5726461890753668, 2: 0.0, 1: 0.57290...","{'ALL': 0.3291705278506425, 2: 0.0, 1: 0.32914...","{'ALL': 0.48700646804676906, 2: 0.0, 1: 0.5104...","{'ALL': 0.3199745679229612, 2: 0.0, 1: 0.34804...","{'ALL': 0.5493269975707225, 2: 0.0, 1: 0.53174..."
173e2b27-8bc6-44d1-b581-a1913d6b1894,"{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.2...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.3...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.2...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.4...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.3...","{5: 0.02829018646578775, 16: 0.0, 1: 0.2256331...","{5: 0.04241223439903114, 16: 0.0, 1: 0.3995683..."
2058f680-aace-4b31-aed4-f34397b75096,"{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}"
22fde42e-45d7-46cd-9d6f-3a4dbabbc579,"{'ALL': 0.8513695392006424, 1: 0.0, 5: 0.0, 6:...","{'ALL': 0.9278731650522143, 1: 0.0, 5: 0.0, 6:...","{'ALL': 1.4550731765156883, 1: 0.0, 5: 0.0, 6:...","{'ALL': 1.6008849858280871, 1: 0.0, 5: 0.0, 6:...","{'ALL': 1.1150348133262886, 1: 0.0, 5: 0.0, 6:...","{6: 0.0, 'ALL': 0.8159645645212904, 5: 0.0, 1:...","{6: 0.0, 'ALL': 1.2074720313003113, 5: 0.0, 1:..."
3dc15e4b-b60d-4c49-aae8-97cf9664af51,"{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}"
423a069b-27b8-44ed-9ef3-ca3cf9470970,"{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}"
457bce7b-9300-4c10-9a97-070b3c0d081d,"{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 5: 0.0, 1: 0.0, 3: 0.0}","{'ALL': 0.0, 5: 0.0, 1: 0.0, 3: 0.0}"
478cd985-f4fc-45b4-ac71-bf78cf11e07b,"{4: 0.0, 1: 0.6698111844586713, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 0.7836775795970184, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 0.6351694588966396, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 0.6698111844586713, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 1.3333333333333333, 5: 0.0, 6: 0.0...","{2: 0.0, 5: 0.0, 1: 0.3751711466950555, 6: 0.0...","{2: 0.0, 5: 0.0, 1: 0.29732228838711444, 6: 0...."
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab,"{2: 0.04769477177005012, 'ALL': 0.117970916499...","{2: 0.0, 'ALL': 0.02001573947091513, 1: 0.0154...","{2: 0.04561887008802765, 'ALL': 0.121719198303...","{2: 0.0056468272883189565, 'ALL': 0.0193017708...","{2: 0.12752287009754845, 'ALL': 0.191257620920...","{'ALL': 0.1391839106559886, 2: 0.0617886024841...","{'ALL': 0.0, 2: 0.14871123311611115, 1: 0.3841..."
50409b57-b000-43d5-9358-44c3081c4132,"{1: 0.7938578863328096, 'ALL': 0.7938578863328...","{1: 0.8178806913624911, 'ALL': 0.8178806913624...","{1: 0.666739266680707, 'ALL': 0.666739266680707}","{1: 0.7938578124623552, 'ALL': 0.7938578124623...","{1: 0.5103879556754432, 'ALL': 0.5271321236933...","{'ALL': 0.41979944953754555, 1: 0.423410768924...","{'ALL': 0.5968974782180998, 1: 0.5989106659081..."
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb,"{'ALL': 0.49709520321481726, 1: 0.497095203214...","{'ALL': 0.29067579393589826, 1: 0.281058133187...","{'ALL': 0.5112335610713565, 1: 0.5112335610713...","{'ALL': 0.2856974441168944, 1: 0.2856974441168...","{'ALL': 0.4188457525647677, 1: 0.4093168468168...","{1: 0.2850263307303724, 'ALL': 0.2825388626242...","{1: 0.5040202928625123, 'ALL': 0.3962191073756..."
60c8f748-e29d-4fce-9e66-584117ca2baf,"{'ALL': 0.41316448091651925, 4: 0.0, 1: 0.4477...","{'ALL': 0.24135042205758123, 4: 0.0, 1: 0.2413...","{'ALL': 0.4505104288184157, 4: 0.0, 1: 0.45051...","{'ALL': 0.41316448091651925, 4: 0.0, 1: 0.4477...","{'ALL': 0.4051214119299109, 4: 0.0, 1: 0.38675...","{4: 0.0, 'ALL': 0.2515095439621755, 1: 0.25168...","{4: 0.0, 'ALL': 0.2234025456050011, 1: 0.22361..."
60ca8452-5b14-481f-a637-8756f527aee8,"{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{1: 0.0, 10: 0.0, 6: 0.0, 'ALL': 0.0}","{1: 0.0, 10: 0.0, 6: 0.0, 'ALL': 0.0}"
6276b87c-ebb2-11ed-a05b-0242ac120003,"{8: 0.18326106533246228, 6: 0.0, 9: 0.15578382...","{8: 0.22696885595503102, 6: 0.0, 9: 0.12257260...","{8: 0.3487791709164587, 6: 0.0, 9: 0.184552312...","{8: 0.19581169661613199, 6: 0.0, 9: 0.19894295...","{8: 0.28654914517245184, 6: 0.0, 9: 0.26342971...","{3: 0.0, 8: 0.19565728542702326, 6: 0.0, 'ALL'...","{3: 0.0, 8: 0.30180203422339547, 6: 0.0, 'ALL'..."
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b,"{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}"
7412074f-0f3a-4724-b035-7fb4db3174c8,"{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{8: 0.0, 15: 0.0, 'ALL': 0.7806872480933718, 1...","{8: 0.0, 15: 0.0, 'ALL': 0.5766440820630965, 1..."
74abffac-6542-4eff-8eae-cc85463a5d02,"{1: 0.42691774830664275, 2: 0.0, 'ALL': 0.4268...","{1: 0.25171724264465, 2: 0.0, 'ALL': 0.2516622...","{1: 0.361879115767993, 2: 0.0, 'ALL': 0.361172...","{1: 0.33008308864706254, 2: 0.0, 'ALL': 0.4268...","{1: 0.38885693337925126, 2: 0.0, 'ALL': 0.3878...","{2: 0.0, 'ALL': 0.371128370925088, 1: 0.269258...","{2: 0.0, 'ALL': 0.45034058160385537, 1: 0.4554..."
775dcad4-0733-4c22-8dbd-cd3ce344e891,"{'ALL': 0.33556436846803506, 2: 0.629455854981...","{'ALL': 0.7348391676372723, 2: 0.4129745846807...","{'ALL': 0.32197191149112003, 2: 0.321198867643...","{'ALL': 0.5033465527020526, 2: 0.3362415513946...","{'ALL': 0.5365594604731142, 2: 0.5256906085751...","{'ALL': 0.27563930049615815, 2: 0.192168909674...","{'ALL': 0.5841874318611723, 2: 0.5839819864028..."
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b,"{'ALL': 0.3403376387560597, 3: 0.0, 1: 0.34033...","{'ALL': 0.6937692093689474, 3: 0.0, 1: 0.37260...","{'ALL': 0.46307590367896684, 3: 0.0, 1: 0.4630...","{'ALL': 0.3403376387560597, 3: 0.0, 1: 0.34033...","{'ALL': 0.521094816459011, 3: 0.0, 1: 0.501747...","{1: 0.4057092898076528, 3: 0.0, 'ALL': 0.39789...","{1: 0.6056272924187203, 3: 0.0, 'ALL': 0.60397..."
7db6eaca-fe22-41d7-bfb8-1fdde880feb8,"{'ALL': 0.1981336514628741, 2: 0.0, 1: 0.41554...","{'ALL': 0.21664103165800327, 2: 0.0, 1: 0.2120...","{'ALL': 0.3630849992621983, 2: 0.0, 1: 0.38111...","{'ALL': 0.17190159000485689, 2: 0.0, 1: 0.4014...","{'ALL': 0.45834107275909897, 2: 0.0, 1: 0.4733...","{'ALL': 0.3908971682901952, 2: 0.0, 1: 0.41113...","{'ALL': 0.6110736074753241, 2: 0.0, 1: 0.61465..."
8fa00df1-38eb-426f-81a6-1185983e14cb,"{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}"
92f116fe-5818-41db-9eb5-87445ad3818e,"{'ALL': 0.5687349620042466, 2: 0.0, 5: 0.37920...","{'ALL': 0.41483250622501744, 2: 0.0, 5: 0.4148...","{'ALL': 0.717576456100309, 2: 0.0, 5: 0.717390...","{'ALL': 0.3791566413361644, 2: 0.0, 5: 0.11718...","{'ALL': 0.5522120082303189, 2: 0.0, 5: 0.28910...","{'ALL': 0.3980062588658285, 5: 0.3940969897461...","{'ALL': 0.5936211452606326, 5: 0.5526117027648..."
9d1296ca-9e4f-4840-b7b5-e12172acab78,"{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{'ALL': 0.0, 1: 0.0, 9: 0.0, 5: 0.0, 4: 0.0}","{'ALL': 0.0, 1: 0.0, 9: 0.0, 5: 0.0, 4: 0.0}"
9d39683a-47b3-4a18-942d-f1d741a47e8c,"{'ALL': 0.3267742056993122, 1: 0.3267742056993...","{'ALL': 0.3457906387165968, 1: 0.3457906378285...","{'ALL': 0.3662783885695453, 1: 0.3662783885695...","{'ALL': 0.3267742056993122, 1: 0.3267742056993...","{'ALL': 0.32790934476434674, 1: 0.324759448561...","{'ALL': 0.09737479084635518, 1: 0.098123266894...","{'ALL': 0.29419300557818123, 1: 0.293671072872..."
aabe992c-cfad-4049-b5df-36c41f900a67,"{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}"
ad942d1a-15ab-4a0d-83a8-ae82183ece53,"{'ALL': 0.5437368101665412, 2: 0.3548289091636...","{'ALL': 0.32096663410526804, 2: 0.418500519723...","{'ALL': 0.6201535515068005, 2: 0.3806639655404...","{'ALL': 0.5437368101733495, 2: 0.3548289091601...","{'ALL': 0.4698044626625527, 2: 0.2950462106051...","{'ALL': 0.14671365878046624, 2: 0.0, 1: 0.1096...","{'ALL': 0.2790669193750644, 2: 0.3115758658781..."
adc6fb62-09e7-44fd-a619-f787ecfd140b,"{'ALL': 0.6158498427135128, 2: 0.1876382703409...","{'ALL': 0.3606344890622168, 2: 0.1392852115446...","{'ALL': 0.3200285450025746, 2: 0.2426070017955...","{'ALL': 0.6158498427135128, 2: 0.2403094830116...","{'ALL': 0.4524784086819223, 2: 0.3133403524970...","{'ALL': 0.28337614932376487, 2: 0.182868872180...","{'ALL': 0.5671458666501811, 2: 0.3823373232353..."
b009c05b-326e-4ebe-988c-8d2229ec3a4c,"{'ALL': 0.387508786865684, 1: 0.387508786865684}","{'ALL': 0.42372148538946264, 1: 0.423721584609...","{'ALL': 0.7129576343168427, 1: 0.7129576343168...","{'ALL': 0.387508786865684, 1: 0.387508786865684}","{'ALL': 0.5441240628780987, 1: 0.5375092855577...","{'ALL': 0.6048487402587153, 1: 0.4052559294443...","{'ALL': 0.5914142111341544, 1: 0.5921084575338..."
bfcbb283-4e53-41fd-9b31-aa818f7f23ce,"{'ALL': 1.4555528938839275, 1: 0.0, 9: 0.0}","{'ALL': 1.5963177827985084, 1: 0.0, 9: 0.0}","{'ALL': 1.3807795251563477, 1: 0.0, 9: 0.0}","{'ALL': 1.4555528938839275, 1: 0.0, 9: 0.0}","{'ALL': 1.1234698572921173, 1: 0.0, 9: 0.0}","{'ALL': 0.761987958197862, 1: 0.0, 9: 0.0}","{'ALL': 1.200441108742333, 1: 0.0, 9: 0.0}"
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4,"{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}"
ca35e88d-d191-4722-b90c-92f4a249869b,"{7: 0.0, 'ALL': 0.7842858343015582, 12: 0.0, 1...","{7: 0.0, 'ALL': 0.5171981435994957, 12: 0.0, 1...","{7: 0.0, 'ALL': 0.8052413948701183, 12: 0.0, 1...","{7: 0.0, 'ALL': 0.47486362649823854, 12: 0.0, ...","{7: 0.0, 'ALL': 0.6123338761715464, 12: 0.0, 1...","{'ALL': 0.42338653946277055, 1: 0.290296649388...","{'ALL': 0.7184994600567162, 1: 0.4775179825744..."
d639773a-df2c-421e-ac87-6918a754572f,"{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{1: 0.0, 14: 0.0, 'ALL': 0.0}","{1: 0.0, 14: 0.0, 'ALL': 0.0}"
e2de40dd-743b-4105-9077-3f343fea980d,"{'ALL': 0.3178137169897532, 1: 0.3178137169897...","{'ALL': 0.30422330765104505, 1: 0.304223307649...","{'ALL': 0.3143438532525315, 1: 0.3143438532525...","{'ALL': 0.27910490949249983, 1: 0.279104909492...","{'ALL': 0.4361808056018588, 1: 0.43955012930169}","{1: 0.3216470024304752, 'ALL': 0.2830383864815...","{1: 0.5288351293685953, 'ALL': 0.5295070095809..."
f9129295-bb08-4330-b60c-9f0beadda521,"{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{42: 0.0, 24: 0.0, 4: 0.0, 36: 0.0, 32: 0.0, 6...","{42: 0.0, 24: 0.0, 4: 0.0, 36: 0.0, 32: 0.0, 6..."

In [39]:
df_scores2 = df_scores12.merge(df_scores22, how='outer', left_index=True, right_index=True, sort=False)
joblib.dump(df_scores2, 'df_scores2.pkl')
df_scores2.to_csv('df_scores2.csv', sep=';', encoding='latin1', index=True)

df_scores2

,GradientBoosting,LSTM,TBATS,Ensemble,Chronos,"amazon/chronos-bolt-base:v2025-03-09:cl(370):q(0.3,0.7)",MEDIAN_MAD_60
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6,"{6: 0.2687836755945146, 3: 0.3791340371395408,...","{6: 0.2840297365726457, 3: 0.39831999423898784...","{6: 0.28887472015507765, 3: 0.3998031356637399...","{6: 0.2687836755945146, 3: 0.37913403603376566...","{6: 0.27765032825534464, 3: 0.4106718769057024...","{6: 0.30689680175455675, 'ALL': 0.744088952280...","{6: 0.25892320680613623, 'ALL': 0.626835301339..."
0661e926-f219-456e-bde5-612fee6f891c,"{1: 0.9469462634855225, 'ALL': 0.9469462634855...","{1: 1.0130325631496984, 'ALL': 1.013032565065393}","{1: 0.7858184083575777, 'ALL': 0.7858184083575...","{1: 0.9469462429746577, 'ALL': 0.9469462429746...","{1: 1.056538365959226, 'ALL': 1.0913607818329885}","{'ALL': 1.1031300133220414, 1: 1.1054466393912...","{'ALL': 0.7382457467602968, 1: 0.4199060061458..."
0ad2f65b-ee0e-4d50-93e2-84b76282325f,"{'ALL': 1.041343146475989, 2: 0.0, 1: 1.041317...","{'ALL': 1.1238143559887415, 2: 0.0, 1: 1.12378...","{'ALL': 1.0120813085330855, 2: 0.0, 1: 1.01266...","{'ALL': 1.0413431464688145, 2: 0.0, 1: 1.04131...","{'ALL': 0.9269345902608628, 2: 0.0, 1: 0.94887...","{'ALL': 1.0601233821947162, 2: 0.0, 1: 1.14345...","{'ALL': 0.9737400510003915, 2: 0.0, 1: 0.97456..."
173e2b27-8bc6-44d1-b581-a1913d6b1894,"{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.9...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.9...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.8...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.9...","{9: 0.0, 16: 0.0, 18: 0.0, 14: 0.0, 'ALL': 0.8...","{5: 0.09812570207682786, 16: 0.0, 1: 0.8058184...","{5: 0.0751953529461361, 16: 0.0, 1: 0.72970889..."
2058f680-aace-4b31-aed4-f34397b75096,"{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}"
22fde42e-45d7-46cd-9d6f-3a4dbabbc579,"{'ALL': 2.8923324425097823, 1: 0.0, 5: 0.0, 6:...","{'ALL': 3.1211558171566844, 1: 0.0, 5: 0.0, 6:...","{'ALL': 2.510709584656852, 1: 0.0, 5: 0.0, 6: ...","{'ALL': 2.8923329258779815, 1: 0.0, 5: 0.0, 6:...","{'ALL': 1.3937935166578606, 1: 0.0, 5: 0.0, 6:...","{6: 0.0, 'ALL': 2.8169549950638304, 5: 0.0, 1:...","{6: 0.0, 'ALL': 2.2051172231290073, 5: 0.0, 1:..."
3dc15e4b-b60d-4c49-aae8-97cf9664af51,"{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}"
423a069b-27b8-44ed-9ef3-ca3cf9470970,"{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}"
457bce7b-9300-4c10-9a97-070b3c0d081d,"{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 3: 0.0, 1: 0.0, 5: 0.0}","{'ALL': 0.0, 5: 0.0, 1: 0.0, 3: 0.0}","{'ALL': 0.0, 5: 0.0, 1: 0.0, 3: 0.0}"
478cd985-f4fc-45b4-ac71-bf78cf11e07b,"{4: 0.0, 1: 1.238696684724528, 5: 0.0, 6: 0.0,...","{4: 0.0, 1: 1.3388879677093661, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 1.1215817878002738, 5: 0.0, 6: 0.0...","{4: 0.0, 1: 1.238696684724528, 5: 0.0, 6: 0.0,...","{4: 0.0, 1: 1.6666666666666665, 5: 0.0, 6: 0.0...","{2: 0.0, 5: 0.0, 1: 1.2863757285144768, 6: 0.0...","{2: 0.0, 5: 0.0, 1: 1.0571014171848696, 6: 0.0..."
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab,"{2: 0.2949421317334402, 'ALL': 0.8793811446872...","{2: 0.0, 'ALL': 0.40031478941830256, 1: 0.3087...","{2: 0.28282514775752726, 'ALL': 0.899506599461...","{2: 0.11293654576637914, 'ALL': 0.386035416252...","{2: 0.24279857096246882, 'ALL': 0.665473843727...","{'ALL': 1.0007819102349984, 2: 0.2992851512495...","{'ALL': 0.0, 2: 0.264525798908987, 1: 0.703000..."
50409b57-b000-43d5-9358-44c3081c4132,"{1: 1.3486544157665221, 'ALL': 1.3486544157665...","{1: 1.4571144021869313, 'ALL': 1.4571144021869...","{1: 1.1551607151405554, 'ALL': 1.1551607151405...","{1: 1.3486543234284538, 'ALL': 1.3486543234284...","{1: 0.6379849445943039, 'ALL': 0.6589151546166...","{'ALL': 1.436644995788238, 1: 1.4383620866054403}","{'ALL': 1.068365924404224, 1: 1.0784318628546794}"
5dd8b3ee-6f1c-4ac9-bbc5-91829dde38eb,"{'ALL': 0.9464301259765222, 1: 0.9464301259765...","{'ALL': 1.0152193073017821, 1: 1.0152193073017...","{'ALL': 0.937621260577583, 1: 0.937621260577583}","{'ALL': 0.9464301259765222, 1: 0.9464301259765...","{'ALL': 0.8789431814639299, 1: 0.8695869455523...","{1: 0.980276969984867, 'ALL': 0.9740020553635256}","{1: 0.9317474378633932, 'ALL': 0.9772156755582..."
60c8f748-e29d-4fce-9e66-584117ca2baf,"{'ALL': 0.8192489152179053, 4: 0.0, 1: 0.81924...","{'ALL': 0.8714893257155459, 4: 0.0, 1: 0.87148...","{'ALL': 0.8205388504832023, 4: 0.0, 1: 0.82053...","{'ALL': 0.8192489152179053, 4: 0.0, 1: 0.81924...","{'ALL': 0.8327711092738616, 4: 0.0, 1: 0.81094...","{4: 0.0, 'ALL': 0.8832561190826294, 1: 0.88608...","{4: 0.0, 'ALL': 0.8190766748611591, 1: 0.82115..."
60ca8452-5b14-481f-a637-8756f527aee8,"{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{10: 0.0, 1: 0.0, 'ALL': 0.0, 6: 0.0}","{1: 0.0, 10: 0.0, 6: 0.0, 'ALL': 0.0}","{1: 0.0, 10: 0.0, 6: 0.0, 'ALL': 0.0}"
6276b87c-ebb2-11ed-a05b-0242ac120003,"{8: 0.6464121325862014, 6: 0.0, 9: 0.694655501...","{8: 0.6990106365337003, 6: 0.0, 9: 0.751080449...","{8: 0.6173376617776747, 6: 0.0, 9: 0.650031458...","{8: 0.6464121325862014, 6: 0.0, 9: 0.694655501...","{8: 0.5423233660326015, 6: 0.0, 9: 0.548432195...","{3: 0.0, 8: 0.6842112276808452, 6: 0.0, 'ALL':...","{3: 0.0, 8: 0.5509494377738401, 6: 0.0, 'ALL':..."
6cd2fa8a-5bac-4cc0-b4df-bd2c7d29e71b,"{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}"
7412074f-0f3a-4724-b035-7fb4db3174c8,"{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{1: 0.0, 11: 0.0, 17: 0.0, 8: 0.0, 15: 0.0, 16...","{8: 0.0, 15: 0.0, 'ALL': 2.6089445802964626, 1...","{8: 0.0, 15: 0.0, 'ALL': 2.0439855290556075, 1..."
74abffac-6542-4eff-8eae-cc85463a5d02,"{1: 0.8799645234114103, 2: 0.0, 'ALL': 0.87984...","{1: 0.9374031652391575, 2: 0.0, 'ALL': 0.93726...","{1: 0.9405630602381798, 2: 0.0, 'ALL': 0.93931...","{1: 0.8799645172956823, 2: 0.0, 'ALL': 0.87984...","{1: 0.8644920553079056, 2: 0.0, 'ALL': 0.88037...","{2: 0.0, 'ALL': 0.9603843929002339, 1: 0.98717...","{2: 0.0, 'ALL': 0.8551394488811488, 1: 0.86247..."
775dcad4-0733-4c22-8dbd-cd3ce344e891,"{'ALL': 1.1614784508165195, 2: 1.1633076055101...","{'ALL': 1.2544550119230111, 2: 1.2564723188462...","{'ALL': 1.11784757176871, 2: 1.115745022162797...","{'ALL': 1.1614784508165195, 2: 1.1633076957544...","{'ALL': 1.08108796822501, 2: 0.657113260718985...","{'ALL': 1.2594605029548815, 2: 1.3099201966833...","{'ALL': 1.0331891680405954, 2: 1.0321619407490..."
789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b,"{'ALL': 1.2191424515144613, 3: 0.0, 1: 1.21914...","{'ALL': 1.3172518906895627, 3: 0.0, 1: 1.31725...","{'ALL': 0.9066914910305325, 3: 0.0, 1: 0.90669...","{'ALL': 1.2191424515144613, 3: 0.0, 1: 1.21914...","{'ALL': 0.896751454476378, 3: 0.0, 1: 0.871452...","{1: 1.4058698330717252, 3: 0.0, 'ALL': 1.37770...","{1: 1.1120149954073264, 3: 0.0, 'ALL': 1.10376..."
7db6eaca-fe22-41d7-bfb8-1fdde880feb8,"{'ALL': 1.3841491791846283, 2: 0.0, 1: 1.46163...","{'ALL': 1.4966282307197494, 2: 0.0, 1: 1.28305...","{'ALL': 1.27346556834477, 2: 0.0, 1: 1.3383750...","{'ALL': 0.8595079500242845, 2: 0.0, 1: 1.46163...","{'ALL': 0.5729263409488736, 2: 0.0, 1: 0.59166...","{'ALL': 1.3767351389540672, 2: 0.0, 1: 1.46128...","{'ALL': 1.139246570690346, 2: 0.0, 1: 1.157163..."
8fa00df1-38eb-426f-81a6-1185983e14cb,"{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}"
92f116fe-5818-41db-9eb5-87445ad3818e,"{'ALL': 1.2836928467452888, 2: 0.0, 5: 1.28381...","{'ALL': 1.3873551053659365, 2: 0.0, 5: 1.38748...","{'ALL': 1.2182090765356826, 2: 0.0, 5: 1.21790...","{'ALL': 1.2836928467452888, 2: 0.0, 5: 0.86577...","{'ALL': 1.069847067375283, 2: 0.0, 5: 1.093341...","{'ALL': 1.331617950755854, 5: 1.32016976073687...","{'ALL': 1.0519842596168885, 5: 1.0551669387140..."
9d1296ca-9e4f-4840-b7b5-e12172acab78,"{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{1: 0.0, 'ALL': 0.0, 4: 0.0, 5: 0.0, 9: 0.0}","{'ALL': 0.0, 1: 0.0, 9: 0.0, 5: 0.0, 4: 0.0}","{'ALL': 0.0, 1: 0.0, 9: 0.0, 5: 0.0, 4: 0.0}"
9d39683a-47b3-4a18-942d-f1d741a47e8c,"{'ALL': 0.624000001471167, 1: 0.624000001471167}","{'ALL': 0.6536531710971303, 1: 0.6536531696626...","{'ALL': 0.678848535734115, 1: 0.678848535734115}","{'ALL': 0.624000001471167, 1: 0.624000001471167}","{'ALL': 0.6763001008491318, 1: 0.6765767564187...","{'ALL': 0.71247976386419, 1: 0.7167388359029406}","{'ALL': 0.6203678279728426, 1: 0.6151485009172..."
aabe992c-cfad-4049-b5df-36c41f900a67,"{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{2: 0.0, 'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}","{'ALL': 0.0, 2: 0.0, 1: 0.0}"
ad942d1a-15ab-4a0d-83a8-ae82183ece53,"{'ALL': 1.0838257658997361, 2: 0.6886914776015...","{'ALL': 1.1631188559239753, 2: 0.7424723936904...","{'ALL': 1.1183973298375205, 2: 0.6780825202687...","{'ALL': 1.08382576596782, 2: 0.688691477567132...","{'ALL': 1.0389243942325175, 2: 0.6334460310475...","{'ALL': 0.7335682939023311, 2: 0.0, 1: 0.38518...","{'ALL': 1.0806970778152158, 2: 0.6289855454641..."
adc6fb62-09e7-44fd-a619-f787ecfd140b,"{'ALL': 1.1462927640131022, 2: 0.8229591085896...","{'ALL': 1.2376331949840669, 2: 0.8894988684358...","{'ALL': 1.1088812331648867, 2: 0.7836616416434...","{'ALL': 1.1462927640131022, 2: 0.8229591909140...","{'ALL': 0.9777378196953058, 2: 0.6674421185302...","{'ALL': 1.238624149573818, 2: 0.85885823220704...","{'ALL': 1.0227280295298098, 2: 0.7037614832786..."
b009c05b-326e-4ebe-988c-8d2229ec3a4c,"{'ALL': 1.3022947663903435, 1: 1.3022947663903...","{'ALL': 1.40710057938879, 1: 1.407100827437873}","{'ALL': 1.2072129730516277, 1: 1.2072129730516...","{'ALL': 1.3022947663903435, 1: 1.3022947663903...","{'ALL': 1.0793117070004765, 1: 1.0715832237044...","{'ALL': 1.2907349833854043, 1: 1.2760854861992...","{'ALL': 1.040949588984497, 1: 1.0444208209831278}"
bfcbb283-4e53-41fd-9b31-aa818f7f23ce,"{'ALL': 2.6189652224654374, 1: 0.0, 9: 0.0}","{'ALL': 2.8301028551409395, 1: 0.0, 9: 0.0}","{'ALL': 2.284620948318842, 1: 0.0, 9: 0.0}","{'ALL': 2.6189652224654374, 1: 0.0, 9: 0.0}","{'ALL': 2.3067300475297587, 1: 0.0, 9: 0.0}","{'ALL': 2.6184856195056865, 1: 0.0, 9: 0.0}","{'ALL': 2.169962610339116, 1: 0.0, 9: 0.0}"
c0cc925b-66c1-4b1c-b609-1bddc82ef4a4,"{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{'ALL': 0.0, 1: 0.0}","{1: 0.0, 'ALL': 0.0}","{1: 0.0, 'ALL': 0.0}"
ca35e88d-d191-4722-b90c-92f4a249869b,"{7: 0.0, 'ALL': 1.4628949108443339, 12: 0.0, 1...","{7: 0.0, 'ALL': 1.5809377284690926, 12: 0.0, 1...","{7: 0.0, 'ALL': 1.405972679101682, 12: 0.0, 1:...","{7: 0.0, 'ALL': 1.4628948479412456, 12: 0.0, 1...","{7: 0.0, 'ALL': 1.2801628784544734, 12: 0.0, 1...","{'ALL': 1.4703947714688186, 1: 1.0028923441229...","{'ALL': 1.2931515402600515, 1: 0.8546927395233..."
d639773a-df2c-421e-ac87-6918a754572f,"{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{'ALL': 0.0, 14: 0.0, 1: 0.0}","{1: 0.0, 14: 0.0, 'ALL': 0.0}","{1: 0.0, 14: 0.0, 'ALL': 0.0}"
e2de40dd-743b-4105-9077-3f343fea980d,"{'ALL': 0.9880783299606499, 1: 0.9880783299606...","{'ALL': 1.061643275406417, 1: 1.0616432753901404}","{'ALL': 0.9702833107933819, 1: 0.9702833107933...","{'ALL': 0.9880783299606499, 1: 0.9880783299606...","{'ALL': 0.8900056112766455, 1: 0.8903433791368...","{1: 0.9906761686377351, 'ALL': 0.9849586701724...","{1: 0.9469073165093491, 'ALL': 0.950266717571185}"
f9129295-bb08-4330-b60c-9f0beadda521,"{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{32: 0.0, 8: 0.0, 34: 0.0, 6: 0.0, 33: 0.0, 10...","{42: 0.0, 24: 0.0, 4: 0.0, 36: 0.0, 32: 0.0, 6...","{42: 0.0, 24: 0.0, 4: 0.0, 36: 0.0, 32: 0.0, 6..."

In [40]:
df_scores1.to_csv('scores1_per_channel.csv', sep=';', encoding='latin1', index=True)
df_scores2.to_csv('scores2_per_channel.csv', sep=';', encoding='latin1', index=True)