In [12]:
import numpy as np
import pandas as pd
import psycopg2
from tqdm import tqdm
from datetime import timedelta
from dateutil.relativedelta import relativedelta

In [13]:
sales = pd.read_csv('pedidos-1743765883268.csv', sep=';', encoding='latin1')

In [14]:
df = sales[['account_id', 'sales_channel_id']].value_counts()
df = pd.DataFrame(df).reset_index()

In [15]:
EPOCHS = 1000
BATCH_SIZE = 32
VALID_SPLIT = 0.1

In [16]:
LOOKBACK = 3
SEASONAL_PERIODS = (24, 24*7)
COVERAGE = 0.33
END_DATE = pd.to_datetime(pd.to_datetime(sales['created_date'].max()).strftime("%Y-%m-%d %H:00:00"))
START_DATE = END_DATE - timedelta(hours=END_DATE.hour)
TEST_SIZE = int((END_DATE - START_DATE).seconds / 60**2 + 1)

In [17]:
account_ids = ['05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '4f1c8b04-eb4b-4887-8c69-a096f0fda3ab', 'ad942d1a-15ab-4a0d-83a8-ae82183ece53']

df_filtered = df[df['account_id'].isin(account_ids)]

In [18]:
# id_pairs = list(zip(df['account_id'], df['sales_channel_id']))
id_pairs = list(zip(df_filtered['account_id'], df_filtered['sales_channel_id']))

In [34]:
id_pairs

[('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', 3),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', 6),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', 5),
 ('ad942d1a-15ab-4a0d-83a8-ae82183ece53', 1),
 ('ad942d1a-15ab-4a0d-83a8-ae82183ece53', 2),
 ('4f1c8b04-eb4b-4887-8c69-a096f0fda3ab', 1),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', 1),
 ('4f1c8b04-eb4b-4887-8c69-a096f0fda3ab', 2),
 ('05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', 4),
 ('ad942d1a-15ab-4a0d-83a8-ae82183ece53', 3)]

In [27]:
weights_chan = {}
for account_id, sales_channel_id in tqdm(id_pairs):
    
    if sales_channel_id == 'ALL':
        cond = (sales['account_id'] == account_id) & \
               (sales['status'].notna())
    else:
        cond = (sales['account_id'] == account_id) & \
               (sales['sales_channel_id'] == sales_channel_id) & \
               (sales['status'].notna())

    df_client = sales[cond].drop(['account_id', 'sales_channel_id'], axis=1)
    df_client['created_date'] = pd.to_datetime(df_client['created_date'], format='%Y-%m-%d %H:%M:%S.%f %z')
    df_client = df_client.sort_values('created_date').reset_index(drop=True)
    df_client['created_date'] = df_client['created_date'].dt.strftime("%Y-%m-%d %H:00:00").reset_index(drop=True)

    df_client_mod = df_client.groupby('created_date').agg(price_total_agg=('price_total', 'sum'), n_orders=('created_date', 'count'))
    df_client_mod.index = pd.to_datetime(df_client_mod.index, format='%Y-%m-%d %H:00:00')

    end_date = pd.to_datetime(END_DATE, format='%Y-%m-%d %H:%M:%S')
    start_date = end_date - relativedelta(months=LOOKBACK)
    date_index = pd.Series(pd.date_range(start=start_date, end=end_date, freq='h', name='created_date'))
    df_client_mod = pd.merge(date_index, df_client_mod, how='left', on='created_date').set_index('created_date')
    
    weights_chan[account_id] = {} if account_id not in weights_chan else weights_chan[account_id]
    
    df = df_client_mod['n_orders'].fillna(0)
    df = df.loc[df.index <= END_DATE]
    
    weights_chan[account_id][sales_channel_id] = df.median()

100%|██████████| 10/10 [00:36<00:00,  3.64s/it]

In [28]:
weights_df = pd.DataFrame(weights_chan)

weights_df

,05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6,ad942d1a-15ab-4a0d-83a8-ae82183ece53,4f1c8b04-eb4b-4887-8c69-a096f0fda3ab
3,68.0,0.0,NaN
6,42.0,NaN,NaN
5,6.0,NaN,NaN
1,0.0,2.0,8.0
4,0.0,NaN,NaN
2,NaN,3.0,3.0

In [29]:
weights_df = weights_df.stack().reset_index().rename(columns={'level_0': 'sales_channel_id', 'level_1': 'account_id', 0: 'weights'}).sort_values(by=['account_id', 'sales_channel_id'])

weights_df

   sales_channel_id                            account_id  weights
4                 1  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6      0.0
0                 3  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6     68.0
7                 4  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6      0.0
3                 5  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6      6.0
2                 6  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6     42.0
6                 1  4f1c8b04-eb4b-4887-8c69-a096f0fda3ab      8.0
9                 2  4f1c8b04-eb4b-4887-8c69-a096f0fda3ab      3.0
5                 1  ad942d1a-15ab-4a0d-83a8-ae82183ece53      2.0
8                 2  ad942d1a-15ab-4a0d-83a8-ae82183ece53      3.0
1                 3  ad942d1a-15ab-4a0d-83a8-ae82183ece53      0.0

In [30]:
weights_chan_df = weights_df.groupby('account_id')['weights'].apply(lambda x: x / x.sum()).fillna(0).reset_index().rename(columns={0: 'weights'}).drop('level_1', axis=1)

weights_chan_df = pd.concat([weights_df['sales_channel_id'].reset_index(drop=True), weights_chan_df], axis=1)

weights_chan_df

   sales_channel_id                            account_id   weights
0                 1  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6  0.000000
1                 3  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6  0.586207
2                 4  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6  0.000000
3                 5  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6  0.051724
4                 6  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6  0.362069
5                 1  4f1c8b04-eb4b-4887-8c69-a096f0fda3ab  0.727273
6                 2  4f1c8b04-eb4b-4887-8c69-a096f0fda3ab  0.272727
7                 1  ad942d1a-15ab-4a0d-83a8-ae82183ece53  0.400000
8                 2  ad942d1a-15ab-4a0d-83a8-ae82183ece53  0.600000
9                 3  ad942d1a-15ab-4a0d-83a8-ae82183ece53  0.000000

In [31]:
weights_acc_df = weights_df.groupby('account_id')['weights'].sum() / weights_df.groupby('account_id')['weights'].sum().sum()

weights_acc_df

account_id
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6    0.878788
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab    0.083333
ad942d1a-15ab-4a0d-83a8-ae82183ece53    0.037879
Name: weights, dtype: float64

In [33]:
dbname = 'railway'
username = 'sinatra'
pwd = '781B3XjpeuqE'
hostname = 'monorail.proxy.rlwy.net'
port = 25096

connection = psycopg2.connect(database=dbname, user=username, password=pwd, host=hostname, port=port)
cursor = connection.cursor()

In [36]:
model = 'GradientBoosting'

In [43]:
df_forecast_metrics_norm = {}
scores = {}
df_forecast_metrics_norm[model] = {}

for account_id, sales_channel_id in id_pairs:
    
    print(account_id, sales_channel_id)
    
    # if sales_channel_id == 'ALL':
    #     cond = (sales['account_id'] == account_id) & \
    #            (sales['status'].notna())
    # else:
    #     cond = (sales['account_id'] == account_id) & \
    #            (sales['sales_channel_id'] == sales_channel_id) & \
    #            (sales['status'].notna())
    cond = (sales['account_id'] == account_id) & \
           (sales['sales_channel_id'] == sales_channel_id) & \
           (sales['status'].notna())

    df_client = sales[cond].drop(['account_id', 'sales_channel_id'], axis=1)
    df_client['created_date'] = pd.to_datetime(df_client['created_date'], format='%Y-%m-%d %H:%M:%S.%f %z')
    df_client = df_client.sort_values('created_date').reset_index(drop=True)
    df_client['created_date'] = df_client['created_date'].dt.strftime("%Y-%m-%d %H:00:00").reset_index(drop=True)

    df_client_mod = df_client.groupby('created_date').agg(price_total_agg=('price_total', 'sum'), n_orders=('created_date', 'count'))
    df_client_mod.index = pd.to_datetime(df_client_mod.index, format='%Y-%m-%d %H:00:00')

    end_date = pd.to_datetime(END_DATE, format='%Y-%m-%d %H:%M:%S')
    start_date = end_date - relativedelta(months=LOOKBACK)
    date_index = pd.Series(pd.date_range(start=start_date, end=end_date, freq='h', name='created_date'))
    df_client_mod = pd.merge(date_index, df_client_mod, how='left', on='created_date').set_index('created_date')
    
    df_forecast_metrics_norm[model][account_id] = {} if account_id not in df_forecast_metrics_norm[model] else df_forecast_metrics_norm[model][account_id]
    for dataset in ['sales', 'orders']:
        if dataset == 'sales':
            col = 'price_total_agg'
        else:
            col = 'n_orders'
        
        df = df_client_mod[col].fillna(0)
        
        y_test = df.loc[(df.index >= START_DATE) & (df.index <= END_DATE)].copy()
    
        cursor.execute(f"select {dataset}_high, {dataset}_low, {dataset}_mean from public.forecast where account_id = '{account_id}' and channel = '{sales_channel_id}' and model = '{model}'")
        res = cursor.fetchall()
        
        df_forecast = pd.DataFrame(res, columns=[f'{dataset}_high', f'{dataset}_low', f'{dataset}_mean'])[:9].set_index(y_test.index)
        
        display(df_forecast)
        
        forecast_mean = df_forecast[f'{dataset}_mean']
        forecast_low = df_forecast[f'{dataset}_low']
        forecast_high = df_forecast[f'{dataset}_high']
        
        forecast = pd.concat([y_test, forecast_mean, forecast_low, forecast_high], axis=1)
        forecast.columns = ['actual', 'forecast', 'lower', 'upper']
        
        display(forecast)
        
        df_forecast = forecast.assign(
            covered_pts=lambda x:
                4*x['actual'].between(x['lower'], x['upper'], inclusive='both') +
                2*(x['actual'].between(2*x['lower']-x['forecast'], x['lower'], inclusive='left') + x['actual'].between(x['upper'], 2*x['upper']-x['forecast'], inclusive='right')) +
                1*(x['actual'].between(3*x['lower']-2*x['forecast'], 2*x['lower']-x['forecast'], inclusive='left') + x['actual'].between(2*x['upper']-x['forecast'], 3*x['upper']-2*x['forecast'], inclusive='right')),
            covered_width=lambda x: x['upper'] - x['lower'],
        )
        
        display(df_forecast)
        
        df_forecast_metrics = {}
        df_forecast_metrics['total_covered'] = df_forecast['covered_pts'].sum()
        df_forecast_metrics['avg_covered'] = df_forecast['covered_pts'].mean()
        df_forecast_metrics['avg_covered_width'] = df_forecast['covered_width'].mean()
        
        display(df_forecast_metrics)
        
        if dataset == 'orders':
            df_forecast_orders_metrics_norm = df_forecast_metrics['avg_covered']/(1 + np.log(1 + df_forecast_metrics['avg_covered_width']))
            print('orders_metric:', df_forecast_orders_metrics_norm)
        else: 
            df_forecast_sales_metrics_norm = df_forecast_metrics['avg_covered']/(1 + np.log(1 + df_forecast_metrics['avg_covered_width']))
            print('sales_metric:', df_forecast_sales_metrics_norm)
    
    weight_chan = weights_chan_df.loc[(weights_chan_df['account_id'] == account_id) & (weights_chan_df['sales_channel_id'] == sales_channel_id), 'weights'].values[0]
    print(weight_chan)
    df_forecast_metrics_norm[model][account_id][sales_channel_id] = weight_chan * (0.5*df_forecast_sales_metrics_norm + 0.5*df_forecast_orders_metrics_norm)
    print(df_forecast_metrics_norm[model][account_id][sales_channel_id])

05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 3

                       sales_high     sales_low    sales_mean
created_date
2025-04-04 00:00:00   5270.203808   4808.226625   5100.822289
2025-04-04 01:00:00   3889.668714   3427.691531   3720.287195
2025-04-04 02:00:00   1715.070000   1294.026518   1545.688481
2025-04-04 03:00:00    851.464054    595.130000    639.642629
2025-04-04 04:00:00    959.067183    497.090000    745.173036
2025-04-04 05:00:00    642.470000    386.135946    430.648575
2025-04-04 06:00:00   1838.051519   1624.157371   1668.670000
2025-04-04 07:00:00   4872.306775   4615.972721   4660.485350
2025-04-04 08:00:00  12818.439542  12356.462359  12649.058023

                      actual      forecast         lower         upper
created_date
2025-04-04 00:00:00  8263.33   5100.822289   4808.226625   5270.203808
2025-04-04 01:00:00  3262.63   3720.287195   3427.691531   3889.668714
2025-04-04 02:00:00  1715.07   1545.688481   1294.026518   1715.070000
2025-04-04 03:00:00   595.13    639.642629    595.130000    851.464054
2025-04-04 04:00:00   497.09    745.173036    497.090000    959.067183
2025-04-04 05:00:00   642.47    430.648575    386.135946    642.470000
2025-04-04 06:00:00  1668.67   1668.670000   1624.157371   1838.051519
2025-04-04 07:00:00  6766.89   4660.485350   4615.972721   4872.306775
2025-04-04 08:00:00  5432.42  12649.058023  12356.462359  12818.439542

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,8263.33,5100.822289,4808.226625,5270.203808,0,461.977183
2025-04-04 01:00:00,3262.63,3720.287195,3427.691531,3889.668714,2,461.977183
2025-04-04 02:00:00,1715.07,1545.688481,1294.026518,1715.070000,4,421.043482
2025-04-04 03:00:00,595.13,639.642629,595.130000,851.464054,2,256.334054
2025-04-04 04:00:00,497.09,745.173036,497.090000,959.067183,4,461.977183
2025-04-04 05:00:00,642.47,430.648575,386.135946,642.470000,2,256.334054
2025-04-04 06:00:00,1668.67,1668.670000,1624.157371,1838.051519,4,213.894148
2025-04-04 07:00:00,6766.89,4660.485350,4615.972721,4872.306775,0,256.334054
2025-04-04 08:00:00,5432.42,12649.058023,12356.462359,12818.439542,0,461.977183

{'total_covered': np.int64(18),
 'avg_covered': np.float64(2.0),
 'avg_covered_width': np.float64(361.3165026666667)}

sales_metric: 0.2901697111945687

                    orders_high orders_low orders_mean
created_date
2025-04-04 00:00:00   15.899451  14.208119   15.338230
2025-04-04 01:00:00    9.519235   7.727355    8.857466
2025-04-04 02:00:00    6.000000   4.308669    5.438780
2025-04-04 03:00:00    3.288611   1.597280    2.727391
2025-04-04 04:00:00    4.823251   3.131919    4.262031
2025-04-04 05:00:00    5.791881   4.868081    5.691331
2025-04-04 06:00:00   13.661770  11.869889   13.000000
2025-04-04 07:00:00   26.722643  25.899392   26.161422
2025-04-04 08:00:00   52.825878  52.002627   52.264658

                     actual   forecast      lower      upper
created_date
2025-04-04 00:00:00    16.0  15.338230  14.208119  15.899451
2025-04-04 01:00:00     5.0   8.857466   7.727355   9.519235
2025-04-04 02:00:00     6.0   5.438780   4.308669   6.000000
2025-04-04 03:00:00     4.0   2.727391   1.597280   3.288611
2025-04-04 04:00:00     4.0   4.262031   3.131919   4.823251
2025-04-04 05:00:00     4.0   5.691331   4.868081   5.791881
2025-04-04 06:00:00    13.0  13.000000  11.869889  13.661770
2025-04-04 07:00:00    37.0  26.161422  25.899392  26.722643
2025-04-04 08:00:00    14.0  52.264658  52.002627  52.825878

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,16.0,15.338230,14.208119,15.899451,2,1.691332
2025-04-04 01:00:00,5.0,8.857466,7.727355,9.519235,0,1.791880
2025-04-04 02:00:00,6.0,5.438780,4.308669,6.000000,4,1.691331
2025-04-04 03:00:00,4.0,2.727391,1.597280,3.288611,1,1.691331
2025-04-04 04:00:00,4.0,4.262031,3.131919,4.823251,4,1.691332
2025-04-04 05:00:00,4.0,5.691331,4.868081,5.791881,1,0.923800
2025-04-04 06:00:00,13.0,13.000000,11.869889,13.661770,4,1.791881
2025-04-04 07:00:00,37.0,26.161422,25.899392,26.722643,0,0.823251
2025-04-04 08:00:00,14.0,52.264658,52.002627,52.825878,0,0.823251

{'total_covered': np.int64(16),
 'avg_covered': np.float64(1.7777777777777777),
 'avg_covered_width': np.float64(1.4354876666666667)}

orders_metric: 0.9405500038466145
0.5862068965517241
0.36072819233965714
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 6

                       sales_high     sales_low    sales_mean
created_date
2025-04-04 00:00:00   4954.130000   4457.913949   4559.668032
2025-04-04 01:00:00   2365.546108   1883.337411   1985.091494
2025-04-04 02:00:00    407.558915     -3.764083     97.990000
2025-04-04 03:00:00    411.322997   -902.587411    101.754083
2025-04-04 04:00:00    411.322997   -902.587411    101.754083
2025-04-04 05:00:00   1059.510000    648.187003    749.941085
2025-04-04 06:00:00   3161.916126   2665.700075   2767.454158
2025-04-04 07:00:00   7315.223903   6819.007852   6920.761935
2025-04-04 08:00:00  12537.146037  12125.823039  12227.577122

                      actual      forecast         lower         upper
created_date
2025-04-04 00:00:00  4954.13   4559.668032   4457.913949   4954.130000
2025-04-04 01:00:00   980.75   1985.091494   1883.337411   2365.546108
2025-04-04 02:00:00    97.99     97.990000     -3.764083    407.558915
2025-04-04 03:00:00     0.00    101.754083   -902.587411    411.322997
2025-04-04 04:00:00   907.62    101.754083   -902.587411    411.322997
2025-04-04 05:00:00  1059.51    749.941085    648.187003   1059.510000
2025-04-04 06:00:00  1620.49   2767.454158   2665.700075   3161.916126
2025-04-04 07:00:00  9591.47   6920.761935   6819.007852   7315.223903
2025-04-04 08:00:00  3637.66  12227.577122  12125.823039  12537.146037

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,4954.13,4559.668032,4457.913949,4954.130000,2,496.216051
2025-04-04 01:00:00,980.75,1985.091494,1883.337411,2365.546108,0,482.208697
2025-04-04 02:00:00,97.99,97.990000,-3.764083,407.558915,4,411.322998
2025-04-04 03:00:00,0.00,101.754083,-902.587411,411.322997,4,1313.910408
2025-04-04 04:00:00,907.62,101.754083,-902.587411,411.322997,1,1313.910408
2025-04-04 05:00:00,1059.51,749.941085,648.187003,1059.510000,4,411.322997
2025-04-04 06:00:00,1620.49,2767.454158,2665.700075,3161.916126,0,496.216051
2025-04-04 07:00:00,9591.47,6920.761935,6819.007852,7315.223903,0,496.216051
2025-04-04 08:00:00,3637.66,12227.577122,12125.823039,12537.146037,0,411.322998

{'total_covered': np.int64(15),
 'avg_covered': np.float64(1.6666666666666667),
 'avg_covered_width': np.float64(648.071851)}

sales_metric: 0.22294923229354646

                    orders_high orders_low orders_mean
created_date
2025-04-04 00:00:00   17.894841  15.385465   15.769845
2025-04-04 01:00:00    4.461887   3.105159    3.875004
2025-04-04 02:00:00    3.509376   1.000000    1.384380
2025-04-04 03:00:00    1.835408   0.864145    1.248525
2025-04-04 04:00:00    3.538113   1.028738    1.413117
2025-04-04 05:00:00    2.114744   0.758017    1.527862
2025-04-04 06:00:00    9.871207   7.615620    8.000000
2025-04-04 07:00:00   20.161201  18.804473   19.574318
2025-04-04 08:00:00   33.868056  32.511329   33.281174

                     actual   forecast      lower      upper
created_date
2025-04-04 00:00:00    15.0  15.769845  15.385465  17.894841
2025-04-04 01:00:00     6.0   3.875004   3.105159   4.461887
2025-04-04 02:00:00     1.0   1.384380   1.000000   3.509376
2025-04-04 03:00:00     0.0   1.248525   0.864145   1.835408
2025-04-04 04:00:00     2.0   1.413117   1.028738   3.538113
2025-04-04 05:00:00     6.0   1.527862   0.758017   2.114744
2025-04-04 06:00:00     8.0   8.000000   7.615620   9.871207
2025-04-04 07:00:00    22.0  19.574318  18.804473  20.161201
2025-04-04 08:00:00    13.0  33.281174  32.511329  33.868056

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,15.0,15.769845,15.385465,17.894841,1,2.509376
2025-04-04 01:00:00,6.0,3.875004,3.105159,4.461887,0,1.356728
2025-04-04 02:00:00,1.0,1.384380,1.000000,3.509376,4,2.509376
2025-04-04 03:00:00,0.0,1.248525,0.864145,1.835408,0,0.971263
2025-04-04 04:00:00,2.0,1.413117,1.028738,3.538113,4,2.509375
2025-04-04 05:00:00,6.0,1.527862,0.758017,2.114744,0,1.356727
2025-04-04 06:00:00,8.0,8.000000,7.615620,9.871207,4,2.255587
2025-04-04 07:00:00,22.0,19.574318,18.804473,20.161201,0,1.356728
2025-04-04 08:00:00,13.0,33.281174,32.511329,33.868056,0,1.356727

{'total_covered': np.int64(13),
 'avg_covered': np.float64(1.4444444444444444),
 'avg_covered_width': np.float64(1.7979874444444444)}

orders_metric: 0.7119346284057153
0.3620689655172414
0.16924621616107324
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 5

                      sales_high    sales_low   sales_mean
created_date
2025-04-04 00:00:00  1054.054160   690.268674   827.413234
2025-04-04 01:00:00   468.407216   -28.395160    66.707432
2025-04-04 02:00:00   235.205574  -261.596802  -166.494211
2025-04-04 03:00:00   496.802376     0.000000   321.743517
2025-04-04 04:00:00   363.785486     6.936925   137.144561
2025-04-04 05:00:00   361.768859  -135.033517   -39.930925
2025-04-04 06:00:00   710.109785   213.307408   308.410000
2025-04-04 07:00:00   630.691141   308.947624   404.050215
2025-04-04 08:00:00  1080.902420   717.116933   854.261494

                      actual     forecast        lower        upper
created_date
2025-04-04 00:00:00   379.71   827.413234   690.268674  1054.054160
2025-04-04 01:00:00   491.66    66.707432   -28.395160   468.407216
2025-04-04 02:00:00  1382.59  -166.494211  -261.596802   235.205574
2025-04-04 03:00:00     0.00   321.743517     0.000000   496.802376
2025-04-04 04:00:00     0.00   137.144561     6.936925   363.785486
2025-04-04 05:00:00   186.71   -39.930925  -135.033517   361.768859
2025-04-04 06:00:00   308.41   308.410000   213.307408   710.109785
2025-04-04 07:00:00   805.75   404.050215   308.947624   630.691141
2025-04-04 08:00:00   241.72   854.261494   717.116933  1080.902420

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,379.71,827.413234,690.268674,1054.054160,0,363.785486
2025-04-04 01:00:00,491.66,66.707432,-28.395160,468.407216,2,496.802376
2025-04-04 02:00:00,1382.59,-166.494211,-261.596802,235.205574,0,496.802376
2025-04-04 03:00:00,0.00,321.743517,0.000000,496.802376,4,496.802376
2025-04-04 04:00:00,0.00,137.144561,6.936925,363.785486,2,356.848561
2025-04-04 05:00:00,186.71,-39.930925,-135.033517,361.768859,4,496.802376
2025-04-04 06:00:00,308.41,308.410000,213.307408,710.109785,4,496.802377
2025-04-04 07:00:00,805.75,404.050215,308.947624,630.691141,2,321.743517
2025-04-04 08:00:00,241.72,854.261494,717.116933,1080.902420,0,363.785487

{'total_covered': np.int64(18),
 'avg_covered': np.float64(2.0),
 'avg_covered_width': np.float64(432.2416591111111)}

sales_metric: 0.28283359818282633

                    orders_high orders_low orders_mean
created_date
2025-04-04 00:00:00    4.766465   3.866204    4.072287
2025-04-04 01:00:00    2.019203   0.779184    0.985267
2025-04-04 02:00:00    2.000000   0.761132    0.966064
2025-04-04 03:00:00    1.240019   0.001151    0.206083
2025-04-04 04:00:00    0.899110  -0.001151    0.204932
2025-04-04 05:00:00    1.694178   0.793917    1.000000
2025-04-04 06:00:00    3.339758   2.100890    2.305822
2025-04-04 07:00:00    4.400877   3.500617    3.706699
2025-04-04 08:00:00    7.494299   6.594038    6.800121

                     actual  forecast      lower     upper
created_date
2025-04-04 00:00:00     3.0  4.072287   3.866204  4.766465
2025-04-04 01:00:00     3.0  0.985267   0.779184  2.019203
2025-04-04 02:00:00     2.0  0.966064   0.761132  2.000000
2025-04-04 03:00:00     0.0  0.206083   0.001151  1.240019
2025-04-04 04:00:00     0.0  0.204932  -0.001151  0.899110
2025-04-04 05:00:00     1.0  1.000000   0.793917  1.694178
2025-04-04 06:00:00     3.0  2.305822   2.100890  3.339758
2025-04-04 07:00:00     6.0  3.706699   3.500617  4.400877
2025-04-04 08:00:00     1.0  6.800121   6.594038  7.494299

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,3.0,4.072287,3.866204,4.766465,0,0.900261
2025-04-04 01:00:00,3.0,0.985267,0.779184,2.019203,2,1.240019
2025-04-04 02:00:00,2.0,0.966064,0.761132,2.000000,4,1.238868
2025-04-04 03:00:00,0.0,0.206083,0.001151,1.240019,2,1.238868
2025-04-04 04:00:00,0.0,0.204932,-0.001151,0.899110,4,0.900261
2025-04-04 05:00:00,1.0,1.000000,0.793917,1.694178,4,0.900261
2025-04-04 06:00:00,3.0,2.305822,2.100890,3.339758,4,1.238868
2025-04-04 07:00:00,6.0,3.706699,3.500617,4.400877,0,0.900260
2025-04-04 08:00:00,1.0,6.800121,6.594038,7.494299,0,0.900261

{'total_covered': np.int64(20),
 'avg_covered': np.float64(2.2222222222222223),
 'avg_covered_width': np.float64(1.0508807777777778)}

orders_metric: 1.293290963995612
0.05172413793103448
0.04076184212530444
ad942d1a-15ab-4a0d-83a8-ae82183ece53 1

                     sales_high   sales_low  sales_mean
created_date
2025-04-04 00:00:00  118.527374   76.809470   95.788369
2025-04-04 01:00:00   59.510000   13.501083   48.830019
2025-04-04 02:00:00   37.095236   -4.622667   14.356231
2025-04-04 03:00:00   38.162405  -25.839487   18.978898
2025-04-04 04:00:00   22.739005  -44.818386    0.000000
2025-04-04 05:00:00  -21.548474  -41.717903  -22.739005
2025-04-04 06:00:00  110.508917   64.500000  109.318386
2025-04-04 07:00:00  301.113128  233.555737  278.374123
2025-04-04 08:00:00  284.948465  238.939547  283.757933

                     actual    forecast       lower       upper
created_date
2025-04-04 00:00:00  262.00   95.788369   76.809470  118.527374
2025-04-04 01:00:00   59.51   48.830019   13.501083   59.510000
2025-04-04 02:00:00  171.99   14.356231   -4.622667   37.095236
2025-04-04 03:00:00    0.00   18.978898  -25.839487   38.162405
2025-04-04 04:00:00    0.00    0.000000  -44.818386   22.739005
2025-04-04 05:00:00    0.00  -22.739005  -41.717903  -21.548474
2025-04-04 06:00:00   64.50  109.318386   64.500000  110.508917
2025-04-04 07:00:00   96.31  278.374123  233.555737  301.113128
2025-04-04 08:00:00  148.68  283.757933  238.939547  284.948465

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,262.00,95.788369,76.809470,118.527374,0,41.717904
2025-04-04 01:00:00,59.51,48.830019,13.501083,59.510000,4,46.008917
2025-04-04 02:00:00,171.99,14.356231,-4.622667,37.095236,0,41.717903
2025-04-04 03:00:00,0.00,18.978898,-25.839487,38.162405,4,64.001892
2025-04-04 04:00:00,0.00,0.000000,-44.818386,22.739005,4,67.557391
2025-04-04 05:00:00,0.00,-22.739005,-41.717903,-21.548474,0,20.169429
2025-04-04 06:00:00,64.50,109.318386,64.500000,110.508917,4,46.008917
2025-04-04 07:00:00,96.31,278.374123,233.555737,301.113128,0,67.557391
2025-04-04 08:00:00,148.68,283.757933,238.939547,284.948465,0,46.008918

{'total_covered': np.int64(16),
 'avg_covered': np.float64(1.7777777777777777),
 'avg_covered_width': np.float64(48.97207355555556)}

sales_metric: 0.3619649175412081

                    orders_high orders_low orders_mean
created_date
2025-04-04 00:00:00    0.650446   0.282176    0.381454
2025-04-04 01:00:00    1.008224   0.290400    0.389678
2025-04-04 02:00:00    0.986138   0.276007    0.367593
2025-04-04 03:00:00    0.521647   0.199998    0.252656
2025-04-04 04:00:00    0.368270   0.046621    0.099279
2025-04-04 05:00:00    0.268992  -0.091586    0.000000
2025-04-04 06:00:00    1.000000   0.639422    0.731008
2025-04-04 07:00:00    2.321649   2.000000    2.052657
2025-04-04 08:00:00    4.425665   3.754462    3.807119

                     actual  forecast      lower     upper
created_date
2025-04-04 00:00:00     1.0  0.381454   0.282176  0.650446
2025-04-04 01:00:00     2.0  0.389678   0.290400  1.008224
2025-04-04 02:00:00     1.0  0.367593   0.276007  0.986138
2025-04-04 03:00:00     0.0  0.252656   0.199998  0.521647
2025-04-04 04:00:00     0.0  0.099279   0.046621  0.368270
2025-04-04 05:00:00     0.0  0.000000  -0.091586  0.268992
2025-04-04 06:00:00     1.0  0.731008   0.639422  1.000000
2025-04-04 07:00:00     2.0  2.052657   2.000000  2.321649
2025-04-04 08:00:00     1.0  3.807119   3.754462  4.425665

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,1.0,0.381454,0.282176,0.650446,1,0.368270
2025-04-04 01:00:00,2.0,0.389678,0.290400,1.008224,1,0.717824
2025-04-04 02:00:00,1.0,0.367593,0.276007,0.986138,2,0.710131
2025-04-04 03:00:00,0.0,0.252656,0.199998,0.521647,0,0.321649
2025-04-04 04:00:00,0.0,0.099279,0.046621,0.368270,2,0.321649
2025-04-04 05:00:00,0.0,0.000000,-0.091586,0.268992,4,0.360578
2025-04-04 06:00:00,1.0,0.731008,0.639422,1.000000,4,0.360578
2025-04-04 07:00:00,2.0,2.052657,2.000000,2.321649,4,0.321649
2025-04-04 08:00:00,1.0,3.807119,3.754462,4.425665,0,0.671203

{'total_covered': np.int64(18),
 'avg_covered': np.float64(2.0),
 'avg_covered_width': np.float64(0.46150344444444447)}

orders_metric: 1.449836740834659
0.4
0.36236033167517345
ad942d1a-15ab-4a0d-83a8-ae82183ece53 2

                     sales_high    sales_low  sales_mean
created_date
2025-04-04 00:00:00   10.626643   -13.747481    0.000000
2025-04-04 01:00:00  -22.127654  -123.418860  -27.318818
2025-04-04 02:00:00   24.374124  -104.842784    8.556318
2025-04-04 03:00:00   15.817807    -8.556318    0.000000
2025-04-04 04:00:00    0.000000   -24.374124  -15.817807
2025-04-04 05:00:00  191.166908    61.950000  175.349101
2025-04-04 06:00:00  275.105129   261.357648  269.913965
2025-04-04 07:00:00  237.057256   212.683131  221.239449
2025-04-04 08:00:00  798.968782   774.594658  783.150976

                     actual    forecast        lower       upper
created_date
2025-04-04 00:00:00    0.00    0.000000   -13.747481   10.626643
2025-04-04 01:00:00  216.07  -27.318818  -123.418860  -22.127654
2025-04-04 02:00:00    0.00    8.556318  -104.842784   24.374124
2025-04-04 03:00:00    0.00    0.000000    -8.556318   15.817807
2025-04-04 04:00:00    0.00  -15.817807   -24.374124    0.000000
2025-04-04 05:00:00   61.95  175.349101    61.950000  191.166908
2025-04-04 06:00:00   30.12  269.913965   261.357648  275.105129
2025-04-04 07:00:00  431.19  221.239449   212.683131  237.057256
2025-04-04 08:00:00  225.24  783.150976   774.594658  798.968782

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,0.00,0.000000,-13.747481,10.626643,4,24.374124
2025-04-04 01:00:00,216.07,-27.318818,-123.418860,-22.127654,0,101.291206
2025-04-04 02:00:00,0.00,8.556318,-104.842784,24.374124,4,129.216908
2025-04-04 03:00:00,0.00,0.000000,-8.556318,15.817807,4,24.374125
2025-04-04 04:00:00,0.00,-15.817807,-24.374124,0.000000,4,24.374124
2025-04-04 05:00:00,61.95,175.349101,61.950000,191.166908,4,129.216908
2025-04-04 06:00:00,30.12,269.913965,261.357648,275.105129,0,13.747481
2025-04-04 07:00:00,431.19,221.239449,212.683131,237.057256,0,24.374125
2025-04-04 08:00:00,225.24,783.150976,774.594658,798.968782,0,24.374124

{'total_covered': np.int64(20),
 'avg_covered': np.float64(2.2222222222222223),
 'avg_covered_width': np.float64(55.038125)}

sales_metric: 0.44214245076173314

                    orders_high orders_low orders_mean
created_date
2025-04-04 00:00:00    0.567682   0.000000    0.292629
2025-04-04 01:00:00    0.570331   0.086090    0.399955
2025-04-04 02:00:00    0.488437   0.025432    0.318061
2025-04-04 03:00:00    0.000000  -0.488437   -0.170376
2025-04-04 04:00:00    0.170376  -0.313865    0.000000
2025-04-04 05:00:00    0.895323   0.406885    0.724947
2025-04-04 06:00:00    2.400027   1.911590    2.229651
2025-04-04 07:00:00    2.621184   2.158179    2.450808
2025-04-04 08:00:00    5.636785   5.173781    5.466409

                     actual   forecast      lower     upper
created_date
2025-04-04 00:00:00     0.0   0.292629   0.000000  0.567682
2025-04-04 01:00:00     1.0   0.399955   0.086090  0.570331
2025-04-04 02:00:00     0.0   0.318061   0.025432  0.488437
2025-04-04 03:00:00     0.0  -0.170376  -0.488437  0.000000
2025-04-04 04:00:00     0.0   0.000000  -0.313865  0.170376
2025-04-04 05:00:00     1.0   0.724947   0.406885  0.895323
2025-04-04 06:00:00     1.0   2.229651   1.911590  2.400027
2025-04-04 07:00:00     5.0   2.450808   2.158179  2.621184
2025-04-04 08:00:00     4.0   5.466409   5.173781  5.636785

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,0.0,0.292629,0.000000,0.567682,4,0.567682
2025-04-04 01:00:00,1.0,0.399955,0.086090,0.570331,0,0.484241
2025-04-04 02:00:00,0.0,0.318061,0.025432,0.488437,2,0.463005
2025-04-04 03:00:00,0.0,-0.170376,-0.488437,0.000000,4,0.488437
2025-04-04 04:00:00,0.0,0.000000,-0.313865,0.170376,4,0.484241
2025-04-04 05:00:00,1.0,0.724947,0.406885,0.895323,2,0.488438
2025-04-04 06:00:00,1.0,2.229651,1.911590,2.400027,0,0.488437
2025-04-04 07:00:00,5.0,2.450808,2.158179,2.621184,0,0.463005
2025-04-04 08:00:00,4.0,5.466409,5.173781,5.636785,0,0.463004

{'total_covered': np.int64(16),
 'avg_covered': np.float64(1.7777777777777777),
 'avg_covered_width': np.float64(0.4878322222222222)}

orders_metric: 1.2722766106831682
0.6
0.5143257184334704
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab 1

                      sales_high    sales_low   sales_mean
created_date
2025-04-04 00:00:00  1604.674479  1570.360000  1586.467831
2025-04-04 01:00:00   918.220533   150.319797   900.013886
2025-04-04 02:00:00   -78.077924  -845.978660   -96.284572
2025-04-04 03:00:00   -12.677509  -101.553451   -85.445620
2025-04-04 04:00:00   -54.561463  -822.462199   -72.768111
2025-04-04 05:00:00   433.341463   344.465521   360.573352
2025-04-04 06:00:00  1142.990736  1108.676257  1124.784088
2025-04-04 07:00:00  1223.786648   455.885912  1205.580000
2025-04-04 08:00:00  2193.130947  1425.230211  2174.924299

                      actual     forecast        lower        upper
created_date
2025-04-04 00:00:00  1570.36  1586.467831  1570.360000  1604.674479
2025-04-04 01:00:00     0.00   900.013886   150.319797   918.220533
2025-04-04 02:00:00     0.00   -96.284572  -845.978660   -78.077924
2025-04-04 03:00:00   133.15   -85.445620  -101.553451   -12.677509
2025-04-04 04:00:00     0.00   -72.768111  -822.462199   -54.561463
2025-04-04 05:00:00   378.78   360.573352   344.465521   433.341463
2025-04-04 06:00:00   375.09  1124.784088  1108.676257  1142.990736
2025-04-04 07:00:00  1205.58  1205.580000   455.885912  1223.786648
2025-04-04 08:00:00   449.90  2174.924299  1425.230211  2193.130947

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,1570.36,1586.467831,1570.360000,1604.674479,4,34.314479
2025-04-04 01:00:00,0.00,900.013886,150.319797,918.220533,2,767.900736
2025-04-04 02:00:00,0.00,-96.284572,-845.978660,-78.077924,0,767.900736
2025-04-04 03:00:00,133.15,-85.445620,-101.553451,-12.677509,0,88.875942
2025-04-04 04:00:00,0.00,-72.768111,-822.462199,-54.561463,0,767.900736
2025-04-04 05:00:00,378.78,360.573352,344.465521,433.341463,4,88.875942
2025-04-04 06:00:00,375.09,1124.784088,1108.676257,1142.990736,0,34.314479
2025-04-04 07:00:00,1205.58,1205.580000,455.885912,1223.786648,4,767.900736
2025-04-04 08:00:00,449.90,2174.924299,1425.230211,2193.130947,1,767.900736

{'total_covered': np.int64(15),
 'avg_covered': np.float64(1.6666666666666667),
 'avg_covered_width': np.float64(453.9871691111111)}

sales_metric: 0.2340735463016851

                    orders_high orders_low orders_mean
created_date
2025-04-04 00:00:00    3.656261   2.122973    3.180322
2025-04-04 01:00:00    4.413870   2.942343    3.190047
2025-04-04 02:00:00    0.995589  -0.475939   -0.228234
2025-04-04 03:00:00   -0.175296  -1.708584   -0.403531
2025-04-04 04:00:00    0.228234  -0.247704    0.000000
2025-04-04 05:00:00    1.004411   0.528473    0.776177
2025-04-04 06:00:00    3.533288   2.000000    3.305053
2025-04-04 07:00:00    6.475939   6.000000    6.247704
2025-04-04 08:00:00    9.327914   8.851975    9.099679

                     actual   forecast      lower      upper
created_date
2025-04-04 00:00:00     6.0   3.180322   2.122973   3.656261
2025-04-04 01:00:00     0.0   3.190047   2.942343   4.413870
2025-04-04 02:00:00     0.0  -0.228234  -0.475939   0.995589
2025-04-04 03:00:00     1.0  -0.403531  -1.708584  -0.175296
2025-04-04 04:00:00     0.0   0.000000  -0.247704   0.228234
2025-04-04 05:00:00     2.0   0.776177   0.528473   1.004411
2025-04-04 06:00:00     2.0   3.305053   2.000000   3.533288
2025-04-04 07:00:00     6.0   6.247704   6.000000   6.475939
2025-04-04 08:00:00     4.0   9.099679   8.851975   9.327914

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,6.0,3.180322,2.122973,3.656261,0,1.533288
2025-04-04 01:00:00,0.0,3.190047,2.942343,4.413870,0,1.471527
2025-04-04 02:00:00,0.0,-0.228234,-0.475939,0.995589,4,1.471528
2025-04-04 03:00:00,1.0,-0.403531,-1.708584,-0.175296,0,1.533288
2025-04-04 04:00:00,0.0,0.000000,-0.247704,0.228234,4,0.475938
2025-04-04 05:00:00,2.0,0.776177,0.528473,1.004411,0,0.475938
2025-04-04 06:00:00,2.0,3.305053,2.000000,3.533288,4,1.533288
2025-04-04 07:00:00,6.0,6.247704,6.000000,6.475939,4,0.475939
2025-04-04 08:00:00,4.0,9.099679,8.851975,9.327914,0,0.475939

{'total_covered': np.int64(16),
 'avg_covered': np.float64(1.7777777777777777),
 'avg_covered_width': np.float64(1.0496303333333334)}

orders_metric: 1.0350001428002673
0.7272727272727273
0.4614813414916191
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 1

                      sales_high    sales_low   sales_mean
created_date
2025-04-04 00:00:00     0.000000  -306.335532  -108.499195
2025-04-04 01:00:00  -240.880633  -438.716970  -349.379827
2025-04-04 02:00:00     0.000000  -197.836338  -108.499195
2025-04-04 03:00:00  -240.880633  -438.716970  -240.880633
2025-04-04 04:00:00   197.836338     0.000000    89.337143
2025-04-04 05:00:00   108.499195   -89.337143     0.000000
2025-04-04 06:00:00   306.335532     0.000000   197.836338
2025-04-04 07:00:00   683.721028   485.884691   575.221834
2025-04-04 08:00:00   683.721028   485.884691   575.221834

                     actual     forecast        lower        upper
created_date
2025-04-04 00:00:00     0.0  -108.499195  -306.335532     0.000000
2025-04-04 01:00:00     0.0  -349.379827  -438.716970  -240.880633
2025-04-04 02:00:00     0.0  -108.499195  -197.836338     0.000000
2025-04-04 03:00:00     0.0  -240.880633  -438.716970  -240.880633
2025-04-04 04:00:00     0.0    89.337143     0.000000   197.836338
2025-04-04 05:00:00     0.0     0.000000   -89.337143   108.499195
2025-04-04 06:00:00     0.0   197.836338     0.000000   306.335532
2025-04-04 07:00:00     0.0   575.221834   485.884691   683.721028
2025-04-04 08:00:00     0.0   575.221834   485.884691   683.721028

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,0.0,-108.499195,-306.335532,0.000000,4,306.335532
2025-04-04 01:00:00,0.0,-349.379827,-438.716970,-240.880633,0,197.836337
2025-04-04 02:00:00,0.0,-108.499195,-197.836338,0.000000,4,197.836338
2025-04-04 03:00:00,0.0,-240.880633,-438.716970,-240.880633,0,197.836337
2025-04-04 04:00:00,0.0,89.337143,0.000000,197.836338,4,197.836338
2025-04-04 05:00:00,0.0,0.000000,-89.337143,108.499195,4,197.836338
2025-04-04 06:00:00,0.0,197.836338,0.000000,306.335532,4,306.335532
2025-04-04 07:00:00,0.0,575.221834,485.884691,683.721028,0,197.836337
2025-04-04 08:00:00,0.0,575.221834,485.884691,683.721028,0,197.836337

{'total_covered': np.int64(20),
 'avg_covered': np.float64(2.2222222222222223),
 'avg_covered_width': np.float64(221.94726955555555)}

sales_metric: 0.34684636627041177

                    orders_high orders_low orders_mean
created_date
2025-04-04 00:00:00   -0.012711  -0.095186   -0.013387
2025-04-04 01:00:00   -0.012711  -0.095186   -0.013387
2025-04-04 02:00:00   -0.012711  -0.095186   -0.013387
2025-04-04 03:00:00    0.013387  -0.033484    0.000676
2025-04-04 04:00:00    0.010614  -0.082475   -0.000676
2025-04-04 05:00:00    0.034160  -0.048315    0.033484
2025-04-04 06:00:00    0.082475   0.000000    0.081799
2025-04-04 07:00:00    1.185824   1.103349    1.185148
2025-04-04 08:00:00    1.364353   1.330193    1.363677

                     actual   forecast      lower      upper
created_date
2025-04-04 00:00:00     0.0  -0.013387  -0.095186  -0.012711
2025-04-04 01:00:00     0.0  -0.013387  -0.095186  -0.012711
2025-04-04 02:00:00     0.0  -0.013387  -0.095186  -0.012711
2025-04-04 03:00:00     0.0   0.000676  -0.033484   0.013387
2025-04-04 04:00:00     0.0  -0.000676  -0.082475   0.010614
2025-04-04 05:00:00     0.0   0.033484  -0.048315   0.034160
2025-04-04 06:00:00     0.0   0.081799   0.000000   0.082475
2025-04-04 07:00:00     0.0   1.185148   1.103349   1.185824
2025-04-04 08:00:00     0.0   1.363677   1.330193   1.364353

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,0.0,-0.013387,-0.095186,-0.012711,0,0.082475
2025-04-04 01:00:00,0.0,-0.013387,-0.095186,-0.012711,0,0.082475
2025-04-04 02:00:00,0.0,-0.013387,-0.095186,-0.012711,0,0.082475
2025-04-04 03:00:00,0.0,0.000676,-0.033484,0.013387,4,0.046871
2025-04-04 04:00:00,0.0,-0.000676,-0.082475,0.010614,4,0.093089
2025-04-04 05:00:00,0.0,0.033484,-0.048315,0.034160,4,0.082475
2025-04-04 06:00:00,0.0,0.081799,0.000000,0.082475,4,0.082475
2025-04-04 07:00:00,0.0,1.185148,1.103349,1.185824,0,0.082475
2025-04-04 08:00:00,0.0,1.363677,1.330193,1.364353,0,0.034160

{'total_covered': np.int64(16),
 'avg_covered': np.float64(1.7777777777777777),
 'avg_covered_width': np.float64(0.07433)}

orders_metric: 1.6588433363133968
0.0
0.0
4f1c8b04-eb4b-4887-8c69-a096f0fda3ab 2

                      sales_high    sales_low   sales_mean
created_date
2025-04-04 00:00:00  1534.473485  1085.031372  1243.684191
2025-04-04 01:00:00   746.672113   297.230000   509.088998
2025-04-04 02:00:00   106.412357  -447.521717     0.000000
2025-04-04 03:00:00   273.900000  -175.542113   -70.095473
2025-04-04 04:00:00     0.000000  -553.934075  -106.412357
2025-04-04 05:00:00   455.288210     5.846097   111.292738
2025-04-04 06:00:00   553.934075     0.000000   447.521717
2025-04-04 07:00:00   861.287504   411.845391   517.292031
2025-04-04 08:00:00   905.386895   351.452820   798.974537

                      actual     forecast        lower        upper
created_date
2025-04-04 00:00:00   507.19  1243.684191  1085.031372  1534.473485
2025-04-04 01:00:00   297.23   509.088998   297.230000   746.672113
2025-04-04 02:00:00     0.00     0.000000  -447.521717   106.412357
2025-04-04 03:00:00   273.90   -70.095473  -175.542113   273.900000
2025-04-04 04:00:00     0.00  -106.412357  -553.934075     0.000000
2025-04-04 05:00:00   455.58   111.292738     5.846097   455.288210
2025-04-04 06:00:00     0.00   447.521717     0.000000   553.934075
2025-04-04 07:00:00  1870.63   517.292031   411.845391   861.287504
2025-04-04 08:00:00   242.23   798.974537   351.452820   905.386895

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,507.19,1243.684191,1085.031372,1534.473485,0,449.442113
2025-04-04 01:00:00,297.23,509.088998,297.230000,746.672113,4,449.442113
2025-04-04 02:00:00,0.00,0.000000,-447.521717,106.412357,4,553.934074
2025-04-04 03:00:00,273.90,-70.095473,-175.542113,273.900000,4,449.442113
2025-04-04 04:00:00,0.00,-106.412357,-553.934075,0.000000,4,553.934075
2025-04-04 05:00:00,455.58,111.292738,5.846097,455.288210,2,449.442113
2025-04-04 06:00:00,0.00,447.521717,0.000000,553.934075,4,553.934075
2025-04-04 07:00:00,1870.63,517.292031,411.845391,861.287504,0,449.442113
2025-04-04 08:00:00,242.23,798.974537,351.452820,905.386895,2,553.934075

{'total_covered': np.int64(24),
 'avg_covered': np.float64(2.6666666666666665),
 'avg_covered_width': np.float64(495.8829848888888)}

sales_metric: 0.369941107382604

                    orders_high orders_low orders_mean
created_date
2025-04-04 00:00:00    4.659465   3.000000    3.324687
2025-04-04 01:00:00    2.650873   1.000000    1.316096
2025-04-04 02:00:00    1.334778  -0.316096    0.000000
2025-04-04 03:00:00    0.579668  -1.071205   -0.755110
2025-04-04 04:00:00    0.585658  -1.065216   -0.749120
2025-04-04 05:00:00    0.414342  -0.659465   -0.334778
2025-04-04 06:00:00    1.717077   0.651861    0.967957
2025-04-04 07:00:00    2.391316   1.317509    1.642196
2025-04-04 08:00:00    4.187090   3.113282    3.279922

                     actual   forecast      lower     upper
created_date
2025-04-04 00:00:00     3.0   3.324687   3.000000  4.659465
2025-04-04 01:00:00     1.0   1.316096   1.000000  2.650873
2025-04-04 02:00:00     0.0   0.000000  -0.316096  1.334778
2025-04-04 03:00:00     1.0  -0.755110  -1.071205  0.579668
2025-04-04 04:00:00     0.0  -0.749120  -1.065216  0.585658
2025-04-04 05:00:00     1.0  -0.334778  -0.659465  0.414342
2025-04-04 06:00:00     0.0   0.967957   0.651861  1.717077
2025-04-04 07:00:00     3.0   1.642196   1.317509  2.391316
2025-04-04 08:00:00     2.0   3.279922   3.113282  4.187090

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,3.0,3.324687,3.000000,4.659465,4,1.659465
2025-04-04 01:00:00,1.0,1.316096,1.000000,2.650873,4,1.650873
2025-04-04 02:00:00,0.0,0.000000,-0.316096,1.334778,4,1.650874
2025-04-04 03:00:00,1.0,-0.755110,-1.071205,0.579668,2,1.650873
2025-04-04 04:00:00,0.0,-0.749120,-1.065216,0.585658,4,1.650874
2025-04-04 05:00:00,1.0,-0.334778,-0.659465,0.414342,2,1.073807
2025-04-04 06:00:00,0.0,0.967957,0.651861,1.717077,0,1.065216
2025-04-04 07:00:00,3.0,1.642196,1.317509,2.391316,2,1.073807
2025-04-04 08:00:00,2.0,3.279922,3.113282,4.187090,0,1.073808

{'total_covered': np.int64(22),
 'avg_covered': np.float64(2.4444444444444446),
 'avg_covered_width': np.float64(1.3943996666666667)}

orders_metric: 1.3050034604637903
0.2727272727272727
0.22840153197905375
05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6 4

                    sales_high sales_low sales_mean
created_date
2025-04-04 00:00:00   0.000000  0.000000   0.000000
2025-04-04 01:00:00   0.000000  0.000000   0.000000
2025-04-04 02:00:00   0.000000  0.000000   0.000000
2025-04-04 03:00:00   0.000000  0.000000   0.000000
2025-04-04 04:00:00   0.000000  0.000000   0.000000
2025-04-04 05:00:00   0.000000  0.000000   0.000000
2025-04-04 06:00:00   0.000000  0.000000   0.000000
2025-04-04 07:00:00   0.000000  0.000000   0.000000
2025-04-04 08:00:00   0.000000  0.000000   0.000000

                     actual  forecast     lower     upper
created_date
2025-04-04 00:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 01:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 02:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 03:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 04:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 05:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 06:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 07:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 08:00:00     0.0  0.000000  0.000000  0.000000

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 01:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 02:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 03:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 04:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 05:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 06:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 07:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 08:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000

{'total_covered': np.int64(36),
 'avg_covered': np.float64(4.0),
 'avg_covered_width': np.float64(0.0)}

sales_metric: 4.0

                    orders_high orders_low orders_mean
created_date
2025-04-04 00:00:00    0.000000   0.000000    0.000000
2025-04-04 01:00:00    0.000000   0.000000    0.000000
2025-04-04 02:00:00    0.000000   0.000000    0.000000
2025-04-04 03:00:00    0.000000   0.000000    0.000000
2025-04-04 04:00:00    0.000000   0.000000    0.000000
2025-04-04 05:00:00    0.000000   0.000000    0.000000
2025-04-04 06:00:00    0.000000   0.000000    0.000000
2025-04-04 07:00:00    0.000000   0.000000    0.000000
2025-04-04 08:00:00    0.000000   0.000000    0.000000

                     actual  forecast     lower     upper
created_date
2025-04-04 00:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 01:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 02:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 03:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 04:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 05:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 06:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 07:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 08:00:00     0.0  0.000000  0.000000  0.000000

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 01:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 02:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 03:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 04:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 05:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 06:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 07:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 08:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000

{'total_covered': np.int64(36),
 'avg_covered': np.float64(4.0),
 'avg_covered_width': np.float64(0.0)}

orders_metric: 4.0
0.0
0.0
ad942d1a-15ab-4a0d-83a8-ae82183ece53 3

                    sales_high sales_low sales_mean
created_date
2025-04-04 00:00:00   0.000000  0.000000   0.000000
2025-04-04 01:00:00   0.000000  0.000000   0.000000
2025-04-04 02:00:00   0.000000  0.000000   0.000000
2025-04-04 03:00:00   0.000000  0.000000   0.000000
2025-04-04 04:00:00   0.000000  0.000000   0.000000
2025-04-04 05:00:00   0.000000  0.000000   0.000000
2025-04-04 06:00:00   0.000000  0.000000   0.000000
2025-04-04 07:00:00   0.000000  0.000000   0.000000
2025-04-04 08:00:00   0.000000  0.000000   0.000000

                     actual  forecast     lower     upper
created_date
2025-04-04 00:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 01:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 02:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 03:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 04:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 05:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 06:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 07:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 08:00:00     0.0  0.000000  0.000000  0.000000

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 01:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 02:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 03:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 04:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 05:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 06:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 07:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 08:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000

{'total_covered': np.int64(36),
 'avg_covered': np.float64(4.0),
 'avg_covered_width': np.float64(0.0)}

sales_metric: 4.0

                    orders_high orders_low orders_mean
created_date
2025-04-04 00:00:00    0.000000   0.000000    0.000000
2025-04-04 01:00:00    0.000000   0.000000    0.000000
2025-04-04 02:00:00    0.000000   0.000000    0.000000
2025-04-04 03:00:00    0.000000   0.000000    0.000000
2025-04-04 04:00:00    0.000000   0.000000    0.000000
2025-04-04 05:00:00    0.000000   0.000000    0.000000
2025-04-04 06:00:00    0.000000   0.000000    0.000000
2025-04-04 07:00:00    0.000000   0.000000    0.000000
2025-04-04 08:00:00    0.000000   0.000000    0.000000

                     actual  forecast     lower     upper
created_date
2025-04-04 00:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 01:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 02:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 03:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 04:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 05:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 06:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 07:00:00     0.0  0.000000  0.000000  0.000000
2025-04-04 08:00:00     0.0  0.000000  0.000000  0.000000

,actual,forecast,lower,upper,covered_pts,covered_width
created_date,,,,,,
2025-04-04 00:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 01:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 02:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 03:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 04:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 05:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 06:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 07:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000
2025-04-04 08:00:00,0.0,0.000000,0.000000,0.000000,4,0.000000

{'total_covered': np.int64(36),
 'avg_covered': np.float64(4.0),
 'avg_covered_width': np.float64(0.0)}

orders_metric: 4.0
0.0
0.0

In [47]:
0.5862068965517241*(0.5*0.9405500038466145 + 0.5*0.2901697111945687)

0.36072819233965714

In [44]:
scores[model] = np.sum([weights_acc_df[acc_id] * np.sum(list(df_forecast_metrics_norm[model][acc_id].values())) for acc_id in df_forecast_metrics_norm[model].keys()])

In [45]:
scores

{'GradientBoosting': np.float64(0.5922541434192474)}

In [46]:
df_forecast_metrics_norm

{'GradientBoosting': {'05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6': {3: np.float64(0.36072819233965714),
   6: np.float64(0.16924621616107324),
   5: np.float64(0.04076184212530444),
   1: np.float64(0.0),
   4: np.float64(0.0)},
  'ad942d1a-15ab-4a0d-83a8-ae82183ece53': {1: np.float64(0.36236033167517345),
   2: np.float64(0.5143257184334704),
   3: np.float64(0.0)},
  '4f1c8b04-eb4b-4887-8c69-a096f0fda3ab': {1: np.float64(0.4614813414916191),
   2: np.float64(0.22840153197905375)}}}