In [ ]:
import os
import sys

sys.stderr = open(os.devnull, "w")

import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import psycopg2
import pytz
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from sktime.forecasting.tbats import TBATS
from sklearn.utils import resample
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, root_mean_squared_error
from keras.callbacks import EarlyStopping
from keras.models import Sequential
from keras.layers import Input, Dense, LSTM, Dropout

warnings.filterwarnings('ignore', category=FutureWarning)

tf.random.set_seed(42)
np.random.seed(42)

/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
def calculate_prediction_intervals(y_test, forecast, confidence_level=0.95, n_bootstrap=1000):
    """
    Calculate prediction intervals using bootstrapping.

    Parameters:
    - y_test: pandas.Series, actual test values
    - forecast: pandas.Series, forecasted values
    - confidence_level: float, confidence level for prediction interval (e.g., 0.95 for 95%)
    - n_bootstrap: int, number of bootstrap samples

    Returns:
    - lower_bound: pandas.Series, lower bound of prediction interval
    - upper_bound: pandas.Series, upper bound of prediction interval
    """
    # Step 3: Calculate residuals
    residuals = y_test - forecast

    # Step 4: Bootstrapping
    bootstrap_samples = []
    for _ in range(n_bootstrap):
        sample_residuals = np.random.choice(residuals, size=len(residuals), replace=True)
        bootstrap_forecast = forecast + sample_residuals
        bootstrap_samples.append(bootstrap_forecast)

    # Step 6: Calculate prediction intervals
    lower_percentile = (1 - confidence_level) / 2 * 100
    upper_percentile = (1 + confidence_level) / 2 * 100
    forecast_lower = pd.Series(np.percentile(bootstrap_samples, lower_percentile, axis=0), index=y_test.index)
    forecast = pd.Series(np.percentile(bootstrap_samples, 50, axis=0), index=y_test.index)
    forecast_upper = pd.Series(np.percentile(bootstrap_samples, upper_percentile, axis=0), index=y_test.index)

    return forecast_lower, forecast, forecast_upper

In [3]:
# def calculate_oot_gb_prediction_intervals(df, X_oot, oot_gb, target_column='price_total_agg', confidence_level=0.95, n_bootstrap=1000):
#     """
#     Calculate OOT prediction intervals for out-of-time data.

#     Parameters:
#     - df: pandas.DataFrame, training data containing features and target
#     - X_oot: pandas.DataFrame, out-of-time features
#     - oot_gb: OOT model
#     - target_column: str, name of the target column in df (default: 'price_total_agg')
#     - n_bootstrap: int, number of bootstrap samples (default: 1000)
#     - confidence_level: float, confidence level for prediction interval (default: 0.95)

#     Returns:
#     - oot_gb_forecast_lower: pandas.Series, lower bound of prediction interval
#     - oot_gb_forecast: pandas.Series, median forecast
#     - oot_gb_forecast_upper: pandas.Series, upper bound of prediction interval
#     """
#     # Calculate percentiles based on confidence level
#     lower_percentile = (1 - confidence_level) / 2 * 100
#     upper_percentile = (1 + confidence_level) / 2 * 100

#     bootstrap_predictions = []
#     for _ in range(n_bootstrap):
#         # Generate bootstrap sample
#         df_boot = resample(df)
#         # X_boot = scaler.fit_transform(df_boot.drop(columns=[target_column]))
#         # X_boot = np.reshape(X_boot, (X_boot.shape[0], 1, X_boot.shape[1]))
#         X_boot = df_boot.drop(columns=[target_column])
#         y_boot = df_boot[target_column]
        
#         # Train a new model on the bootstrap sample
#         oot_boot_gb = oot_gb
#         oot_boot_gb.fit(X_boot, y_boot)
        
#         # Generate predictions from the bootstrap model
#         # X_oot_scaled = scaler.transform(X_oot)
#         # X_oot_scaled = np.reshape(X_oot_scaled, (X_oot_scaled.shape[0], 1, X_oot_scaled.shape[1]))
#         bootstrap_pred = oot_boot_gb.predict(X_oot)
#         bootstrap_predictions.append(bootstrap_pred)

#     # Calculate lower and upper bounds for the prediction intervals
#     bootstrap_predictions = np.array(bootstrap_predictions)
#     oot_gb_forecast_lower = pd.Series(np.percentile(bootstrap_predictions, lower_percentile, axis=0), index=X_oot.index)
#     oot_gb_forecast = pd.Series(np.percentile(bootstrap_predictions, 50, axis=0), index=X_oot.index)
#     oot_gb_forecast_upper = pd.Series(np.percentile(bootstrap_predictions, upper_percentile, axis=0), index=X_oot.index)

#     return oot_gb_forecast_lower, oot_gb_forecast, oot_gb_forecast_upper

In [4]:
# def calculate_oot_lstm_prediction_intervals(df, X_oot, oot_lstm, target_column='price_total_agg', confidence_level=0.95, n_bootstrap=1000):
#     """
#     Calculate OOT prediction intervals for out-of-time data.

#     Parameters:
#     - df: pandas.DataFrame, training data containing features and target
#     - X_oot: pandas.DataFrame, out-of-time features
#     - oot_lstm: OOT model
#     - target_column: str, name of the target column in df (default: 'price_total_agg')
#     - n_bootstrap: int, number of bootstrap samples (default: 1000)
#     - confidence_level: float, confidence level for prediction interval (default: 0.95)

#     Returns:
#     - oot_lstm_forecast_lower: pandas.Series, lower bound of prediction interval
#     - oot_lstm_forecast: pandas.Series, median forecast
#     - oot_lstm_forecast_upper: pandas.Series, upper bound of prediction interval
#     """
#     # Calculate percentiles based on confidence level
#     lower_percentile = (1 - confidence_level) / 2 * 100
#     upper_percentile = (1 + confidence_level) / 2 * 100

#     bootstrap_predictions = []
#     for _ in range(n_bootstrap):
#         # Generate bootstrap sample
        
#         scaler = StandardScaler()
        
#         df_boot = resample(df)
#         X_boot = scaler.fit_transform(df_boot.drop(columns=[target_column]))
#         X_boot = np.reshape(X_boot, (X_boot.shape[0], 1, X_boot.shape[1]))
#         y_boot = df_boot[target_column]
        
#         # Train a new model on the bootstrap sample
#         oot_boot_lstm = oot_lstm
#         oot_boot_lstm.fit(X_boot, y_boot)
        
#         # Generate predictions from the bootstrap model
#         X_oot_scaled = scaler.transform(X_oot)
#         X_oot_scaled = np.reshape(X_oot_scaled, (X_oot_scaled.shape[0], 1, X_oot_scaled.shape[1]))
#         bootstrap_pred = oot_boot_lstm.predict(X_oot_scaled)
#         bootstrap_predictions.append(bootstrap_pred)

#     # Calculate lower and upper bounds for the prediction intervals
#     bootstrap_predictions = np.array(bootstrap_predictions).squeeze()
#     oot_lstm_forecast_lower = pd.Series(np.percentile(bootstrap_predictions, lower_percentile, axis=0), index=X_oot.index)
#     oot_lstm_forecast = pd.Series(np.percentile(bootstrap_predictions, 50, axis=0), index=X_oot.index)
#     oot_lstm_forecast_upper = pd.Series(np.percentile(bootstrap_predictions, upper_percentile, axis=0), index=X_oot.index)

#     return oot_lstm_forecast_lower, oot_lstm_forecast, oot_lstm_forecast_upper

In [5]:
def calculate_oot_lr_prediction_intervals(df, X_oot, X_oot_gb, X_oot_lstm, target_column='price_total_agg', confidence_level=0.95, n_bootstrap=1000, epochs=1000, batch_size=32, validation_split=0.1):
    """
    Calculate OOT prediction intervals for out-of-time data.

    Parameters:
    - df: pandas.DataFrame, training data containing features and target
    - X_oot: pandas.DataFrame, out-of-time features
    - oot_lr: OOT model
    - target_column: str, name of the target column in df (default: 'price_total_agg')
    - n_bootstrap: int, number of bootstrap samples (default: 1000)
    - confidence_level: float, confidence level for prediction interval (default: 0.95)

    Returns:
    - oot_lr_forecast_lower: pandas.Series, lower bound of prediction interval
    - oot_lr_forecast: pandas.Series, median forecast
    - oot_lr_forecast_upper: pandas.Series, upper bound of prediction interval
    """
    # Calculate percentiles based on confidence level
    lower_percentile = (1 - confidence_level) / 2 * 100
    upper_percentile = (1 + confidence_level) / 2 * 100

    bootstrap_predictions = []
    for _ in range(n_bootstrap):
        # Generate bootstrap sample
        df_boot = resample(df).sort_index(ascending=True)
        df_boot.index = df.index
        X_boot = df_boot.drop(columns=[target_column])
        y_boot = df_boot[target_column]
        
        scaler = StandardScaler()
        X_boot_scaled = scaler.fit_transform(X_boot)
        X_boot_scaled = np.reshape(X_boot_scaled, (X_boot_scaled.shape[0], 1, X_boot_scaled.shape[1]))
        
        # oot_boot_tbats = TBATS(sp=[24, 168], show_warnings=False, n_jobs=-1)
        oot_boot_tbats = TBATS(sp=24, show_warnings=False, n_jobs=-1)
        oot_boot_tbats.fit(y_boot)
        
        gscv = GridSearchCV(GradientBoostingRegressor(random_state=42, n_iter_no_change=3),
                            param_grid={'max_depth': [1, 2, 4, 8, 16],
                                        'subsample': [0.2, 0.4, 0.6, 0.8, 1],
                                        'max_features': ['sqrt', 'log2', None]},
                            scoring='neg_root_mean_squared_error',
                            cv=TimeSeriesSplit(),
                            n_jobs=-1,
                            verbose=1)
        gscv.fit(X_boot, y_boot)
        oot_boot_gb = gscv.best_estimator_
        
        early_stopping = EarlyStopping(patience=3)
        oot_boot_lstm = Sequential()
        oot_boot_lstm.add(Input(shape=(1, 24)))
        oot_boot_lstm.add(LSTM(128, activation='relu', return_sequences=True))
        oot_boot_lstm.add(Dropout(0.5))
        oot_boot_lstm.add(Dense(1))
        oot_boot_lstm.compile(loss='mean_squared_error', optimizer='adam')
        oot_boot_lstm.fit(X_boot_scaled, y_boot, epochs=epochs, batch_size=batch_size, validation_split=validation_split, shuffle=False, callbacks=early_stopping, verbose=2)
        
        oot_tbats_estimations = pd.Series(oot_boot_tbats.predict(fh=X_boot.index), index=X_boot.index)
        oot_gb_estimations = pd.Series(oot_boot_gb.predict(X_boot), index=X_boot.index)
        oot_lstm_estimations = pd.Series(oot_boot_lstm.predict(X_boot_scaled).squeeze(), index=X_boot.index)
        
        oot_estimations = pd.concat([oot_tbats_estimations, oot_gb_estimations, oot_lstm_estimations], axis=1)
        oot_estimations.columns = ['tbats', 'gb', 'lstm']
        
        # Train a new model on the bootstrap sample
        oot_lr = Ridge()
        oot_lr.fit(oot_estimations, y_boot)
        
        # Generate predictions from the bootstrap model
        bootstrap_tbats_pred = oot_boot_tbats.predict(fh=X_oot.index)
        bootstrap_gb_pred = pd.Series(oot_boot_gb.predict(X_oot_gb), index=X_oot.index)
        X_oot_scaled = scaler.transform(X_oot_lstm)
        X_oot_scaled = np.reshape(X_oot_scaled, (X_oot_scaled.shape[0], 1, X_oot_scaled.shape[1]))
        bootstrap_lstm_pred = pd.Series(oot_boot_lstm.predict(X_oot_scaled).squeeze(), index=X_oot.index)

        oot_bootstrap_forecast = pd.concat([bootstrap_tbats_pred, bootstrap_gb_pred, bootstrap_lstm_pred], axis=1)
        oot_bootstrap_forecast.columns = ['tbats', 'gb', 'lstm']
        
        bootstrap_forecast = pd.Series(oot_lr.predict(oot_bootstrap_forecast), index=X_oot.index)
        bootstrap_predictions.append(bootstrap_forecast)

    # Calculate lower and upper bounds for the prediction intervals
    bootstrap_predictions = np.array(bootstrap_predictions)
    oot_lr_forecast_lower = pd.Series(np.percentile(bootstrap_predictions, lower_percentile, axis=0), index=X_oot.index)
    oot_lr_forecast = pd.Series(np.percentile(bootstrap_predictions, 50, axis=0), index=X_oot.index)
    oot_lr_forecast_upper = pd.Series(np.percentile(bootstrap_predictions, upper_percentile, axis=0), index=X_oot.index)

    return oot_lr_forecast_lower, oot_lr_forecast, oot_lr_forecast_upper

In [6]:
sales = pd.read_csv('pedidos-1743765883268.csv', sep=';', encoding='latin1')

In [7]:
df = sales[['account_id', 'sales_channel_id']].value_counts()
df = pd.DataFrame(df).reset_index()

In [8]:
EPOCHS = 1000
BATCH_SIZE = 32
VALID_SPLIT = 0.1

In [9]:
SAO_PAULO_TZ = pytz.timezone('America/Sao_Paulo')
LOOKBACK = 1
SEASONAL_PERIODS = [24, 24*7]
END_DATE = pd.to_datetime(pd.to_datetime(sales['created_date'].max()).strftime("%Y-%m-%d %H:00:00"))
# START_DATE = END_DATE - timedelta(hours=END_DATE.hour)
START_DATE = END_DATE - timedelta(hours=23)
TEST_SIZE = int((END_DATE - START_DATE).seconds / 60**2 + 1)

In [10]:
# OOT_DATE = START_DATE + timedelta(hours=23)

In [11]:
# OOT_PERIODS = int((OOT_DATE - END_DATE).seconds / 60**2 + 1)

In [12]:
# oot_dates = pd.DatetimeIndex([END_DATE+timedelta(hours=h) for h in range(1, OOT_PERIODS)], freq='h')
# df_oot = pd.DataFrame(index=oot_dates)

In [13]:
# df.drop('count', axis=1, inplace=True)
# for account_id in df['account_id'].unique():
#     df = pd.concat([df, pd.DataFrame({'account_id': [account_id], 'sales_channel_id': ['ALL']})], ignore_index=True)

In [14]:
df

                               account_id  sales_channel_id    count
0    5f5ed10c-7792-4080-970c-b11398e3f58f                 1  3004186
1    9d39683a-47b3-4a18-942d-f1d741a47e8c                 1  2542841
2    05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6                 3  1908829
3    5f5ed10c-7792-4080-970c-b11398e3f58f                 9  1057418
4    74abffac-6542-4eff-8eae-cc85463a5d02                 1   986953
..                                    ...               ...      ...
272  60ca8452-5b14-481f-a637-8756f527aee8                 4        2
273  f9129295-bb08-4330-b60c-9f0beadda521                36        1
274  789ff5c4-21d8-4ed3-ab64-8b46cf2eba9b                 2        1
275  457bce7b-9300-4c10-9a97-070b3c0d081d                 5        1
276  b8c6ac4b-2999-40f4-ad33-17649fb2f0aa                10        1

[277 rows x 3 columns]

In [15]:
df[df['account_id'] == '423a069b-27b8-44ed-9ef3-ca3cf9470970']

                               account_id  sales_channel_id  count
67   423a069b-27b8-44ed-9ef3-ca3cf9470970                 1  17714
71   423a069b-27b8-44ed-9ef3-ca3cf9470970                 2  15934
180  423a069b-27b8-44ed-9ef3-ca3cf9470970                 3    586

In [16]:
account_ids = ['f9129295-bb08-4330-b60c-9f0beadda521', '05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '9d39683a-47b3-4a18-942d-f1d741a47e8c']

df_filtered = df[df['account_id'].isin(account_ids)]

In [17]:
df_filtered

                               account_id  sales_channel_id    count
1    9d39683a-47b3-4a18-942d-f1d741a47e8c                 1  2542841
2    05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6                 3  1908829
5    05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6                 6   876335
7    f9129295-bb08-4330-b60c-9f0beadda521                 1   486716
11   f9129295-bb08-4330-b60c-9f0beadda521                 2   321190
15   05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6                 5   263987
29   f9129295-bb08-4330-b60c-9f0beadda521                10   106300
48   f9129295-bb08-4330-b60c-9f0beadda521                38    47359
51   f9129295-bb08-4330-b60c-9f0beadda521                16    41229
55   f9129295-bb08-4330-b60c-9f0beadda521                18    29153
63   05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6                 1    20307
64   f9129295-bb08-4330-b60c-9f0beadda521                17    20111
86   f9129295-bb08-4330-b60c-9f0beadda521                 6    10374
88   f9129295-bb08-4330-b60c-9f0beadda521                22     9553
97   f9129295-bb08-4330-b60c-9f0beadda521                20     8467
105  f9129295-bb08-4330-b60c-9f0beadda521                31     6540
109  f9129295-bb08-4330-b60c-9f0beadda521                15     6072
110  f9129295-bb08-4330-b60c-9f0beadda521                43     5862
114  f9129295-bb08-4330-b60c-9f0beadda521                21     4857
116  f9129295-bb08-4330-b60c-9f0beadda521                39     4115
126  f9129295-bb08-4330-b60c-9f0beadda521                33     3209
137  f9129295-bb08-4330-b60c-9f0beadda521                32     2152
145  f9129295-bb08-4330-b60c-9f0beadda521                26     1769
146  f9129295-bb08-4330-b60c-9f0beadda521                19     1769
147  f9129295-bb08-4330-b60c-9f0beadda521                27     1757
148  f9129295-bb08-4330-b60c-9f0beadda521                 7     1654
156  f9129295-bb08-4330-b60c-9f0beadda521                34     1402
164  f9129295-bb08-4330-b60c-9f0beadda521                 3     1167
173  f9129295-bb08-4330-b60c-9f0beadda521                42      848
179  f9129295-bb08-4330-b60c-9f0beadda521                35      595
192  f9129295-bb08-4330-b60c-9f0beadda521                 4      388
195  f9129295-bb08-4330-b60c-9f0beadda521                11      352
197  f9129295-bb08-4330-b60c-9f0beadda521                24      339
207  f9129295-bb08-4330-b60c-9f0beadda521                13      211
208  f9129295-bb08-4330-b60c-9f0beadda521                29      207
233  f9129295-bb08-4330-b60c-9f0beadda521                25       60
235  9d39683a-47b3-4a18-942d-f1d741a47e8c                 2       40
243  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6                 4       24
245  f9129295-bb08-4330-b60c-9f0beadda521                 5       20
251  f9129295-bb08-4330-b60c-9f0beadda521                 8       14
273  f9129295-bb08-4330-b60c-9f0beadda521                36        1

In [18]:
dbname = 'railway'
username = 'sinatra'
pwd = '781B3XjpeuqE'
hostname = 'monorail.proxy.rlwy.net'
port = 25096

connection = psycopg2.connect(database=dbname, user=username, password=pwd, host=hostname, port=port)
cursor = connection.cursor()

In [19]:
cursor.execute("select distinct account_id, channel from public.forecast where model='Ensemble_10';")

In [20]:
res_forecast = cursor.fetchall()

In [21]:
len(res_forecast)

0

In [ ]:
id_pairs = list(zip(df_filtered['account_id'], df_filtered['sales_channel_id']))
# id_pairs = list(zip(df['account_id'], df['sales_channel_id']))
summary_dict = {}
forecast_dict = {}
for coverage in [n*10**-1 for n in range(1, 10)]:
    for account_id, sales_channel_id in id_pairs:
        
        if (account_id, str(sales_channel_id)) in res_forecast:
            continue

        print(f'account_id: {account_id}')
        print(f'sales_channel_id: {sales_channel_id}')
        
        summary_dict[(account_id, sales_channel_id)] = {}
        
        if sales_channel_id == 'ALL':
            cond = (sales['account_id'] == account_id) & \
                   (sales['status'].notna())
        else:
            cond = (sales['account_id'] == account_id) & \
                   (sales['sales_channel_id'] == int(sales_channel_id)) & \
                   (sales['status'].notna())
        
        df_client = sales[cond].drop(['account_id', 'sales_channel_id'], axis=1)
        df_client['created_date'] = pd.to_datetime(df_client['created_date'], format='%Y-%m-%d %H:%M:%S.%f %z')
        df_client = df_client.sort_values('created_date').reset_index(drop=True)
        df_client['created_date'] = df_client['created_date'].dt.strftime("%Y-%m-%d %H:00:00").reset_index(drop=True)
        
        df_client_mod = df_client.groupby('created_date').agg(price_total_agg=('price_total', 'sum'), n_orders=('created_date', 'count'))
        df_client_mod.index = pd.to_datetime(df_client_mod.index, format='%Y-%m-%d %H:00:00')
        
        end_date = pd.to_datetime(END_DATE, format='%Y-%m-%d %H:%M:%S')
        start_date = end_date - relativedelta(months=LOOKBACK)
        date_index = pd.Series(pd.date_range(start=start_date, end=end_date, freq='h', name='created_date'))
        df_client_mod = pd.merge(date_index, df_client_mod, how='left', on='created_date').set_index('created_date')
        
        # oot_date_index = pd.Series(df_oot.index, name='created_date')
        # combined_date_index = pd.concat([date_index, oot_date_index], axis=0)
        # df_client_mod = pd.merge(combined_date_index, df_client_mod, how='left', on='created_date').set_index('created_date')
        
        forecast_dict[account_id] = {} if account_id not in forecast_dict else forecast_dict[account_id]
        forecast_dict[account_id][sales_channel_id] = {}
        
        for n, col in enumerate(['price_total_agg', 'n_orders']):
            print(col)
            
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}'] = {}
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}']['name'] = col
            
            forecast_dict[account_id][sales_channel_id][f'dataset_{n}'] = {}
            
            df = df_client_mod[col]
            
            df.fillna(0, inplace=True)
            
            lags = [df.shift(l).rename(f'lag_{l}') for l in range(1, 25)]
            df_lag = pd.concat([df, pd.concat(lags, axis=1)], axis=1).dropna().asfreq('h')
            
            # df = df_lag.loc[df_lag.index <= END_DATE].copy()
            df_train = df_lag.loc[df_lag.index < START_DATE].copy()
            df_test = df_lag.loc[(df_lag.index >= START_DATE) & (df_lag.index <= END_DATE)].copy()
            # df_oot = df_lag.loc[df_lag.index > END_DATE].copy()
            
            # X, y = df.iloc[:, 1:], df.iloc[:, 0]
            X_train, y_train = df_train.iloc[:, 1:], df_train.iloc[:, 0]
            X_test, y_test = df_test.iloc[:, 1:], df_test.iloc[:, 0]
            # X_oot = df_oot.iloc[:, 1:]
            
            # tbats = TBATS(sp=[24, 168], show_warnings=False, n_jobs=-1)
            tbats = TBATS(sp=24, show_warnings=False, n_jobs=-1)
            tbats.fit(y_train)
            
            gscv = GridSearchCV(GradientBoostingRegressor(random_state=42, n_iter_no_change=3),
                                param_grid={'max_depth': [1, 2, 4, 8, 16],
                                            'subsample': [0.2, 0.4, 0.6, 0.8, 1],
                                            'max_features': ['sqrt', 'log2', None]},
                                scoring='neg_root_mean_squared_error',
                                cv=TimeSeriesSplit(),
                                n_jobs=-1,
                                verbose=1)
            gscv.fit(X_train, y_train)
            gb = gscv.best_estimator_
            
            tbats_estimations = tbats.predict(fh=X_train.index)
            gb_estimations = pd.Series(gb.predict(X_train), index=X_train.index)
            
            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            # X_test_scaled = lstm_scaler.transform(X_test)
            
            X_train_scaled = np.reshape(X_train_scaled, (X_train.shape[0], 1, X_train.shape[1]))
            # X_test_scaled = np.reshape(X_test_scaled, (X_test.shape[0], 1, X_test.shape[1]))
            
            early_stopping = EarlyStopping(patience=3)
            lstm = Sequential()
            lstm.add(Input(shape=(1, 24)))
            lstm.add(LSTM(128, activation='relu', return_sequences=True))
            lstm.add(Dropout(0.5))
            lstm.add(Dense(1))
            lstm.compile(loss='mean_squared_error', optimizer='adam')
            lstm.fit(X_train_scaled, y_train, epochs=EPOCHS, batch_size=BATCH_SIZE, validation_split=VALID_SPLIT, shuffle=False, callbacks=early_stopping, verbose=2)
            
            lstm_estimations = pd.Series(lstm.predict(X_train_scaled).squeeze(), index=X_train.index)
            
            models_estimations = pd.concat([tbats_estimations, gb_estimations, lstm_estimations], axis=1)
            models_estimations.columns = ['tbats', 'gb', 'lstm']
            lr = Ridge()
            lr.fit(models_estimations, y_train)
            estimations = pd.Series(lr.predict(models_estimations), index=X_train.index)
            
            display(pd.DataFrame(lr.coef_, index=models_estimations.columns, columns=['coef']))
            
            train_mae = mean_absolute_error(y_train, estimations)
            train_rmse = root_mean_squared_error(y_train, estimations)
            
            print(f"train RMSE: {train_rmse:.3f}")
            print(f"train MAE:  {train_mae:.3f}")
            
            # tbats_forecast = tbats.predict(fh=X_test.index)
            # tbats_forecast_int = tbats.predict_interval(fh=X_test.index, coverage=coverage)
            # tbats_forecast_lower = tbats_forecast_int.iloc[:, 0]
            # tbats_forecast_upper = tbats_forecast_int.iloc[:, 1]
            
            # gb_forecast = pd.Series(gb.predict(X_test), index=X_test.index)
            # gb_forecast_lower, gb_forecast, gb_forecast_upper = calculate_prediction_intervals(y_test, gb_forecast, confidence_level=coverage, n_bootstrap=300)
            
            # lstm_forecast = pd.Series(lstm.predict(X_test_scaled).squeeze(), index=X_test.index)
            # lstm_forecast_lower, lstm_forecast, lstm_forecast_upper = calculate_prediction_intervals(y_test, lstm_forecast, confidence_level=coverage, n_bootstrap=300)
            
            # models_forecast = pd.concat([tbats_forecast, gb_forecast, lstm_forecast], axis=1)
            # models_forecast.columns = ['tbats', 'gb', 'lstm']
            
            # models_forecast_lower = pd.concat([tbats_forecast_lower, gb_forecast_lower, lstm_forecast_lower], axis=1)
            # models_forecast_upper = pd.concat([tbats_forecast_upper, gb_forecast_upper, lstm_forecast_upper], axis=1)
            
            # forecast = pd.Series(lr.predict(models_forecast), index=X_test.index)
            # forecast_lower, forecast, forecast_upper = calculate_prediction_intervals(y_test, forecast, confidence_level=coverage, n_bootstrap=300)
            
            # forecast = pd.Series(lr.predict(models_forecast), index=X_test.index)
            # forecast_lower = pd.Series(lr.predict(models_forecast_lower), index=X_test.index)
            # forecast_upper = pd.Series(lr.predict(models_forecast_upper), index=X_test.index)
            
            # test_mae = mean_absolute_error(y_test, forecast)
            # test_rmse = root_mean_squared_error(y_test, forecast)

            # print(f"test RMSE: {test_rmse:.3f}")
            # print(f"test MAE:  {test_mae:.3f}")
            
            # forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['forecast'] = forecast
            # forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['forecast_lower'] = forecast_lower
            # forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['forecast_upper'] = forecast_upper
            
            # oot_tbats = TBATS(sp=[24, 168], show_warnings=False, n_jobs=-1)
            # oot_tbats.fit(y)
            
            # # oot_tbats_forecast = oot_tbats.predict(fh=X_oot.index)
            # # oot_tbats_forecast_int = oot_tbats.predict_interval(fh=X_oot.index, coverage=coverage)
            # # oot_tbats_forecast_lower = oot_tbats_forecast_int.iloc[:, 0]
            # # oot_tbats_forecast_upper = oot_tbats_forecast_int.iloc[:, 1]
            
            # oot_gscv = GridSearchCV(GradientBoostingRegressor(loss="quantile", alpha=0.5, random_state=42, n_iter_no_change=3),
            #                         param_grid={'max_depth': [1, 2, 4, 8, 16],
            #                                     'subsample': [0.2, 0.4, 0.6, 0.8, 1],
            #                                     'max_features': ['sqrt', 'log2', None]},
            #                         scoring='neg_mean_absolute_error',
            #                         cv=TimeSeriesSplit(),
            #                         n_jobs=-1,
            #                         verbose=1)        
            # oot_gscv.fit(X, y)
            # oot_gb = oot_gscv.best_estimator_
            
            # scaler = StandardScaler()
            # X_scaled = np.reshape(scaler.fit_transform(X), (X.shape[0], 1, X.shape[1]))
            
            # early_stopping = EarlyStopping(patience=3)
            # oot_lstm = Sequential()
            # oot_lstm.add(Input(shape=(1, 24)))
            # oot_lstm.add(LSTM(128, activation='relu', return_sequences=True))
            # oot_lstm.add(Dropout(0.5))
            # oot_lstm.add(Dense(1))
            # oot_lstm.compile(loss='mean_absolute_error', optimizer='adam')
            # oot_lstm.fit(X_scaled, y, epochs=EPOCHS, batch_size=BATCH_SIZE, validation_split=VALID_SPLIT, shuffle=False, callbacks=early_stopping, verbose=2)
            
            # oot_tbats_estimations = pd.Series(oot_tbats.predict(fh=X.index), index=X.index)
            # oot_gb_estimations = pd.Series(oot_gb.predict(X), index=X.index)
            # oot_lstm_estimations = pd.Series(oot_lstm.predict(X_scaled).squeeze(), index=X.index)
            
            # oot_estimations = pd.concat([oot_tbats_estimations, oot_gb_estimations, oot_lstm_estimations], axis=1)
            # oot_estimations.columns = ['tbats', 'gb', 'lstm']
            # oot_lr = Ridge()
            # oot_lr.fit(oot_estimations, y)
            
            # display(pd.DataFrame(zip(oot_lr.feature_names_in_, oot_lr.coef_), columns=['feature', 'coef']))
            
            # oot_gb_forecast_ls = []
            # oot_gb_forecast_lower_ls = []
            # oot_gb_forecast_upper_ls = []
            # oot_lstm_forecast_ls = []
            # oot_lstm_forecast_lower_ls = []
            # oot_lstm_forecast_upper_ls = []
            
            # X_oot_gb = X_oot.copy()
            # X_oot_lstm = X_oot.copy()
            # for i in range(len(X_oot)):
            #     x_oot_gb = X_oot_gb.iloc[i].to_frame().T
                
            #     x_oot_lstm = X_oot_lstm.iloc[i].to_frame().T
            #     x_oot_lstm_scaled = scaler.transform(x_oot_lstm)
            #     x_oot_lstm_scaled = np.reshape(x_oot_lstm_scaled, (x_oot_lstm.shape[0], 1, x_oot_lstm.shape[1]))
                
            #     x_oot_gb_forecast = oot_gb.predict(x_oot_gb)[0]
                
            #     x_oot_lstm_forecast = oot_lstm.predict(x_oot_lstm_scaled).squeeze()
                
            #     for j, k in list(zip(range(i+1, len(X_oot)), range(len(X_oot)-i-1))):
            #         X_oot_gb.iloc[j, k] = x_oot_gb_forecast
            #         X_oot_lstm.iloc[j, k] = x_oot_lstm_forecast
                    
            X_oot_gb = X_test.copy()
            X_oot_lstm = X_test.copy()
            # for i in range(len(X_oot)):
            for i in range(len(X_test)):
                x_oot_gb = X_oot_gb.iloc[i].to_frame().T
                
                x_oot_lstm = X_oot_lstm.iloc[i].to_frame().T
                x_oot_lstm_scaled = scaler.transform(x_oot_lstm)
                x_oot_lstm_scaled = np.reshape(x_oot_lstm_scaled, (x_oot_lstm.shape[0], 1, x_oot_lstm.shape[1]))
                
                # x_oot_gb_forecast = oot_gb.predict(x_oot_gb)[0]
                x_oot_gb_forecast = gb.predict(x_oot_gb)[0]
                
                # x_oot_lstm_forecast = oot_lstm.predict(x_oot_lstm_scaled).squeeze()
                x_oot_lstm_forecast = lstm.predict(x_oot_lstm_scaled).squeeze()
                
                # for j, k in list(zip(range(i+1, len(X_oot)), range(len(X_oot)-i-1))):
                for j, k in list(zip(range(i+1, len(X_test)), range(len(X_test)-i-1))):
                    X_oot_gb.iloc[j, k] = x_oot_gb_forecast
                    X_oot_lstm.iloc[j, k] = x_oot_lstm_forecast
            
            # oot_gb_forecast_lower, oot_gb_forecast, oot_gb_forecast_upper = calculate_oot_gb_prediction_intervals(df, X_oot_gb, oot_gb, target_column=col, confidence_level=coverage, n_bootstrap=300)
            # oot_gb_forecast = pd.Series(oot_gb_forecast, index=X_oot.index)
            # oot_gb_forecast_lower = pd.Series(oot_gb_forecast_lower, index=X_oot.index)
            # oot_gb_forecast_upper = pd.Series(oot_gb_forecast_upper, index=X_oot.index)
            
            # oot_lstm_forecast_lower, oot_lstm_forecast, oot_lstm_forecast_upper = calculate_oot_lstm_prediction_intervals(df, X_oot_lstm, oot_lstm, target_column=col, confidence_level=coverage, n_bootstrap=300)
            # oot_lstm_forecast = pd.Series(oot_lstm_forecast, index=X_oot.index)
            # oot_lstm_forecast_lower = pd.Series(oot_lstm_forecast_lower, index=X_oot.index)
            # oot_lstm_forecast_upper = pd.Series(oot_lstm_forecast_upper, index=X_oot.index)
            
            # oot_models_forecast = pd.concat([oot_tbats_forecast, oot_gb_forecast, oot_lstm_forecast], axis=1)
            # oot_models_forecast.columns = ['tbats', 'gb', 'lstm']
            
            # oot_models_forecast_lower = pd.concat([oot_tbats_forecast_lower, oot_gb_forecast_lower, oot_lstm_forecast_lower], axis=1)
            # oot_models_forecast_upper = pd.concat([oot_tbats_forecast_upper, oot_gb_forecast_upper, oot_lstm_forecast_upper], axis=1)
            
            # oot_forecast = pd.Series(oot_lr.predict(oot_models_forecast), index=X_oot.index)
            # oot_forecast_lower = pd.Series(oot_lr.predict(oot_models_forecast_lower), index=X_oot.index)
            # oot_forecast_upper = pd.Series(oot_lr.predict(oot_models_forecast_upper), index=X_oot.index)
            
            # oot_forecast_lower, oot_forecast, oot_forecast_upper = calculate_oot_lr_prediction_intervals(df, X_oot, oot_tbats, oot_gb, oot_lstm, target_column=col, confidence_level=coverage, n_bootstrap=300)
            forecast_lower, forecast, forecast_upper = calculate_oot_lr_prediction_intervals(df_train, X_test, X_oot_gb, X_oot_lstm, target_column=col, confidence_level=coverage, n_bootstrap=10, epochs=EPOCHS, batch_size=BATCH_SIZE, validation_split=VALID_SPLIT)
            
            test_mae = mean_absolute_error(y_test, forecast)
            test_rmse = root_mean_squared_error(y_test, forecast)

            print(f"test RMSE: {test_rmse:.3f}")
            print(f"test MAE:  {test_mae:.3f}")
            
            # forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['oot_forecast'] = oot_forecast
            # forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['oot_forecast_lower'] = oot_forecast_lower
            # forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['oot_forecast_upper'] = oot_forecast_upper
            
            forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['forecast'] = forecast
            forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['forecast_lower'] = forecast_lower
            forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['forecast_upper'] = forecast_upper
            
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}']['train RMSE'] = train_rmse
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}']['test RMSE'] = test_rmse
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}']['train MAE'] = train_mae
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}']['test MAE'] = test_mae
            
            plt.figure(figsize=(12, 3))
            sns.lineplot(y_train.iloc[-3*TEST_SIZE:], lw=0.8, label='Train')
            sns.lineplot(estimations.iloc[-3*TEST_SIZE:], lw=0.8, label='Estimation')
            sns.lineplot(y_test, lw=0.8, label='Test', marker='o', markersize=3)
            sns.lineplot(forecast, lw=0.8, label='Forecast')
            sns.lineplot(forecast_lower, c='darkviolet', alpha=0.5, linestyle='--', lw=0.8)
            sns.lineplot(forecast_upper, c='darkviolet', alpha=0.5, linestyle='--', lw=0.8)
            sns.lineplot(2*forecast_lower-forecast, c='darkviolet', alpha=0.3, linestyle='--', lw=0.8)
            sns.lineplot(2*forecast_upper-forecast, c='darkviolet', alpha=0.3, linestyle='--', lw=0.8)
            # sns.lineplot(oot_forecast, lw=0.8, label='OOT Forecast')
            # sns.lineplot(oot_forecast_lower, c='darkviolet', linestyle='--', lw=0.8)
            # sns.lineplot(oot_forecast_upper, c='darkviolet', linestyle='--', lw=0.8)
            plt.fill_between(x=forecast.index,
                             y1=forecast_lower,
                             y2=forecast_upper,
                             color='violet',
                             alpha=0.5)
            plt.fill_between(x=forecast.index,
                             y1=2*forecast_lower-forecast,
                             y2=2*forecast_upper-forecast,
                             color='violet',
                             alpha=0.3)
            # plt.fill_between(x=oot_forecast.index,
            #                 y1=oot_forecast_lower,
            #                 y2=oot_forecast_upper,
            #                 color='violet',
            #                 alpha=0.5)
            plt.legend()
            plt.savefig(f'plots/ensemble/forecast_{account_id}_{sales_channel_id}_{col}_ens.png')
            plt.show();
        
        # with open(f'sql/ensemble/forecast_{account_id}_{sales_channel_id}_ens.sql', 'w') as output_file:
        #     pt_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_lower']
        #     pt_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_upper']
        #     pt_forecast = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast']
            
        #     no_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_lower']
        #     no_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_upper']
        #     no_forecast = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast']
        #     for i in range(len(df_test)):
        #         start_time = df_test.index[i]
        #         end_time = start_time + pd.Timedelta(hours=1)
        #         output_file.write(
        #             f"""
        #             INSERT INTO forecast (id, created, modified, platform, store_name, "start", "end",
        #                                   channel, seller, account_id, organization_id, store_id, minutes_interval,
        #                                   model, orders_high, orders_low, orders_mean, sales_high, sales_low, sales_mean)
        #             VALUES (gen_random_uuid(), now(), now(), 1, (select vtexid from vtex_account where id = '{account_id}'::uuid), '{start_time}', '{end_time}',
        #                     {sales_channel_id}, 'ALL', '{account_id}'::uuid, (select organizationid from vtex_account where id = '{account_id}'::uuid), NULL, 60, 'Ensemble',
        #                     {no_forecast_upper.iloc[i]}, {no_forecast_lower.iloc[i]}, {no_forecast.iloc[i]},
        #                     {pt_forecast_upper.iloc[i]}, {pt_forecast_lower.iloc[i]}, {pt_forecast.iloc[i]});
        #             """
        #             )
            
        #     pt_oot_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast_lower']
        #     pt_oot_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast_upper']
        #     pt_oot_forecast = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast']
            
        #     no_oot_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast_lower']
        #     no_oot_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast_upper']
        #     no_oot_forecast = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast']
        #     for i in range(len(df_oot)):
        #         start_time = df_oot.index[i]
        #         end_time = start_time + pd.Timedelta(hours=1)
        #         output_file.write(
        #             f"""
        #             INSERT INTO forecast (id, created, modified, platform, store_name, "start", "end",
        #                                   channel, seller, account_id, organization_id, store_id, minutes_interval,
        #                                   model, orders_high, orders_low, orders_mean, sales_high, sales_low, sales_mean)
        #             VALUES (gen_random_uuid(), now(), now(), 1, (select vtexid from vtex_account where id = '{account_id}'::uuid), '{start_time}', '{end_time}',
        #                     {sales_channel_id}, 'ALL', '{account_id}'::uuid, (select organizationid from vtex_account where id = '{account_id}'::uuid), NULL, 60, 'Ensemble',
        #                     {no_oot_forecast_upper.iloc[i]}, {no_oot_forecast_lower.iloc[i]}, {no_oot_forecast.iloc[i]},
        #                     {pt_oot_forecast_upper.iloc[i]}, {pt_oot_forecast_lower.iloc[i]}, {pt_oot_forecast.iloc[i]});
        #             """
        #         )
        
        pt_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_lower']
        pt_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_upper']
        pt_forecast = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast']
        
        no_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_lower']
        no_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_upper']
        no_forecast = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast']
        for i in range(len(df_test)):
            start_time = df_test.index[i]
            end_time = start_time + pd.Timedelta(hours=1)
            start_time = start_time.tz_localize(SAO_PAULO_TZ)
            end_time = end_time.tz_localize(SAO_PAULO_TZ)
            insert = \
                f"""
                INSERT INTO public.forecast (id, created, modified, platform, store_name, "start", "end",
                                            channel, seller, account_id, organization_id, store_id, minutes_interval,
                                            model, orders_high, orders_low, orders_mean, sales_high, sales_low, sales_mean)
                VALUES (gen_random_uuid(), now(), now(), 1, '{account_id}'::uuid, '{start_time}', '{end_time}',
                        '{sales_channel_id}', 'ALL', '{account_id}'::uuid, '{account_id}'::uuid, NULL, 60, 'Ensemble_{int(100*coverage)}',
                        {no_forecast_upper.iloc[i]}, {no_forecast_lower.iloc[i]}, {no_forecast.iloc[i]},
                        {pt_forecast_upper.iloc[i]}, {pt_forecast_lower.iloc[i]}, {pt_forecast.iloc[i]});
                """
            cursor.execute(insert)
        
        # pt_oot_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast_lower']
        # pt_oot_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast_upper']
        # pt_oot_forecast = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast']
        
        # no_oot_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast_lower']
        # no_oot_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast_upper']
        # no_oot_forecast = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast']
        # for i in range(len(df_oot)):
        #     start_time = df_oot.index[i]
        #     end_time = start_time + pd.Timedelta(hours=1)
        #     start_time = start_time.tz_localize(SAO_PAULO_TZ)
        #     end_time = end_time.tz_localize(SAO_PAULO_TZ)
        #     oot_insert = \
        #         f"""
        #         INSERT INTO public.forecast (id, created, modified, platform, store_name, "start", "end",
        #                                     channel, seller, account_id, organization_id, store_id, minutes_interval,
        #                                     model, orders_high, orders_low, orders_mean, sales_high, sales_low, sales_mean)
        #         VALUES (gen_random_uuid(), now(), now(), 1, '{account_id}'::uuid, '{start_time}', '{end_time}',
        #                 '{sales_channel_id}', 'ALL', '{account_id}'::uuid, '{account_id}'::uuid, NULL, 60, 'Ensemble_{int(100*coverage)}',
        #                 {no_oot_forecast_upper.iloc[i]}, {no_oot_forecast_lower.iloc[i]}, {no_oot_forecast.iloc[i]},
        #                 {pt_oot_forecast_upper.iloc[i]}, {pt_oot_forecast_lower.iloc[i]}, {pt_oot_forecast.iloc[i]});
        #         """
        #     cursor.execute(oot_insert)
            
        cursor.execute('commit;')

account_id: 9d39683a-47b3-4a18-942d-f1d741a47e8c
sales_channel_id: 1
price_total_agg
Fitting 5 folds for each of 75 candidates, totalling 375 fits
Epoch 1/1000
20/20 - 1s - 32ms/step - loss: 5670629376.0000 - val_loss: 6372186112.0000
Epoch 2/1000
20/20 - 0s - 3ms/step - loss: 5670552064.0000 - val_loss: 6372057088.0000
Epoch 3/1000
20/20 - 0s - 2ms/step - loss: 5670396928.0000 - val_loss: 6371799040.0000
Epoch 4/1000
20/20 - 0s - 2ms/step - loss: 5670116352.0000 - val_loss: 6371355136.0000
Epoch 5/1000
20/20 - 0s - 2ms/step - loss: 5669651968.0000 - val_loss: 6370698752.0000
Epoch 6/1000
20/20 - 0s - 2ms/step - loss: 5669032448.0000 - val_loss: 6369828352.0000
Epoch 7/1000
20/20 - 0s - 2ms/step - loss: 5668165632.0000 - val_loss: 6368743424.0000
Epoch 8/1000
20/20 - 0s - 2ms/step - loss: 5667212800.0000 - val_loss: 6367455232.0000
Epoch 9/1000
20/20 - 0s - 2ms/step - loss: 5665981440.0000 - val_loss: 6365973504.0000
Epoch 10/1000
20/20 - 0s - 2ms/step - loss: 5664688640.0000 - val_loss: 6364307456.0000
Epoch 11/1000
20/20 - 0s - 2ms/step - loss: 5663081472.0000 - val_loss: 6362448896.0000
Epoch 12/1000
20/20 - 0s - 2ms/step - loss: 5661195776.0000 - val_loss: 6360362496.0000
Epoch 13/1000
20/20 - 0s - 2ms/step - loss: 5659402752.0000 - val_loss: 6358073344.0000
Epoch 14/1000
20/20 - 0s - 2ms/step - loss: 5657252864.0000 - val_loss: 6355579392.0000
Epoch 15/1000
20/20 - 0s - 3ms/step - loss: 5655200768.0000 - val_loss: 6352908800.0000
Epoch 16/1000
20/20 - 0s - 2ms/step - loss: 5652669440.0000 - val_loss: 6350023168.0000
Epoch 17/1000
20/20 - 0s - 2ms/step - loss: 5649842176.0000 - val_loss: 6346921472.0000
Epoch 18/1000
20/20 - 0s - 3ms/step - loss: 5647420416.0000 - val_loss: 6343608320.0000
Epoch 19/1000
20/20 - 0s - 2ms/step - loss: 5644140032.0000 - val_loss: 6340078592.0000
Epoch 20/1000
20/20 - 0s - 2ms/step - loss: 5641343488.0000 - val_loss: 6336346624.0000
Epoch 21/1000
20/20 - 0s - 2ms/step - loss: 5637441536.0000 - val_loss: 6332382208.0000
Epoch 22/1000
20/20 - 0s - 2ms/step - loss: 5634145280.0000 - val_loss: 6328202752.0000
Epoch 23/1000
20/20 - 0s - 2ms/step - loss: 5630417920.0000 - val_loss: 6323837952.0000
Epoch 24/1000
20/20 - 0s - 2ms/step - loss: 5626143232.0000 - val_loss: 6319221760.0000
Epoch 25/1000
20/20 - 0s - 2ms/step - loss: 5622080512.0000 - val_loss: 6314428416.0000
Epoch 26/1000
20/20 - 0s - 3ms/step - loss: 5618797568.0000 - val_loss: 6309464576.0000
Epoch 27/1000
20/20 - 0s - 3ms/step - loss: 5614733312.0000 - val_loss: 6304346624.0000
Epoch 28/1000
20/20 - 0s - 3ms/step - loss: 5609487872.0000 - val_loss: 6298990592.0000
Epoch 29/1000
20/20 - 0s - 2ms/step - loss: 5604590592.0000 - val_loss: 6293415424.0000
Epoch 30/1000
20/20 - 0s - 2ms/step - loss: 5599793664.0000 - val_loss: 6287647232.0000
Epoch 31/1000
20/20 - 0s - 2ms/step - loss: 5594060288.0000 - val_loss: 6281649664.0000
Epoch 32/1000
20/20 - 0s - 2ms/step - loss: 5589341184.0000 - val_loss: 6275518464.0000
Epoch 33/1000
20/20 - 0s - 2ms/step - loss: 5583130112.0000 - val_loss: 6269166080.0000
Epoch 34/1000
20/20 - 0s - 2ms/step - loss: 5578063872.0000 - val_loss: 6262664192.0000
Epoch 35/1000
20/20 - 0s - 2ms/step - loss: 5571291136.0000 - val_loss: 6255936512.0000
Epoch 36/1000
20/20 - 0s - 2ms/step - loss: 5566346240.0000 - val_loss: 6249062400.0000
Epoch 37/1000
20/20 - 0s - 3ms/step - loss: 5559682048.0000 - val_loss: 6242010624.0000
Epoch 38/1000
20/20 - 0s - 2ms/step - loss: 5554060800.0000 - val_loss: 6234830848.0000
Epoch 39/1000
20/20 - 0s - 3ms/step - loss: 5547935232.0000 - val_loss: 6227458048.0000
Epoch 40/1000
20/20 - 0s - 2ms/step - loss: 5541533696.0000 - val_loss: 6219945472.0000
Epoch 41/1000
20/20 - 0s - 3ms/step - loss: 5534598656.0000 - val_loss: 6212264448.0000
Epoch 42/1000
20/20 - 0s - 3ms/step - loss: 5525488640.0000 - val_loss: 6204305408.0000
Epoch 43/1000
20/20 - 0s - 2ms/step - loss: 5522031104.0000 - val_loss: 6196248576.0000
Epoch 44/1000
20/20 - 0s - 2ms/step - loss: 5512999424.0000 - val_loss: 6188021760.0000
Epoch 45/1000
20/20 - 0s - 2ms/step - loss: 5507128832.0000 - val_loss: 6179640832.0000
Epoch 46/1000
20/20 - 0s - 3ms/step - loss: 5498231808.0000 - val_loss: 6171115008.0000
Epoch 47/1000
20/20 - 0s - 2ms/step - loss: 5491408384.0000 - val_loss: 6162388992.0000
Epoch 48/1000
20/20 - 0s - 2ms/step - loss: 5484541440.0000 - val_loss: 6153580544.0000
Epoch 49/1000
20/20 - 0s - 2ms/step - loss: 5474894336.0000 - val_loss: 6144596992.0000
Epoch 50/1000
20/20 - 0s - 2ms/step - loss: 5469084160.0000 - val_loss: 6135471104.0000
Epoch 51/1000
20/20 - 0s - 2ms/step - loss: 5457083904.0000 - val_loss: 6126121472.0000
Epoch 52/1000
20/20 - 0s - 3ms/step - loss: 5452870656.0000 - val_loss: 6116728320.0000
Epoch 53/1000
20/20 - 0s - 3ms/step - loss: 5441939968.0000 - val_loss: 6107182592.0000
Epoch 54/1000
20/20 - 0s - 2ms/step - loss: 5432760320.0000 - val_loss: 6097441280.0000
Epoch 55/1000
20/20 - 0s - 2ms/step - loss: 5425835008.0000 - val_loss: 6087611392.0000
Epoch 56/1000
20/20 - 0s - 3ms/step - loss: 5414370304.0000 - val_loss: 6077632512.0000
Epoch 57/1000
20/20 - 0s - 2ms/step - loss: 5408127488.0000 - val_loss: 6067515392.0000
Epoch 58/1000
20/20 - 0s - 2ms/step - loss: 5399292928.0000 - val_loss: 6057357312.0000
Epoch 59/1000
20/20 - 0s - 2ms/step - loss: 5390472704.0000 - val_loss: 6047032320.0000
Epoch 60/1000
20/20 - 0s - 3ms/step - loss: 5380830208.0000 - val_loss: 6036601344.0000
Epoch 61/1000
20/20 - 0s - 3ms/step - loss: 5370031104.0000 - val_loss: 6026067456.0000
Epoch 62/1000
20/20 - 0s - 2ms/step - loss: 5363539968.0000 - val_loss: 6015379968.0000
Epoch 63/1000
20/20 - 0s - 2ms/step - loss: 5353489408.0000 - val_loss: 6004617728.0000
Epoch 64/1000
20/20 - 0s - 2ms/step - loss: 5344822784.0000 - val_loss: 5993719808.0000
Epoch 65/1000
20/20 - 0s - 2ms/step - loss: 5332479488.0000 - val_loss: 5982678016.0000
Epoch 66/1000
20/20 - 0s - 2ms/step - loss: 5324423168.0000 - val_loss: 5971560448.0000
Epoch 67/1000
20/20 - 0s - 2ms/step - loss: 5312182784.0000 - val_loss: 5960244224.0000
Epoch 68/1000
20/20 - 0s - 2ms/step - loss: 5302798848.0000 - val_loss: 5948841984.0000
Epoch 69/1000
20/20 - 0s - 2ms/step - loss: 5294926848.0000 - val_loss: 5937358848.0000
Epoch 70/1000
20/20 - 0s - 3ms/step - loss: 5285179904.0000 - val_loss: 5925763072.0000
Epoch 71/1000
20/20 - 0s - 2ms/step - loss: 5271203840.0000 - val_loss: 5913960960.0000
Epoch 72/1000
20/20 - 0s - 2ms/step - loss: 5263612416.0000 - val_loss: 5901984768.0000
Epoch 73/1000
20/20 - 0s - 2ms/step - loss: 5248769024.0000 - val_loss: 5889883648.0000
Epoch 74/1000
20/20 - 0s - 2ms/step - loss: 5244038144.0000 - val_loss: 5877749248.0000
Epoch 75/1000
20/20 - 0s - 2ms/step - loss: 5235923968.0000 - val_loss: 5865554944.0000
Epoch 76/1000
20/20 - 0s - 2ms/step - loss: 5221478912.0000 - val_loss: 5853255680.0000
Epoch 77/1000
20/20 - 0s - 2ms/step - loss: 5203805184.0000 - val_loss: 5840729600.0000
Epoch 78/1000
20/20 - 0s - 2ms/step - loss: 5198934528.0000 - val_loss: 5828071424.0000
Epoch 79/1000
20/20 - 0s - 2ms/step - loss: 5185125376.0000 - val_loss: 5815345152.0000
Epoch 80/1000
20/20 - 0s - 2ms/step - loss: 5175686144.0000 - val_loss: 5802574336.0000
Epoch 81/1000
20/20 - 0s - 2ms/step - loss: 5161560064.0000 - val_loss: 5789630464.0000
Epoch 82/1000
20/20 - 0s - 2ms/step - loss: 5151001088.0000 - val_loss: 5776644608.0000
Epoch 83/1000
20/20 - 0s - 3ms/step - loss: 5138827776.0000 - val_loss: 5763480576.0000
Epoch 84/1000
20/20 - 0s - 2ms/step - loss: 5134091776.0000 - val_loss: 5750395392.0000
Epoch 85/1000
20/20 - 0s - 2ms/step - loss: 5116143616.0000 - val_loss: 5737212928.0000
Epoch 86/1000
20/20 - 0s - 2ms/step - loss: 5100418560.0000 - val_loss: 5723762176.0000
Epoch 87/1000
20/20 - 0s - 2ms/step - loss: 5095025152.0000 - val_loss: 5710309888.0000
Epoch 88/1000
20/20 - 0s - 2ms/step - loss: 5083635200.0000 - val_loss: 5696819200.0000
Epoch 89/1000
20/20 - 0s - 2ms/step - loss: 5080962048.0000 - val_loss: 5683351040.0000
Epoch 90/1000
20/20 - 0s - 2ms/step - loss: 5058017280.0000 - val_loss: 5669736960.0000
Epoch 91/1000
20/20 - 0s - 2ms/step - loss: 5057208832.0000 - val_loss: 5656131584.0000
Epoch 92/1000
20/20 - 0s - 2ms/step - loss: 5040501248.0000 - val_loss: 5642408960.0000
Epoch 93/1000
20/20 - 0s - 2ms/step - loss: 5021606400.0000 - val_loss: 5628487168.0000
Epoch 94/1000
20/20 - 0s - 2ms/step - loss: 5005262336.0000 - val_loss: 5614375936.0000
Epoch 95/1000
20/20 - 0s - 3ms/step - loss: 4995146240.0000 - val_loss: 5600135680.0000
Epoch 96/1000
20/20 - 0s - 2ms/step - loss: 4996230144.0000 - val_loss: 5586032640.0000
Epoch 97/1000
20/20 - 0s - 2ms/step - loss: 4966032896.0000 - val_loss: 5571764736.0000
Epoch 98/1000
20/20 - 0s - 2ms/step - loss: 4953870848.0000 - val_loss: 5557283840.0000
Epoch 99/1000
20/20 - 0s - 2ms/step - loss: 4955894784.0000 - val_loss: 5542840832.0000
Epoch 100/1000
20/20 - 0s - 2ms/step - loss: 4940558336.0000 - val_loss: 5528434176.0000
Epoch 101/1000
20/20 - 0s - 2ms/step - loss: 4929306112.0000 - val_loss: 5513977344.0000
Epoch 102/1000
20/20 - 0s - 2ms/step - loss: 4909031936.0000 - val_loss: 5499369472.0000
Epoch 103/1000
20/20 - 0s - 2ms/step - loss: 4897338880.0000 - val_loss: 5484613632.0000
Epoch 104/1000
20/20 - 0s - 2ms/step - loss: 4878069760.0000 - val_loss: 5469827584.0000
Epoch 105/1000
20/20 - 0s - 2ms/step - loss: 4879430656.0000 - val_loss: 5455042048.0000
Epoch 106/1000
20/20 - 0s - 2ms/step - loss: 4848974848.0000 - val_loss: 5440121344.0000
Epoch 107/1000
20/20 - 0s - 2ms/step - loss: 4845066240.0000 - val_loss: 5425136640.0000
Epoch 108/1000
20/20 - 0s - 2ms/step - loss: 4832322560.0000 - val_loss: 5410138112.0000
Epoch 109/1000
20/20 - 0s - 2ms/step - loss: 4821721088.0000 - val_loss: 5395138048.0000
Epoch 110/1000
20/20 - 0s - 2ms/step - loss: 4800402432.0000 - val_loss: 5379988480.0000
Epoch 111/1000
20/20 - 0s - 2ms/step - loss: 4796404736.0000 - val_loss: 5364782592.0000
Epoch 112/1000
20/20 - 0s - 2ms/step - loss: 4779868160.0000 - val_loss: 5349579264.0000
Epoch 113/1000
20/20 - 0s - 2ms/step - loss: 4760963072.0000 - val_loss: 5334215680.0000
Epoch 114/1000
20/20 - 0s - 3ms/step - loss: 4749891072.0000 - val_loss: 5318820864.0000
Epoch 115/1000
20/20 - 0s - 2ms/step - loss: 4738787840.0000 - val_loss: 5303367680.0000
Epoch 116/1000
20/20 - 0s - 2ms/step - loss: 4726961664.0000 - val_loss: 5287936512.0000
Epoch 117/1000
20/20 - 0s - 2ms/step - loss: 4710760448.0000 - val_loss: 5272420352.0000
Epoch 118/1000
20/20 - 0s - 2ms/step - loss: 4698786816.0000 - val_loss: 5256879104.0000
Epoch 119/1000
20/20 - 0s - 2ms/step - loss: 4677068800.0000 - val_loss: 5241235456.0000
Epoch 120/1000
20/20 - 0s - 2ms/step - loss: 4671306752.0000 - val_loss: 5225581056.0000
Epoch 121/1000
20/20 - 0s - 2ms/step - loss: 4648532992.0000 - val_loss: 5209823232.0000
Epoch 122/1000
20/20 - 0s - 2ms/step - loss: 4644684288.0000 - val_loss: 5194099200.0000
Epoch 123/1000
20/20 - 0s - 2ms/step - loss: 4621029376.0000 - val_loss: 5178258944.0000
Epoch 124/1000
20/20 - 0s - 2ms/step - loss: 4614819840.0000 - val_loss: 5162407936.0000
Epoch 125/1000
20/20 - 0s - 2ms/step - loss: 4602425856.0000 - val_loss: 5146583552.0000
Epoch 126/1000
20/20 - 0s - 2ms/step - loss: 4597803520.0000 - val_loss: 5130809344.0000
Epoch 127/1000
20/20 - 0s - 2ms/step - loss: 4568819712.0000 - val_loss: 5114882048.0000
Epoch 128/1000
20/20 - 0s - 2ms/step - loss: 4542565888.0000 - val_loss: 5098818560.0000
Epoch 129/1000
20/20 - 0s - 2ms/step - loss: 4541406208.0000 - val_loss: 5082753536.0000
Epoch 130/1000
20/20 - 0s - 2ms/step - loss: 4518635520.0000 - val_loss: 5066573824.0000
Epoch 131/1000
20/20 - 0s - 2ms/step - loss: 4518254592.0000 - val_loss: 5050450432.0000
Epoch 132/1000
20/20 - 0s - 2ms/step - loss: 4489969152.0000 - val_loss: 5034206720.0000
Epoch 133/1000
20/20 - 0s - 2ms/step - loss: 4499703296.0000 - val_loss: 5018183168.0000
Epoch 134/1000
20/20 - 0s - 2ms/step - loss: 4470209024.0000 - val_loss: 5002019328.0000
Epoch 135/1000
20/20 - 0s - 3ms/step - loss: 4444585472.0000 - val_loss: 4985715712.0000
Epoch 136/1000
20/20 - 0s - 2ms/step - loss: 4441742336.0000 - val_loss: 4969435136.0000
Epoch 137/1000
20/20 - 0s - 2ms/step - loss: 4425141248.0000 - val_loss: 4953163776.0000
Epoch 138/1000
20/20 - 0s - 3ms/step - loss: 4404984832.0000 - val_loss: 4936758272.0000
Epoch 139/1000
20/20 - 0s - 2ms/step - loss: 4393598976.0000 - val_loss: 4920391168.0000
Epoch 140/1000
20/20 - 0s - 2ms/step - loss: 4385234944.0000 - val_loss: 4904041472.0000
Epoch 141/1000
20/20 - 0s - 2ms/step - loss: 4366606848.0000 - val_loss: 4887667200.0000
Epoch 142/1000
20/20 - 0s - 2ms/step - loss: 4371301888.0000 - val_loss: 4871331840.0000
Epoch 143/1000
20/20 - 0s - 2ms/step - loss: 4335759360.0000 - val_loss: 4854958592.0000
Epoch 144/1000
20/20 - 0s - 3ms/step - loss: 4325182464.0000 - val_loss: 4838514688.0000
Epoch 145/1000
20/20 - 0s - 2ms/step - loss: 4318577152.0000 - val_loss: 4822038528.0000
Epoch 146/1000
20/20 - 0s - 2ms/step - loss: 4299826688.0000 - val_loss: 4805590016.0000
Epoch 147/1000
20/20 - 0s - 2ms/step - loss: 4266959616.0000 - val_loss: 4789021184.0000
Epoch 148/1000
20/20 - 0s - 2ms/step - loss: 4266838784.0000 - val_loss: 4772410880.0000
Epoch 149/1000
20/20 - 0s - 2ms/step - loss: 4254666496.0000 - val_loss: 4755848704.0000
Epoch 150/1000
20/20 - 0s - 2ms/step - loss: 4251786240.0000 - val_loss: 4739378688.0000
Epoch 151/1000
20/20 - 0s - 3ms/step - loss: 4232470016.0000 - val_loss: 4722902528.0000
Epoch 152/1000
20/20 - 0s - 3ms/step - loss: 4196067584.0000 - val_loss: 4706279424.0000
Epoch 153/1000
20/20 - 0s - 3ms/step - loss: 4199998720.0000 - val_loss: 4689616896.0000
Epoch 154/1000
20/20 - 0s - 3ms/step - loss: 4181923328.0000 - val_loss: 4672995840.0000
Epoch 155/1000
20/20 - 0s - 3ms/step - loss: 4169251072.0000 - val_loss: 4656409088.0000
Epoch 156/1000
20/20 - 0s - 2ms/step - loss: 4173745920.0000 - val_loss: 4639886336.0000
Epoch 157/1000
20/20 - 0s - 2ms/step - loss: 4133849856.0000 - val_loss: 4623316992.0000
Epoch 158/1000
20/20 - 0s - 2ms/step - loss: 4113188608.0000 - val_loss: 4606609920.0000
Epoch 159/1000
20/20 - 0s - 2ms/step - loss: 4094701312.0000 - val_loss: 4589799936.0000
Epoch 160/1000
20/20 - 0s - 2ms/step - loss: 4098477312.0000 - val_loss: 4573131264.0000
Epoch 161/1000
20/20 - 0s - 2ms/step - loss: 4065846272.0000 - val_loss: 4556376576.0000
Epoch 162/1000
20/20 - 0s - 2ms/step - loss: 4058301952.0000 - val_loss: 4539667968.0000
Epoch 163/1000
20/20 - 0s - 2ms/step - loss: 4030154240.0000 - val_loss: 4522884608.0000
Epoch 164/1000
20/20 - 0s - 3ms/step - loss: 4010375424.0000 - val_loss: 4505981952.0000
Epoch 165/1000
20/20 - 0s - 2ms/step - loss: 4019241472.0000 - val_loss: 4489227264.0000
Epoch 166/1000
20/20 - 0s - 2ms/step - loss: 4001838336.0000 - val_loss: 4472482816.0000
Epoch 167/1000
20/20 - 0s - 2ms/step - loss: 4002057216.0000 - val_loss: 4455862784.0000
Epoch 168/1000
20/20 - 0s - 2ms/step - loss: 3971109120.0000 - val_loss: 4439205888.0000
Epoch 169/1000
20/20 - 0s - 3ms/step - loss: 3948308480.0000 - val_loss: 4422410240.0000
Epoch 170/1000
20/20 - 0s - 2ms/step - loss: 3947261952.0000 - val_loss: 4405734912.0000
Epoch 171/1000
20/20 - 0s - 2ms/step - loss: 3947878912.0000 - val_loss: 4389134336.0000
Epoch 172/1000
20/20 - 0s - 2ms/step - loss: 3910586112.0000 - val_loss: 4372484096.0000
Epoch 173/1000
20/20 - 0s - 2ms/step - loss: 3907470080.0000 - val_loss: 4355823616.0000
Epoch 174/1000
20/20 - 0s - 2ms/step - loss: 3898417920.0000 - val_loss: 4339165696.0000
Epoch 175/1000
20/20 - 0s - 2ms/step - loss: 3872618496.0000 - val_loss: 4322506240.0000
Epoch 176/1000
20/20 - 0s - 2ms/step - loss: 3851444736.0000 - val_loss: 4305791488.0000
Epoch 177/1000
20/20 - 0s - 3ms/step - loss: 3843357952.0000 - val_loss: 4289097984.0000
Epoch 178/1000
20/20 - 0s - 3ms/step - loss: 3813706496.0000 - val_loss: 4272354560.0000
Epoch 179/1000
20/20 - 0s - 3ms/step - loss: 3814757632.0000 - val_loss: 4255596544.0000
Epoch 180/1000
20/20 - 0s - 2ms/step - loss: 3781175808.0000 - val_loss: 4238810368.0000
Epoch 181/1000
20/20 - 0s - 2ms/step - loss: 3766997504.0000 - val_loss: 4221981184.0000
Epoch 182/1000
20/20 - 0s - 2ms/step - loss: 3768438272.0000 - val_loss: 4205215232.0000
Epoch 183/1000
20/20 - 0s - 3ms/step - loss: 3740084992.0000 - val_loss: 4188420864.0000
Epoch 184/1000
20/20 - 0s - 2ms/step - loss: 3707756800.0000 - val_loss: 4171539712.0000
Epoch 185/1000
20/20 - 0s - 2ms/step - loss: 3717473280.0000 - val_loss: 4154757632.0000
Epoch 186/1000
20/20 - 0s - 3ms/step - loss: 3706967552.0000 - val_loss: 4138072832.0000
Epoch 187/1000
20/20 - 0s - 3ms/step - loss: 3685599232.0000 - val_loss: 4121443072.0000
Epoch 188/1000
20/20 - 0s - 2ms/step - loss: 3674771456.0000 - val_loss: 4104755968.0000
Epoch 189/1000
20/20 - 0s - 2ms/step - loss: 3656972032.0000 - val_loss: 4088102912.0000
Epoch 190/1000
20/20 - 0s - 2ms/step - loss: 3631578368.0000 - val_loss: 4071381504.0000
Epoch 191/1000
20/20 - 0s - 3ms/step - loss: 3629285888.0000 - val_loss: 4054756864.0000
Epoch 192/1000
20/20 - 0s - 5ms/step - loss: 3627967488.0000 - val_loss: 4038225408.0000
Epoch 193/1000
20/20 - 0s - 5ms/step - loss: 3609018880.0000 - val_loss: 4021668608.0000
Epoch 194/1000
20/20 - 0s - 5ms/step - loss: 3597995264.0000 - val_loss: 4005116160.0000
Epoch 195/1000
20/20 - 0s - 3ms/step - loss: 3567075328.0000 - val_loss: 3988593920.0000
Epoch 196/1000
20/20 - 0s - 2ms/step - loss: 3551441920.0000 - val_loss: 3972066304.0000
Epoch 197/1000
20/20 - 0s - 2ms/step - loss: 3558961408.0000 - val_loss: 3955692032.0000
Epoch 198/1000
20/20 - 0s - 2ms/step - loss: 3527258368.0000 - val_loss: 3939286016.0000
Epoch 199/1000
20/20 - 0s - 2ms/step - loss: 3507321600.0000 - val_loss: 3922761728.0000
Epoch 200/1000
20/20 - 0s - 2ms/step - loss: 3473348864.0000 - val_loss: 3906208000.0000
Epoch 201/1000
20/20 - 0s - 3ms/step - loss: 3476667136.0000 - val_loss: 3889784320.0000
Epoch 202/1000
20/20 - 0s - 2ms/step - loss: 3468128000.0000 - val_loss: 3873391104.0000
Epoch 203/1000
20/20 - 0s - 2ms/step - loss: 3453644544.0000 - val_loss: 3856997888.0000
Epoch 204/1000
20/20 - 0s - 2ms/step - loss: 3443940096.0000 - val_loss: 3840711424.0000
Epoch 205/1000
20/20 - 0s - 2ms/step - loss: 3407722496.0000 - val_loss: 3824326144.0000
Epoch 206/1000
20/20 - 0s - 2ms/step - loss: 3410208000.0000 - val_loss: 3808004352.0000
Epoch 207/1000
20/20 - 0s - 2ms/step - loss: 3382287616.0000 - val_loss: 3791696128.0000
Epoch 208/1000
20/20 - 0s - 3ms/step - loss: 3362325504.0000 - val_loss: 3775395584.0000
Epoch 209/1000
20/20 - 0s - 2ms/step - loss: 3370339328.0000 - val_loss: 3759184384.0000
Epoch 210/1000
20/20 - 0s - 2ms/step - loss: 3346426112.0000 - val_loss: 3742987520.0000
Epoch 211/1000
20/20 - 0s - 2ms/step - loss: 3329671424.0000 - val_loss: 3726830080.0000
Epoch 212/1000
20/20 - 0s - 2ms/step - loss: 3300120576.0000 - val_loss: 3710609664.0000
Epoch 213/1000
20/20 - 0s - 2ms/step - loss: 3304640256.0000 - val_loss: 3694476800.0000
Epoch 214/1000
20/20 - 0s - 2ms/step - loss: 3305758208.0000 - val_loss: 3678437888.0000
Epoch 215/1000
20/20 - 0s - 2ms/step - loss: 3249595648.0000 - val_loss: 3662334720.0000
Epoch 216/1000
20/20 - 0s - 2ms/step - loss: 3268004608.0000 - val_loss: 3646353152.0000
Epoch 217/1000
20/20 - 0s - 2ms/step - loss: 3249477632.0000 - val_loss: 3630499328.0000
Epoch 218/1000
20/20 - 0s - 2ms/step - loss: 3224659200.0000 - val_loss: 3614562304.0000
Epoch 219/1000
20/20 - 0s - 2ms/step - loss: 3197843968.0000 - val_loss: 3598611456.0000
Epoch 220/1000
20/20 - 0s - 2ms/step - loss: 3197400320.0000 - val_loss: 3582721536.0000
Epoch 221/1000
20/20 - 0s - 2ms/step - loss: 3201112832.0000 - val_loss: 3566952448.0000
Epoch 222/1000
20/20 - 0s - 2ms/step - loss: 3161233920.0000 - val_loss: 3551179008.0000
Epoch 223/1000
20/20 - 0s - 2ms/step - loss: 3125224192.0000 - val_loss: 3535382272.0000
Epoch 224/1000
20/20 - 0s - 2ms/step - loss: 3147891968.0000 - val_loss: 3519658496.0000
Epoch 225/1000

           coef
tbats -0.162382
gb     1.608305
lstm  -0.330686

train RMSE: 13328.777
train MAE:  9338.785
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
Fitting 5 folds for each of 75 candidates, totalling 375 fits
Epoch 1/1000
20/20 - 1s - 29ms/step - loss: 6463740416.0000 - val_loss: 3668867840.0000
Epoch 2/1000
20/20 - 0s - 2ms/step - loss: 6463642624.0000 - val_loss: 3668774400.0000
Epoch 3/1000
20/20 - 0s - 2ms/step - loss: 6463484928.0000 - val_loss: 3668607232.0000
Epoch 4/1000
20/20 - 0s - 2ms/step - loss: 6463190016.0000 - val_loss: 3668331776.0000
Epoch 5/1000
20/20 - 0s - 2ms/step - loss: 6462758912.0000 - val_loss: 3667929600.0000
Epoch 6/1000
20/20 - 0s - 3ms/step - loss: 6462138880.0000 - val_loss: 3667396864.0000
Epoch 7/1000
20/20 - 0s - 4ms/step - loss: 6461317120.0000 - val_loss: 3666728448.0000
Epoch 8/1000
20/20 - 0s - 2ms/step - loss: 6460403200.0000 - val_loss: 3665926400.0000
Epoch 9/1000
20/20 - 0s - 2ms/step - loss: 6459259392.0000 - val_loss: 3664997376.0000
Epoch 10/1000
20/20 - 0s - 2ms/step - loss: 6458017792.0000 - val_loss: 3663950080.0000
Epoch 11/1000
20/20 - 0s - 2ms/step - loss: 6456353280.0000 - val_loss: 3662755328.0000
Epoch 12/1000
20/20 - 0s - 2ms/step - loss: 6454842880.0000 - val_loss: 3661435136.0000
Epoch 13/1000
20/20 - 0s - 3ms/step - loss: 6453009408.0000 - val_loss: 3660002560.0000
Epoch 14/1000
20/20 - 0s - 3ms/step - loss: 6451181568.0000 - val_loss: 3658460160.0000
Epoch 15/1000
20/20 - 0s - 2ms/step - loss: 6449261056.0000 - val_loss: 3656817664.0000
Epoch 16/1000
20/20 - 0s - 2ms/step - loss: 6446878720.0000 - val_loss: 3655064320.0000
Epoch 17/1000
20/20 - 0s - 2ms/step - loss: 6444503552.0000 - val_loss: 3653187072.0000
Epoch 18/1000
20/20 - 0s - 2ms/step - loss: 6442422272.0000 - val_loss: 3651227904.0000
Epoch 19/1000
20/20 - 0s - 2ms/step - loss: 6439832576.0000 - val_loss: 3649165312.0000
Epoch 20/1000
20/20 - 0s - 2ms/step - loss: 6436781568.0000 - val_loss: 3646973184.0000
Epoch 21/1000
20/20 - 0s - 2ms/step - loss: 6433935872.0000 - val_loss: 3644643072.0000
Epoch 22/1000
20/20 - 0s - 2ms/step - loss: 6430951936.0000 - val_loss: 3642205184.0000
Epoch 23/1000
20/20 - 0s - 2ms/step - loss: 6427454976.0000 - val_loss: 3639606784.0000
Epoch 24/1000
20/20 - 0s - 2ms/step - loss: 6423812608.0000 - val_loss: 3636878080.0000
Epoch 25/1000
20/20 - 0s - 2ms/step - loss: 6420203520.0000 - val_loss: 3634012160.0000
Epoch 26/1000
20/20 - 0s - 3ms/step - loss: 6416711680.0000 - val_loss: 3631040768.0000
Epoch 27/1000
20/20 - 0s - 2ms/step - loss: 6412086272.0000 - val_loss: 3627952384.0000
Epoch 28/1000
20/20 - 0s - 2ms/step - loss: 6409330688.0000 - val_loss: 3624764928.0000
Epoch 29/1000
20/20 - 0s - 2ms/step - loss: 6405010944.0000 - val_loss: 3621492480.0000
Epoch 30/1000
20/20 - 0s - 2ms/step - loss: 6400462848.0000 - val_loss: 3618090240.0000
Epoch 31/1000
20/20 - 0s - 2ms/step - loss: 6396466688.0000 - val_loss: 3614605312.0000
Epoch 32/1000
20/20 - 0s - 2ms/step - loss: 6391116800.0000 - val_loss: 3610965760.0000
Epoch 33/1000
20/20 - 0s - 2ms/step - loss: 6386032640.0000 - val_loss: 3607225856.0000
Epoch 34/1000
20/20 - 0s - 2ms/step - loss: 6381324800.0000 - val_loss: 3603378432.0000
Epoch 35/1000
20/20 - 0s - 2ms/step - loss: 6377345536.0000 - val_loss: 3599478784.0000
Epoch 36/1000
20/20 - 0s - 2ms/step - loss: 6372262400.0000 - val_loss: 3595500544.0000
Epoch 37/1000
20/20 - 0s - 2ms/step - loss: 6365928960.0000 - val_loss: 3591374080.0000
Epoch 38/1000
20/20 - 0s - 2ms/step - loss: 6361442304.0000 - val_loss: 3587136768.0000
Epoch 39/1000
20/20 - 0s - 2ms/step - loss: 6354255360.0000 - val_loss: 3582751232.0000
Epoch 40/1000
20/20 - 0s - 2ms/step - loss: 6350723584.0000 - val_loss: 3578316032.0000
Epoch 41/1000
20/20 - 0s - 2ms/step - loss: 6344391680.0000 - val_loss: 3573774336.0000
Epoch 42/1000
20/20 - 0s - 2ms/step - loss: 6338595328.0000 - val_loss: 3569110784.0000
Epoch 43/1000
20/20 - 0s - 2ms/step - loss: 6329987584.0000 - val_loss: 3564308992.0000
Epoch 44/1000
20/20 - 0s - 2ms/step - loss: 6324545024.0000 - val_loss: 3559380480.0000
Epoch 45/1000
20/20 - 0s - 2ms/step - loss: 6318487552.0000 - val_loss: 3554395392.0000
Epoch 46/1000
20/20 - 0s - 2ms/step - loss: 6313992704.0000 - val_loss: 3549356288.0000
Epoch 47/1000
20/20 - 0s - 2ms/step - loss: 6306973696.0000 - val_loss: 3544220416.0000
Epoch 48/1000
20/20 - 0s - 2ms/step - loss: 6298285056.0000 - val_loss: 3538966016.0000
Epoch 49/1000
20/20 - 0s - 2ms/step - loss: 6292439552.0000 - val_loss: 3533623808.0000
Epoch 50/1000
20/20 - 0s - 2ms/step - loss: 6285996544.0000 - val_loss: 3528195072.0000
Epoch 51/1000
20/20 - 0s - 3ms/step - loss: 6281947136.0000 - val_loss: 3522745600.0000
Epoch 52/1000
20/20 - 0s - 2ms/step - loss: 6273812480.0000 - val_loss: 3517238528.0000
Epoch 53/1000
20/20 - 0s - 3ms/step - loss: 6266236928.0000 - val_loss: 3511624960.0000
Epoch 54/1000
20/20 - 0s - 2ms/step - loss: 6257481216.0000 - val_loss: 3505909760.0000
Epoch 55/1000
20/20 - 0s - 2ms/step - loss: 6251596288.0000 - val_loss: 3500117504.0000
Epoch 56/1000
20/20 - 0s - 2ms/step - loss: 6245513728.0000 - val_loss: 3494242816.0000
Epoch 57/1000
20/20 - 0s - 2ms/step - loss: 6235976192.0000 - val_loss: 3488280832.0000
Epoch 58/1000
20/20 - 0s - 3ms/step - loss: 6227139072.0000 - val_loss: 3482176512.0000
Epoch 59/1000
20/20 - 0s - 2ms/step - loss: 6218562048.0000 - val_loss: 3475963392.0000
Epoch 60/1000
20/20 - 0s - 2ms/step - loss: 6209647616.0000 - val_loss: 3469651968.0000
Epoch 61/1000
20/20 - 0s - 2ms/step - loss: 6203685376.0000 - val_loss: 3463269888.0000
Epoch 62/1000
20/20 - 0s - 2ms/step - loss: 6194105856.0000 - val_loss: 3456800256.0000
Epoch 63/1000
20/20 - 0s - 2ms/step - loss: 6186191872.0000 - val_loss: 3450222848.0000
Epoch 64/1000
20/20 - 0s - 2ms/step - loss: 6178761728.0000 - val_loss: 3443585024.0000
Epoch 65/1000
20/20 - 0s - 3ms/step - loss: 6168728576.0000 - val_loss: 3436824832.0000
Epoch 66/1000
20/20 - 0s - 2ms/step - loss: 6160053248.0000 - val_loss: 3430022656.0000
Epoch 67/1000
20/20 - 0s - 2ms/step - loss: 6151447040.0000 - val_loss: 3423145728.0000
Epoch 68/1000
20/20 - 0s - 2ms/step - loss: 6145318912.0000 - val_loss: 3416215552.0000
Epoch 69/1000
20/20 - 0s - 2ms/step - loss: 6131120128.0000 - val_loss: 3409179392.0000
Epoch 70/1000
20/20 - 0s - 2ms/step - loss: 6126137856.0000 - val_loss: 3402053376.0000
Epoch 71/1000
20/20 - 0s - 3ms/step - loss: 6116328960.0000 - val_loss: 3394836224.0000
Epoch 72/1000
20/20 - 0s - 3ms/step - loss: 6108595712.0000 - val_loss: 3387568896.0000
Epoch 73/1000
20/20 - 0s - 3ms/step - loss: 6098678784.0000 - val_loss: 3380243456.0000
Epoch 74/1000
20/20 - 0s - 2ms/step - loss: 6089982464.0000 - val_loss: 3372895744.0000
Epoch 75/1000
20/20 - 0s - 2ms/step - loss: 6077947904.0000 - val_loss: 3365456896.0000
Epoch 76/1000
20/20 - 0s - 2ms/step - loss: 6065523200.0000 - val_loss: 3357870592.0000
Epoch 77/1000
20/20 - 0s - 2ms/step - loss: 6053901312.0000 - val_loss: 3350239744.0000
Epoch 78/1000
20/20 - 0s - 3ms/step - loss: 6051547648.0000 - val_loss: 3342564608.0000
Epoch 79/1000
20/20 - 0s - 4ms/step - loss: 6037427200.0000 - val_loss: 3334825472.0000
Epoch 80/1000
20/20 - 0s - 3ms/step - loss: 6028979200.0000 - val_loss: 3327055104.0000
Epoch 81/1000
20/20 - 0s - 3ms/step - loss: 6021039104.0000 - val_loss: 3319280384.0000
Epoch 82/1000
20/20 - 0s - 5ms/step - loss: 6007486464.0000 - val_loss: 3311388928.0000
Epoch 83/1000
20/20 - 0s - 2ms/step - loss: 5999111680.0000 - val_loss: 3303442688.0000
Epoch 84/1000
20/20 - 0s - 3ms/step - loss: 5987309568.0000 - val_loss: 3295436800.0000
Epoch 85/1000
20/20 - 0s - 3ms/step - loss: 5977166848.0000 - val_loss: 3287361024.0000
Epoch 86/1000
20/20 - 0s - 2ms/step - loss: 5968974336.0000 - val_loss: 3279249664.0000
Epoch 87/1000
20/20 - 0s - 2ms/step - loss: 5949576704.0000 - val_loss: 3271034112.0000
Epoch 88/1000
20/20 - 0s - 2ms/step - loss: 5944497152.0000 - val_loss: 3262765824.0000
Epoch 89/1000
20/20 - 0s - 2ms/step - loss: 5930101248.0000 - val_loss: 3254431488.0000
Epoch 90/1000
20/20 - 0s - 2ms/step - loss: 5916380672.0000 - val_loss: 3246043136.0000
Epoch 91/1000
20/20 - 0s - 2ms/step - loss: 5908827136.0000 - val_loss: 3237561856.0000
Epoch 92/1000
20/20 - 0s - 2ms/step - loss: 5896086528.0000 - val_loss: 3229055744.0000
Epoch 93/1000
20/20 - 0s - 2ms/step - loss: 5879009280.0000 - val_loss: 3220511232.0000
Epoch 94/1000
20/20 - 0s - 2ms/step - loss: 5873662464.0000 - val_loss: 3211918336.0000
Epoch 95/1000
20/20 - 0s - 2ms/step - loss: 5863804416.0000 - val_loss: 3203270400.0000
Epoch 96/1000
20/20 - 0s - 2ms/step - loss: 5861248512.0000 - val_loss: 3194707712.0000
Epoch 97/1000
20/20 - 0s - 2ms/step - loss: 5836985344.0000 - val_loss: 3186022656.0000
Epoch 98/1000
20/20 - 0s - 2ms/step - loss: 5833496576.0000 - val_loss: 3177326848.0000
Epoch 99/1000
20/20 - 0s - 2ms/step - loss: 5812250112.0000 - val_loss: 3168543232.0000
Epoch 100/1000
20/20 - 0s - 3ms/step - loss: 5810244096.0000 - val_loss: 3159680000.0000
Epoch 101/1000
20/20 - 0s - 3ms/step - loss: 5798440448.0000 - val_loss: 3150882048.0000
Epoch 102/1000
20/20 - 0s - 3ms/step - loss: 5777192448.0000 - val_loss: 3141965824.0000
Epoch 103/1000
20/20 - 0s - 2ms/step - loss: 5773895168.0000 - val_loss: 3133034240.0000
Epoch 104/1000
20/20 - 0s - 3ms/step - loss: 5756808192.0000 - val_loss: 3124080896.0000
Epoch 105/1000
20/20 - 0s - 2ms/step - loss: 5747015680.0000 - val_loss: 3115027968.0000
Epoch 106/1000
20/20 - 0s - 2ms/step - loss: 5732178432.0000 - val_loss: 3105943040.0000
Epoch 107/1000
20/20 - 0s - 2ms/step - loss: 5717550080.0000 - val_loss: 3096805376.0000
Epoch 108/1000
20/20 - 0s - 2ms/step - loss: 5713822720.0000 - val_loss: 3087648512.0000
Epoch 109/1000
20/20 - 0s - 2ms/step - loss: 5697050112.0000 - val_loss: 3078472192.0000
Epoch 110/1000
20/20 - 0s - 2ms/step - loss: 5687485952.0000 - val_loss: 3069241600.0000
Epoch 111/1000
20/20 - 0s - 2ms/step - loss: 5673628672.0000 - val_loss: 3060050176.0000
Epoch 112/1000
20/20 - 0s - 2ms/step - loss: 5656193536.0000 - val_loss: 3050787328.0000
Epoch 113/1000
20/20 - 0s - 2ms/step - loss: 5647209984.0000 - val_loss: 3041417728.0000
Epoch 114/1000
20/20 - 0s - 2ms/step - loss: 5619973632.0000 - val_loss: 3031928576.0000
Epoch 115/1000
20/20 - 0s - 3ms/step - loss: 5632409600.0000 - val_loss: 3022575872.0000
Epoch 116/1000
20/20 - 0s - 4ms/step - loss: 5612718592.0000 - val_loss: 3013192960.0000
Epoch 117/1000
20/20 - 0s - 3ms/step - loss: 5599325696.0000 - val_loss: 3003803904.0000
Epoch 118/1000
20/20 - 0s - 3ms/step - loss: 5588427264.0000 - val_loss: 2994329344.0000
Epoch 119/1000
20/20 - 0s - 3ms/step - loss: 5588167680.0000 - val_loss: 2984997376.0000
Epoch 120/1000
20/20 - 0s - 2ms/step - loss: 5564213760.0000 - val_loss: 2975542528.0000
Epoch 121/1000
20/20 - 0s - 2ms/step - loss: 5540917760.0000 - val_loss: 2965934592.0000
Epoch 122/1000
20/20 - 0s - 2ms/step - loss: 5533001216.0000 - val_loss: 2956343040.0000
Epoch 123/1000
20/20 - 0s - 2ms/step - loss: 5529077248.0000 - val_loss: 2946773248.0000
Epoch 124/1000
20/20 - 0s - 2ms/step - loss: 5508649472.0000 - val_loss: 2937215488.0000
Epoch 125/1000
20/20 - 0s - 2ms/step - loss: 5495528960.0000 - val_loss: 2927558912.0000
Epoch 126/1000
20/20 - 0s - 2ms/step - loss: 5476866560.0000 - val_loss: 2917861888.0000
Epoch 127/1000
20/20 - 0s - 2ms/step - loss: 5469837824.0000 - val_loss: 2908112640.0000
Epoch 128/1000
20/20 - 0s - 2ms/step - loss: 5456297984.0000 - val_loss: 2898386944.0000
Epoch 129/1000
20/20 - 0s - 2ms/step - loss: 5451314176.0000 - val_loss: 2888677888.0000
Epoch 130/1000
20/20 - 0s - 2ms/step - loss: 5446761984.0000 - val_loss: 2879028736.0000
Epoch 131/1000
20/20 - 0s - 2ms/step - loss: 5417900032.0000 - val_loss: 2869259008.0000
Epoch 132/1000
20/20 - 0s - 2ms/step - loss: 5412841472.0000 - val_loss: 2859463168.0000
Epoch 133/1000
20/20 - 0s - 3ms/step - loss: 5401160192.0000 - val_loss: 2849683968.0000
Epoch 134/1000
20/20 - 0s - 3ms/step - loss: 5372870144.0000 - val_loss: 2839778304.0000
Epoch 135/1000
20/20 - 0s - 3ms/step - loss: 5358627840.0000 - val_loss: 2829804800.0000
Epoch 136/1000
20/20 - 0s - 2ms/step - loss: 5348407296.0000 - val_loss: 2819748864.0000
Epoch 137/1000
20/20 - 0s - 2ms/step - loss: 5338031104.0000 - val_loss: 2809751296.0000
Epoch 138/1000
20/20 - 0s - 3ms/step - loss: 5322979840.0000 - val_loss: 2799728384.0000
Epoch 139/1000
20/20 - 0s - 2ms/step - loss: 5309022208.0000 - val_loss: 2789723648.0000
Epoch 140/1000
20/20 - 0s - 2ms/step - loss: 5289587200.0000 - val_loss: 2779643904.0000
Epoch 141/1000
20/20 - 0s - 2ms/step - loss: 5273349120.0000 - val_loss: 2769541376.0000
Epoch 142/1000
20/20 - 0s - 3ms/step - loss: 5256328704.0000 - val_loss: 2759408640.0000
Epoch 143/1000
20/20 - 0s - 2ms/step - loss: 5249290240.0000 - val_loss: 2749259776.0000
Epoch 144/1000
20/20 - 0s - 2ms/step - loss: 5232450048.0000 - val_loss: 2739066112.0000
Epoch 145/1000
20/20 - 0s - 3ms/step - loss: 5217207808.0000 - val_loss: 2728903168.0000
Epoch 146/1000
20/20 - 0s - 2ms/step - loss: 5196899840.0000 - val_loss: 2718684160.0000
Epoch 147/1000
20/20 - 0s - 2ms/step - loss: 5193180672.0000 - val_loss: 2708424448.0000
Epoch 148/1000
20/20 - 0s - 2ms/step - loss: 5183669760.0000 - val_loss: 2698272256.0000
Epoch 149/1000
20/20 - 0s - 2ms/step - loss: 5170583040.0000 - val_loss: 2688047616.0000
Epoch 150/1000
20/20 - 0s - 2ms/step - loss: 5157278208.0000 - val_loss: 2677904896.0000
Epoch 151/1000
20/20 - 0s - 2ms/step - loss: 5158479872.0000 - val_loss: 2667788032.0000
Epoch 152/1000
20/20 - 0s - 2ms/step - loss: 5108407296.0000 - val_loss: 2657560320.0000
Epoch 153/1000
20/20 - 0s - 2ms/step - loss: 5128072192.0000 - val_loss: 2647363328.0000
Epoch 154/1000
20/20 - 0s - 2ms/step - loss: 5104906752.0000 - val_loss: 2637200640.0000
Epoch 155/1000
20/20 - 0s - 2ms/step - loss: 5071424000.0000 - val_loss: 2626880000.0000
Epoch 156/1000
20/20 - 0s - 3ms/step - loss: 5065179136.0000 - val_loss: 2616545024.0000
Epoch 157/1000
20/20 - 0s - 2ms/step - loss: 5054313472.0000 - val_loss: 2606207744.0000
Epoch 158/1000
20/20 - 0s - 2ms/step - loss: 5041540608.0000 - val_loss: 2595876608.0000
Epoch 159/1000
20/20 - 0s - 2ms/step - loss: 5031469056.0000 - val_loss: 2585572096.0000
Epoch 160/1000
20/20 - 0s - 2ms/step - loss: 5025439232.0000 - val_loss: 2575262976.0000
Epoch 161/1000
20/20 - 0s - 3ms/step - loss: 5000482304.0000 - val_loss: 2564973056.0000
Epoch 162/1000
20/20 - 0s - 2ms/step - loss: 4978151424.0000 - val_loss: 2554628864.0000
Epoch 163/1000
20/20 - 0s - 2ms/step - loss: 4980260864.0000 - val_loss: 2544301824.0000
Epoch 164/1000
20/20 - 0s - 2ms/step - loss: 4954924544.0000 - val_loss: 2533978624.0000
Epoch 165/1000
20/20 - 0s - 2ms/step - loss: 4948732416.0000 - val_loss: 2523612928.0000
Epoch 166/1000
20/20 - 0s - 2ms/step - loss: 4942309888.0000 - val_loss: 2513305856.0000
Epoch 167/1000
20/20 - 0s - 2ms/step - loss: 4903683072.0000 - val_loss: 2502974208.0000
Epoch 168/1000
20/20 - 0s - 2ms/step - loss: 4903492608.0000 - val_loss: 2492592384.0000
Epoch 169/1000
20/20 - 0s - 2ms/step - loss: 4884600832.0000 - val_loss: 2482207232.0000
Epoch 170/1000
20/20 - 0s - 2ms/step - loss: 4889474048.0000 - val_loss: 2471903232.0000
Epoch 171/1000
20/20 - 0s - 2ms/step - loss: 4852032512.0000 - val_loss: 2461571584.0000
Epoch 172/1000
20/20 - 0s - 2ms/step - loss: 4841190912.0000 - val_loss: 2451202560.0000
Epoch 173/1000
20/20 - 0s - 2ms/step - loss: 4824820736.0000 - val_loss: 2440827392.0000
Epoch 174/1000
20/20 - 0s - 2ms/step - loss: 4799472128.0000 - val_loss: 2430399488.0000
Epoch 175/1000
20/20 - 0s - 2ms/step - loss: 4808791040.0000 - val_loss: 2420101120.0000
Epoch 176/1000
20/20 - 0s - 2ms/step - loss: 4782362112.0000 - val_loss: 2409755648.0000
Epoch 177/1000
20/20 - 0s - 2ms/step - loss: 4760301568.0000 - val_loss: 2399418624.0000
Epoch 178/1000
20/20 - 0s - 2ms/step - loss: 4775510528.0000 - val_loss: 2389178624.0000
Epoch 179/1000
20/20 - 0s - 2ms/step - loss: 4757751296.0000 - val_loss: 2378903552.0000
Epoch 180/1000
20/20 - 0s - 2ms/step - loss: 4723576320.0000 - val_loss: 2368622336.0000
Epoch 181/1000
20/20 - 0s - 2ms/step - loss: 4703718912.0000 - val_loss: 2358262528.0000
Epoch 182/1000
20/20 - 0s - 2ms/step - loss: 4694114304.0000 - val_loss: 2347899904.0000
Epoch 183/1000
20/20 - 0s - 2ms/step - loss: 4650344448.0000 - val_loss: 2337504000.0000
Epoch 184/1000
20/20 - 0s - 2ms/step - loss: 4648345088.0000 - val_loss: 2327050752.0000
Epoch 185/1000
20/20 - 0s - 2ms/step - loss: 4623960576.0000 - val_loss: 2316657920.0000
Epoch 186/1000
20/20 - 0s - 2ms/step - loss: 4620720640.0000 - val_loss: 2306273280.0000
Epoch 187/1000
20/20 - 0s - 2ms/step - loss: 4610546688.0000 - val_loss: 2295918592.0000
Epoch 188/1000
20/20 - 0s - 3ms/step - loss: 4609739776.0000 - val_loss: 2285593344.0000
Epoch 189/1000
20/20 - 0s - 2ms/step - loss: 4599398912.0000 - val_loss: 2275360256.0000
Epoch 190/1000
20/20 - 0s - 3ms/step - loss: 4575580672.0000 - val_loss: 2265107200.0000
Epoch 191/1000
20/20 - 0s - 2ms/step - loss: 4547235328.0000 - val_loss: 2254819072.0000
Epoch 192/1000
20/20 - 0s - 3ms/step - loss: 4556558336.0000 - val_loss: 2244565248.0000
Epoch 193/1000
20/20 - 0s - 2ms/step - loss: 4522283520.0000 - val_loss: 2234286592.0000
Epoch 194/1000
20/20 - 0s - 2ms/step - loss: 4501540352.0000 - val_loss: 2224033536.0000
Epoch 195/1000
20/20 - 0s - 2ms/step - loss: 4486286848.0000 - val_loss: 2213736960.0000
Epoch 196/1000
20/20 - 0s - 2ms/step - loss: 4481341952.0000 - val_loss: 2203466496.0000
Epoch 197/1000
20/20 - 0s - 2ms/step - loss: 4485268480.0000 - val_loss: 2193319168.0000
Epoch 198/1000
20/20 - 0s - 2ms/step - loss: 4436006400.0000 - val_loss: 2183101696.0000
Epoch 199/1000
20/20 - 0s - 2ms/step - loss: 4428397056.0000 - val_loss: 2172867072.0000
Epoch 200/1000
20/20 - 0s - 2ms/step - loss: 4425194496.0000 - val_loss: 2162666496.0000
Epoch 201/1000
20/20 - 0s - 3ms/step - loss: 4410121216.0000 - val_loss: 2152527360.0000
Epoch 202/1000
20/20 - 0s - 2ms/step - loss: 4387577856.0000 - val_loss: 2142399744.0000
Epoch 203/1000
20/20 - 0s - 2ms/step - loss: 4392403968.0000 - val_loss: 2132298752.0000
Epoch 204/1000
20/20 - 0s - 2ms/step - loss: 4370966528.0000 - val_loss: 2122255104.0000
Epoch 205/1000
20/20 - 0s - 2ms/step - loss: 4339748864.0000 - val_loss: 2112180096.0000
Epoch 206/1000
20/20 - 0s - 2ms/step - loss: 4346259968.0000 - val_loss: 2102079872.0000
Epoch 207/1000
20/20 - 0s - 2ms/step - loss: 4325632000.0000 - val_loss: 2092069248.0000
Epoch 208/1000
20/20 - 0s - 2ms/step - loss: 4283815168.0000 - val_loss: 2081968896.0000
Epoch 209/1000
20/20 - 0s - 2ms/step - loss: 4288758272.0000 - val_loss: 2071890432.0000
Epoch 210/1000
20/20 - 0s - 2ms/step - loss: 4253315584.0000 - val_loss: 2061858944.0000
Epoch 211/1000
20/20 - 0s - 2ms/step - loss: 4247900160.0000 - val_loss: 2051810176.0000
Epoch 212/1000
20/20 - 0s - 3ms/step - loss: 4235036672.0000 - val_loss: 2041796608.0000
Epoch 213/1000
20/20 - 0s - 2ms/step - loss: 4252778752.0000 - val_loss: 2031850752.0000
Epoch 214/1000
20/20 - 0s - 2ms/step - loss: 4213376000.0000 - val_loss: 2021954304.0000
Epoch 215/1000

In [ ]:
# cursor.close()

In [ ]:
dataset_0 = pd.DataFrame({k: v['dataset_0'] for k, v in summary_dict.items()}).T
dataset_1 = pd.DataFrame({k: v['dataset_1'] for k, v in summary_dict.items()}).T

In [ ]:
summary = (
    pd
    .concat([dataset_0, dataset_1], axis=0)
    .rename({'name': 'dataset'}, axis=1)
    .sort_index()
    .reset_index(names=['account_id', 'sales_channel_id'])
)
summary.to_csv('summary_ts.csv', sep=';')

summary

# Evaluating Model

In [ ]:
for account_id, sales_channel_id in id_pairs:
    ens_price_forecast = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast']
    ens_price_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_lower']
    ens_price_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_upper']
    
    forecast_price_ens = pd.concat([y_test, ens_price_forecast, ens_price_forecast_lower, ens_price_forecast_upper], axis=1)
    forecast_price_ens.columns = ['actual', 'forecast', 'lower', 'upper']
    
    df_forecast_price = forecast_price_ens.assign(
        covered_pts=lambda x:
            4*x['actual'].between(x['lower'], x['upper'], inclusive='both') +
            2*(x['actual'].between(2*x['lower']-x['forecast'], x['lower'], inclusive='left') + x['actual'].between(x['upper'], 2*x['upper']-x['forecast'], inclusive='right')) +
            1*(x['actual'].between(3*x['lower']-2*x['forecast'], 2*x['lower']-x['forecast'], inclusive='left') + x['actual'].between(2*x['upper']-x['forecast'], 3*x['upper']-2*x['forecast'], inclusive='right')),
        covered_width=lambda x: x['upper'] - x['lower'],
    )
    
    df_forecast_price_metrics = df_forecast_price.agg(total_covered=('covered_pts', 'sum'), avg_covered=('covered_pts', 'mean'), avg_covered_width=('covered_width', 'mean'))
    
    df_forecast_price_metrics_norm = df_forecast_price_metrics['avg_covered']/np.log(1+df_forecast_price_metrics['avg_covered_width'])
    
    ens_order_forecast = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast']
    ens_order_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_lower']
    ens_order_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_upper']
    
    forecast_order_ens = pd.concat([y_test, ens_order_forecast, ens_order_forecast_lower, ens_order_forecast_upper], axis=1)
    forecast_order_ens.columns = ['actual', 'forecast', 'lower', 'upper']
    
    df_forecast_order = forecast_order_ens.assign(
        covered_pts=lambda x:
            4*x['actual'].between(x['lower'], x['upper'], inclusive='both') +
            2*(x['actual'].between(2*x['lower']-x['forecast'], x['lower'], inclusive='left') + x['actual'].between(x['upper'], 2*x['upper']-x['forecast'], inclusive='right')) +
            1*(x['actual'].between(3*x['lower']-2*x['forecast'], 2*x['lower']-x['forecast'], inclusive='left') + x['actual'].between(2*x['upper']-x['forecast'], 3*x['upper']-2*x['forecast'], inclusive='right')),
        covered_width=lambda x: x['upper'] - x['lower'],
    )
    
    df_forecast_order_metrics = df_forecast_order.agg(total_covered=('covered_pts', 'sum'), avg_covered=('covered_pts', 'mean'), avg_covered_width=('covered_width', 'mean'))
    
    df_forecast_order_metrics_norm = df_forecast_order_metrics['avg_covered']/np.log(1+df_forecast_order_metrics['avg_covered_width'])
    
    df_forecast_metrics_norm += 0.7*df_forecast_price_metrics_norm + 0.3*df_forecast_order_metrics_norm

In [ ]:
forecast_price_ens = pd.concat([y_test, ens_price_forecast, ens_price_forecast_lower, ens_price_forecast_upper], axis=1)
forecast_price_ens.columns = ['actual', 'forecast', 'lower', 'upper']

In [ ]:
df_forecast_price = forecast_price_ens.assign(
    covered_pts=lambda x:
        4*x['actual'].between(x['lower'], x['upper'], inclusive='both') +
        2*(x['actual'].between(2*x['lower']-x['forecast'], x['lower'], inclusive='left') + x['actual'].between(x['upper'], 2*x['upper']-x['forecast'], inclusive='right')) +
        1*(x['actual'].between(3*x['lower']-2*x['forecast'], 2*x['lower']-x['forecast'], inclusive='left') + x['actual'].between(2*x['upper']-x['forecast'], 3*x['upper']-2*x['forecast'], inclusive='right')),
    covered_width=lambda x: x['upper'] - x['lower'],
)

In [ ]:
df_forecast_price_metrics = df_forecast_price.agg(total_covered=('covered_pts', 'sum'), avg_covered=('covered_pts', 'mean'), avg_covered_width=('covered_width', 'mean'))

In [ ]:
df_forecast_price_metrics_norm = df_forecast_price_metrics['avg_covered']/np.log(1+df_forecast_price_metrics['avg_covered_width'])